<?php
use Laminas\Session\Container;
$sessionLogin = new Container('credo');
?>
<div class="bg-body-light">
    <div class="content content-full">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
            <h1 class="flex-sm-fill font-size-h2 font-w400 mt-2 mb-0 mb-sm-2">Roles</h1>
            <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <a href="<?php echo $this->url('roles', array('action' => 'index')); ?>">
                        <li class="breadcrumb-item">Role Details</li>
                    </a>
                    <li class="breadcrumb-item active" aria-current="page">&nbsp;/ Edit</li>
                </ol>
            </nav>
        </div>
    </div>
</div>


<div class="content">
    <div class="block block-rounded block-bordered">
        <div class="block-header block-header-default">
            <h3 class="block-title">Edit Role Details</h3>
        </div>
        <div class="block-content">
            <div class="col-md-12 table-responsive" id="hide">
                <form name="addRoleInformation" id="addRoleInformation" class="mb-5" action="<?php echo $this->url('roles', array('action' => 'edit')); ?>" method="post" autocomplete="off">
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" for="">Role Name <span class="mandatory">*</span></label>
                        <div class="col-sm-4">
                            <input type="text" class="form-control isRequired" id="roleName" name="roleName" placeholder="Enter the role name" title="Please enter the role name" onblur="checkNameValidation('roles', 'role_name', this,'<?php echo "role_id##" .$result->role_id; ?>', 'The role name that you entered already exist. Please enter another name.');" value="<?php echo $result->role_name; ?>">
                            <input type="hidden" name="roleId"  value="<?php echo base64_encode($result->role_id); ?>" />
                        </div>

                        <label class="col-sm-2 col-form-label" for="">Role Code <span class="mandatory">*</span></label>
                        <div class="col-sm-4">
                            <input type="text" class="form-control isRequired" id="roleCode" name="roleCode" placeholder="Enter the role code" title="Please enter the role code" onblur="checkNameValidation('roles', 'role_code', this,'<?php echo "role_id##" .$result->role_id; ?>', 'The role code that you entered already exist . Please enter another code.');" value="<?php echo $result->role_code; ?>"/>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" for="">Status<span class="mandatory">*</span></label>
                        <div class="col-sm-4">
                            <select class="form-control isRequired" id="roleStatus" name="roleStatus" title="Please select the role status">
                                <option value="active" <?php echo(($result->role_status=='active') ? "selected='selected'" : "") ?>>Active</option>
                                <option value="inactive" <?php echo(($result->role_status=='inactive') ? "selected='selected'" : "") ?>>Inactive</option>
                            </select>
                        </div>
                    </div>
                    <fieldset>
                        <div class="form-group row">
                            <label class="col-sm-2 control-label">Note:</label>
                            <div class="col-sm-10">
                                <p class="form-control-static">Unless you choose "access" the people belonging to this role will not be able to access other rights like "add", "edit" etc.</p>
                            </div>
                        </div>
                        <div class="form-group" style="padding-left:134px;">
                            <strong>Select All</strong> <a style="color: #333;" href="javascript:void(0);" id="cekAllPrivileges"><input type='radio' class='layCek' name='cekUnCekAll'/> <i class='fa fa-check'></i></a>
			    &nbsp&nbsp&nbsp&nbsp<strong>Unselect All</strong> <a style="color: #333;" href="javascript:void(0);" id="unCekAllPrivileges"><input type='radio' class='layCek' name='cekUnCekAll' checked='checked'/> <i class='fa fa-times'></i></a>
                        </div>
                        <div class="table-responsive">
                        <table class="table table-striped table-hover responsive-utilities jambo_table">
                        <?php
                        $role = $result->role_code;
                        foreach ($resourceResult as $value) {
                        echo "<tr class=''>";
                        echo "<td><strong>" . ucwords($value['display_name']) . "</strong></td>";
                        foreach ($value['privilege'] as $privilege) {
                        if(isset($resourcePrivilegeMap[$role][$value['resource_id']][$privilege['privilege_name']]) && $resourcePrivilegeMap[$role][$value['resource_id']][$privilege['privilege_name']] == 'allow'){
										$allowChecked = " checked='' ";
											  $denyChecked = "";
											  } else {
											  $denyChecked = " checked='' ";
											  $allowChecked = "";
											  }
                        echo "<td>"
                        . "<label class='labelName'>" . ucwords($privilege['display_name']) . "</label>
                                                                
													  <label>
															  <input type='radio' class='cekAll layCek'  name='resource[" . $value['resource_id'] . "][" . $privilege['privilege_name'] . "]" . "' value='allow' $allowChecked> <i class='fa fa-check'></i>
													  </label>
													  <label>
															  <input type='radio' class='unCekAll layCek'  name='resource[" . $value['resource_id'] . "][" . $privilege['privilege_name'] . "]" . "' value='deny' $denyChecked>  <i class='fa fa-times'></i>
													  </label>
																		 
									  </td>";
                                                                        }
                                                                        echo "</tr>";
                                                                }
                                                                ?>	
                                                </table>
						</div>
                    </fieldset>
                    <div class="row items-push">
                        <div class="col-lg-7 offset-lg-4">
                            <a href="<?php echo $this->url('roles', array('action' => 'index')); ?>" class="btn btn-danger">Cancel</a>&nbsp;
                            <button type="submit" class="btn btn-primary" onclick="validateNow();return false;"><i class="fa fa-fw fa-check"></i> Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    duplicateName = true;

    function validateNow() {
        flag = deforayValidator.init({
            formId: 'addRoleInformation'
        });
        if (flag) {
            if (duplicateName) {
                $.blockUI();
                document.getElementById('addRoleInformation').submit();
            }
        }
    }

    function checkNameValidation(tableName, fieldName, obj, fnct, msg) {
        checkValue = document.getElementById(obj.id).value;
        if ($.trim(checkValue) != '') {
            $.post("<?php echo $this->url('common', array('action' => 'index')); ?>", {
                    tableName: tableName,
                    fieldName: fieldName,
                    value: checkValue,
                    fnct: fnct
                },
                function(data) {
                    if (data > 0) {
                        alert(msg);
                        duplicateName = false;
                        document.getElementById(obj.id).value = "";
                    } else {
                        duplicateName = true;
                    }
                });
        }
    }
    $("#cekAllPrivileges").click(function(){
      $('.unCekAll').prop('checked', false);
      $(".cekAll").prop( "checked", true );
    });

    $("#unCekAllPrivileges").click(function(){
      $('.unCekAll').prop('checked', true);
      $(".cekAll").prop( "checked", false );
    });
</script>