<?php
use Laminas\Session\Container;
$sessionLogin = new Container('credo');
?>
<style>
	.switch-field {
		display: flex;
		overflow: hidden;
	}

	.switch-field input {
		position: absolute !important;
		clip: rect(0, 0, 0, 0);
		height: 1px;
		width: 1px;
		border: 0;
		overflow: hidden;
	}

	.switch-field label {
		background-color: #e4e4e4;
		color: rgba(0, 0, 0, 0.6);
		font-size: 14px;
		line-height: 1;
		text-align: center;
		padding: 8px 16px;
		margin-right: -1px;
		border: 1px solid rgba(0, 0, 0, 0.2);
		box-shadow: inset 0 1px 3px rgba(0, 0, 0, 0.3), 0 1px rgba(255, 255, 255, 0.1);
		transition: all 0.1s ease-in-out;
	}

	.switch-field label:hover {
		cursor: pointer;
	}

	.switch-field input:checked+label {
		background-color: #87CEFA;
		box-shadow: none;
	}

	.switch-field label:first-of-type {
		border-radius: 4px 0 0 4px;
	}

	.switch-field label:last-of-type {
		border-radius: 0 4px 4px 0;
	}
    .pull-right {
        float: right !important;
    }
</style>
<div class="bg-body-light">
    <div class="content content-full">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
            <h1 class="flex-sm-fill font-size-h2 font-w400 mt-2 mb-0 mb-sm-2">Roles</h1>
            <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <a href="<?php echo $this->url('roles', array('action' => 'index')); ?>">
                        <li class="breadcrumb-item">Role Details</li>
                    </a>
                    <li class="breadcrumb-item active" aria-current="page">&nbsp;/ Edit</li>
                </ol>
            </nav>
        </div>
    </div>
</div>


<div class="content">
    <div class="block block-rounded block-bordered">
        <div class="block-header block-header-default">
            <h3 class="block-title">Edit Role Details</h3>
        </div>
        <div class="block-content">
            <div class="col-md-12 table-responsive" id="hide">
                <form name="addRoleInformation" id="addRoleInformation" class="mb-5" action="<?php echo $this->url('roles', array('action' => 'edit')); ?>" method="post" autocomplete="off">
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" for="">Role Name <span class="mandatory">*</span></label>
                        <div class="col-sm-4">
                            <input type="text" class="form-control isRequired" id="roleName" name="roleName" placeholder="Enter the role name" title="Please enter the role name" onblur="checkNameValidation('roles', 'role_name', this,'<?php echo "role_id##" .$result->role_id; ?>', 'The role name that you entered already exist. Please enter another name.');" value="<?php echo $result->role_name; ?>">
                            <input type="hidden" name="roleId"  value="<?php echo base64_encode($result->role_id); ?>" />
                        </div>

                        <label class="col-sm-2 col-form-label" for="">Role Code <span class="mandatory">*</span></label>
                        <div class="col-sm-4">
                            <input type="text" class="form-control isRequired" id="roleCode" name="roleCode" placeholder="Enter the role code" title="Please enter the role code" onblur="checkNameValidation('roles', 'role_code', this,'<?php echo "role_id##" .$result->role_id; ?>', 'The role code that you entered already exist . Please enter another code.');" value="<?php echo $result->role_code; ?>"/>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" for="">Status<span class="mandatory">*</span></label>
                        <div class="col-sm-4">
                            <select class="form-control isRequired" id="roleStatus" name="roleStatus" title="Please select the role status">
                                <option value="active" <?php echo(($result->role_status=='active') ? "selected='selected'" : "") ?>>Active</option>
                                <option value="inactive" <?php echo(($result->role_status=='inactive') ? "selected='selected'" : "") ?>>Inactive</option>
                            </select>
                        </div>
                    </div>
                    <fieldset>
                        <div class="form-group row">
                            <label class="col-sm-2 control-label">Note:</label>
                            <div class="col-sm-10">
                                <p class="form-control-static">Unless you choose "access" the people belonging to this role will not be able to access other rights like "add", "edit" etc.</p>
                            </div>
                        </div>
                        <div class="form-group" style="padding-left:138px;">
                            <div class="switch-field">
                                <input type="radio" class='layCek' id="cekAllPrivileges" name='cekUnCekAll'
                                    value="yes" />
                                <label for="cekAllPrivileges">
                                    <?php echo _("Select All"); ?>
                                </label>
                                <input type="radio" class='layCek' id="unCekAllPrivileges" name='cekUnCekAll' 
                                     value="no" />
                                <label for="unCekAllPrivileges">
                                    <?php echo _("Unselect All"); ?>
                                </label>
                            </div>
                        </div>
                        <table class="table table-striped responsive-utilities jambo_table">
                        <?php
                            $role = $result->role_code;
                            foreach ($resourceResult as $value) {
                                echo "<tr>";
                                    echo "<th>";
                                    ?>
                                    <small class="toggler">
                                        <h4 style="font-weight: bold;">
                                            <?= _(ucwords($value['display_name'])); ?>
                                        </h4>
                                        <div class="switch-field pull-right">
                                            <input type='radio' class='display_name' id='all<?= $value['display_name']; ?>'
                                                name='<?= $value['display_name']; ?>'
                                                onclick='togglePrivilegesForThisResource("<?= $value['display_name']; ?>",true);'>
                                            <label for='all<?= $value['display_name']; ?>'><?= _("All"); ?></label>
                                            <input type='radio' class='display_name' id='none<?= $value['display_name']; ?>'
                                                name='<?= $value['display_name']; ?>'
                                                onclick='togglePrivilegesForThisResource("<?= $value['display_name']; ?>",false);'>
                                            <label for='none<?= $value['display_name']; ?>'><?= _("None"); ?></label>
                                        </div>
                                    </small>
                                    <?php
                                    echo "</th>";
                                echo "</tr>";
                                echo "<tr class=''>";
                                echo "<td style='text-align:center;vertical-align:middle;' class='privilegesNode' id='" . $value['display_name'] . "'>";
                                foreach ($value['privilege'] as $privilege) {
                                    if(isset($resourcePrivilegeMap[$role][$value['resource_id']][$privilege['privilege_name']]) && $resourcePrivilegeMap[$role][$value['resource_id']][$privilege['privilege_name']] == 'allow'){
                                        $allowChecked = " checked='' ";
                                        $denyChecked = "";
                                    } else {
                                        $denyChecked = " checked='' ";
                                        $allowChecked = "";
                                    }
                                    echo "<div class='col-lg-3' style='float: left; margin-top:5px;border:1px solid #eee;padding:10px; width: 25%;'>
                                            <strong style='font-size: 14px;'>" . _($privilege['display_name']) . "</strong>
                                            <br>
                                            <div class='switch-field' style='margin: 30px 0 36px 40px;'>
                                                <input type='radio' class='cekAll layCek'  name='resource[" . $value['resource_id'] . "][" . $privilege['privilege_name'] . "]" ."'id='radio-one[" . $value['resource_id'] . "][" . $privilege['privilege_name'] . "]". "' value='allow' $allowChecked><label for='radio-one[" . $value['resource_id'] . "][" . $privilege['privilege_name'] . "]"."'>Yes</label>
                                                <input type='radio' class='unCekAll layCek'  name='resource[" . $value['resource_id'] . "][" . $privilege['privilege_name'] . "]" . "'id='radio-two[" . $value['resource_id'] . "][" . $privilege['privilege_name'] . "]"."' value='deny' $denyChecked> <label for='radio-two[" . $value['resource_id'] . "][" . $privilege['privilege_name'] . "]"."'> No</label>
                                            </div>
                                        </div>";
                                }
                            echo "</td></tr>";
                            }
                        echo "</table>";
                        ?>
                    </fieldset>
                    <div class="row items-push">
                        <div class="col-lg-7 offset-lg-4">
                            <a href="<?php echo $this->url('roles', array('action' => 'index')); ?>" class="btn btn-danger">Cancel</a>&nbsp;
                            <button type="submit" class="btn btn-primary" onclick="validateNow();return false;"><i class="fa fa-fw fa-check"></i> Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    duplicateName = true;

    function validateNow() {
        flag = deforayValidator.init({
            formId: 'addRoleInformation'
        });
        if (flag) {
            if (duplicateName) {
                $.blockUI();
                document.getElementById('addRoleInformation').submit();
            }
        }
    }

    function checkNameValidation(tableName, fieldName, obj, fnct, msg) {
        checkValue = document.getElementById(obj.id).value;
        if ($.trim(checkValue) != '') {
            $.post("<?php echo $this->url('common', array('action' => 'index')); ?>", {
                    tableName: tableName,
                    fieldName: fieldName,
                    value: checkValue,
                    fnct: fnct
                },
                function(data) {
                    if (data > 0) {
                        alert(msg);
                        duplicateName = false;
                        document.getElementById(obj.id).value = "";
                    } else {
                        duplicateName = true;
                    }
                });
        }
    }
    $("#cekAllPrivileges").click(function(){
      $('.unCekAll').prop('checked', false);
      $(".cekAll").prop( "checked", true );
    });

    $("#unCekAllPrivileges").click(function(){
      $('.unCekAll').prop('checked', true);
      $(".cekAll").prop( "checked", false );
    });

    function togglePrivilegesForThisResource(obj, checked) {
		if (checked == true) {
			$("#" + obj).find('.cekAll').prop('checked', true);
			$("#" + obj).find('.unCekAll').prop('checked', false);
		} else if (checked == false) {
			$("#" + obj).find('.cekAll').prop('checked', false);
			$("#" + obj).find('.unCekAll').prop('checked', true);
		}
	}
</script>