<?php
    use Laminas\Session\Container;
    $sessionLogin = new Container('credo');
    $roleCode = $sessionLogin->roleCode;
    $editAction = '{"sClass":"center"},{"sClass":"center"}';
?>
<div class="bg-body-light">
    <div class="content content-full">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
            <h1 class="flex-sm-fill font-size-h2 font-w400 mt-2 mb-0 mb-sm-2">Global Config</h1>
            <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="<?php echo $this->url('global-config',array('action' => 'edit'));?>" class="btn btn-primary pull-right" style="margin-right: 2px;" title="Edit"><i class="far fa-edit"></i> Edit</a>
                    </li>
                </ol>
            </nav>
        </div>
    </div>
</div>
<div class="content">
    <div class="block block-rounded block-bordered">
        <div class="block-header block-header-default">

        </div>
        <div class="block-content block-content-full">
            <table id="globalConfigDataTable" class="table table-bordered table-striped table-vcenter">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Value</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td colspan='2' class='dataTables_empty'>Loading data from server</td>
                    </tr>
                    <tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

<script type="text/javascript">
    /* Table initialisation */
    oTable = null;
    $(document).ready(function() {
        oTable = $('#globalConfigDataTable').dataTable( {
            "bAutoWidth": false,
            "bProcessing": true,
            "bServerSide": true,
            "aoColumns": [
                    <?php echo $editAction;?>
            ],
            "sAjaxSource": "<?php echo $this->url('global-config',array('action' => 'index')); ?>",
            "fnServerData": function ( sSource, aoData, fnCallback ) {
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
                });
            }
        } );
    } );
</script>
