<?php
    use Laminas\Session\Container;
?>
<div class="bg-body-light">
     <div class="content content-full">
          <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
               <h1 class="flex-sm-fill font-size-h2 font-w400 mt-2 mb-0 mb-sm-2">Recent User Login Attempts</h1>
                   
               </div>
          </div>
     </div>
     <div class="content">
          <div class="block block-rounded block-bordered">
               <div class="block-header block-header-default">
                    
               </div>
               <div class="block-content block-content-full">
                    <table id="facilityDataTable" class="table table-bordered table-striped table-vcenter table-responsive">
                         <thead>
                              <tr>
                                    <th>Login Attempt Date & Time</th>
                                    <th>User Name</th>
                                    <th>Login ID</th>
                                    <th>IP Address</th>
                                    <th>Browser</th>
                                    <th>Operating System</th>
                                    <th>Login Status</th>
                              </tr>
                         </thead>
                         <tbody>
                              <tr>
                                   <td colspan="7" class="dataTables_empty">Loading data from server</td>
                              </tr>
                              <tr>
                              </tbody>
                         </table>
                    </div>
               </div>
          </div>

          <script type="text/javascript">
          /* Table initialisation */
          oTable = null;
          $(document).ready(function() {
            oTable = $('#facilityDataTable').dataTable( {
                "bAutoWidth": false,
                "bProcessing": true,
                "bServerSide": true,
                "sAjaxSource": "<?php echo $this->url('monitoring',array('action' => 'allUserLoginHistory')); ?>",
                "fnServerData": function ( sSource, aoData, fnCallback ) {
                    $.ajax({
                        "dataType": 'json',
                        "type": "POST",
                        "url": sSource,
                        "data": aoData,
                        "success": fnCallback
                    });
                }
            } );

          } );

     </script>
