<?php
use Laminas\Session\Container;
$sessionLogin = new Container('credo');
//echo '<pre>'; print_r($result); die;
$auditRecency = $result['auditInfo'];
$currentRecency = $result['currentRecord'];
$sampleCode="";
if(isset($params['sampleCode']))
$sampleCode = $params['sampleCode'];
?>
<style>
	#current {
		display: block;
		overflow-x: auto;
		white-space: nowrap;
	}
	.select2-container--default .select2-selection--multiple .select2-selection__choice {color:black;}
</style>
<link rel="stylesheet" href="<?php echo $this->basePath() . '/assets/css/buttons.dataTables.min.css' ?>" rel="stylesheet">

<div class="bg-body-light">
     <div class="content content-full">
          <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
               <h1 class="flex-sm-fill font-size-h2 font-w400 mt-2 mb-0 mb-sm-2">Audit Trail</h1>
          </div>
     </div>
</div>


<div class="content">
     <div class="block block-rounded block-bordered">
          
          <div class="block-content">
               <div class="col-md-12 table-responsive" id="hide">
                    <form name="auditTrail" id="auditTrail"  class="mb-5" action="<?php echo $this->url('monitoring', array('action' => 'audit-trail')); ?>" method="post">
                         <div class="form-group row">
                              <label class="col-sm-4 col-form-label" for="">Sample Code OR Patient ID<span class="mandatory">*</span></label>
                              <div class="col-sm-4">
                                   <input type="text" value="<?php echo $sampleCode; ?>" class="form-control isRequired" id="sampleCode" name="sampleCode" placeholder="Enter the Sample Code Or Patient ID" title="Please enter the Sample Code Or Patient ID">
                              </div>
                         </div>
                         <div class="row items-push">
                              <div class="col-lg-7 offset-lg-4">
                                   <a href="<?php echo $this->url('monitoring', array('action' => 'audit-trail')); ?>" class="btn btn-danger">Cancel</a>&nbsp;
                                   <button type="submit" class="btn btn-primary" onclick="validateNow();return false;"><i class="fa fa-fw fa-check"></i> Submit</button>
                              </div>
                         </div>
                    </form>
               </div>
          </div>
     </div>
<?php if(!empty($sampleCode)){ 
	
	if (!empty($auditRecency)) {
	?>
     <h3> Audit Trail for Sample <?php echo $sampleCode; ?></h3>
	 
	 <select name="auditColumn[]" id="auditColumn" class="form-control" multiple="multiple">
	<?php
	$i=0;
	foreach($result['auditColumns'] as $col)
	{
	?>
	<option value="<?php echo $i; ?>"><?php echo $col['COLUMN_NAME']; ?></option>
	<?php
	$i++;
	}
	?>
	</select>
	
     <table border="1" id="auditTable" class="table table-bordered table-striped table-vcenter" aria-hidden="true">
								<thead>
									<tr>
										<?php
                                            $colArr = array();
										foreach ($result['auditColumns'] as $col) {
											$colArr[] = $col['COLUMN_NAME'];
										?>
											<th>
												<?php
												echo $col['COLUMN_NAME'];
												?>
											</th>
										<?php } ?>
									</tr>
								</thead>
								<tbody>
                                <?php
									
										for ($i = 0; $i < count($auditRecency); $i++) {
									?>
											<tr>
												<?php
												for ($j = 0; $j < count($colArr); $j++) {

													if (($j > 3) && ($i > 0) && $auditRecency[$i][$colArr[$j]] != $auditRecency[$i - 1][$colArr[$j]]) {
														echo '<td style="background: orange; color:black;" >' . $auditRecency[$i][$colArr[$j]] . '</td>';
													} else {
														echo '<td>' . $auditRecency[$i][$colArr[$j]] . '</td>';
													}
												?>
												<?php }
												?>
											</tr>
									<?php
										}
									?>
                                        </tbody>
                                        </table>
<br>
                                        <h3> Current Recency for Sample <?php echo $sampleCode; ?></h3>
                                        <table id="current" class="table table-striped table-hover table-bordered" aria-hidden="true">
								<thead>
									<tr>
										<?php
										$colValue=array();
										foreach ($result['recencyColumns'] as $col) {
                                                       $colValue[] = $col['COLUMN_NAME'];
										?>
											<th>
												<?php
												echo $col['COLUMN_NAME'];
												?>
											</th>
										<?php } ?>
									</tr>
								</thead>
								<tbody>
									
											<tr>
												<?php
												for ($j = 3; $j < count($colValue); $j++) {
												?>
													<td>
														<?php
														echo $currentRecency[$colValue[$j]];
														?>
													</td>
												<?php }
												?>
											</tr>
									
								</tbody>

							</table>
							<?php } 
							
							else
							{
								echo '<h3 align="center">Records are not available for this sample code. Please enter  valid sample code</h3>';
							}
						}
							
							?>
</div>
<script src="<?php echo $this->basePath() . '/assets/js/dataTables.buttons.min.js'; ?>"></script>
<script src="<?php echo $this->basePath() . '/assets/js/jszip.min.js'; ?>"></script>
<script src="<?php echo $this->basePath() . '/assets/js/buttons.html5.min.js'; ?>"></script>
<script type="text/javascript">
	function printString(columnNumber)
{
    // To store result (Excel column name)
        let columnName = [];
  
        while (columnNumber > 0) {
            // Find remainder
            let rem = columnNumber % 26;
  
            // If remainder is 0, then a
            // 'Z' must be there in output
            if (rem == 0) {
                columnName.push("Z");
                columnNumber = Math.floor(columnNumber / 26) - 1;
            }
            else // If remainder is non-zero
            {
                columnName.push(String.fromCharCode((rem - 1) + 'A'.charCodeAt(0)));
                columnNumber = Math.floor(columnNumber / 26);
            }
        }
  
        // Reverse the string and print result
        return columnName.reverse().join("");
}
oTable = null;
$(document).ready(function() {
         /* $("#auditTable").DataTable({
			scrollY: '50vh',
			scrollX: true,
			scrollCollapse: true,
			paging: false,
			"aaSorting": [1, "asc"]
		});*/
		$("#auditColumn").select2({
            placeholder: "Choose Audit Columns",
            //	allowClear: true,
        });

          oTable = $('#auditTable').DataTable( {
               dom: 'Bfrtip',
    buttons: [ 
	   {
	            extend: 'excelHtml5',
				exportOptions: {
                    columns: ':visible'
                },
	            text: 'Export To Excel',
	            title:'AuditTrailSample-<?php echo $sampleCode; ?>',
	            extension:'.xlsx',
				customize: function ( xlsx ) {
        var sheet = xlsx.xl.worksheets['sheet1.xml'];
        // Map used to map column index to Excel index
		
		var excelMap = [];
	b=0;
	for(a=1;a<=226;a++)
		{
				excelMap[b] = printString(a);
				b++;
		}
        var count = 0;
        var skippedHeader = 0;
		
        $('row', sheet).each( function () {
          var row = this;
          if (skippedHeader==2) {
//             var colour = $('tbody tr:eq('+parseInt(count)+') td:eq(2)').css('background-color');
            
            // Output first row
            if (count === 0) {
              console.log(this);
            }
            
            for (td=0; td<226; td++) {
              
              // Output cell contents for first row
              if (count === 0) {
                console.log($('c[r^="' + excelMap[td] + '"]', row).text());
              }
              var colour = $(oTable.cell(':eq('+count+')',td).node()).css('background-color');            

              if (colour === 'rgb(255, 165, 0)' || colour == 'orange') {
                $('c[r^="' + excelMap[td] + '"]', row).attr( 's', '35' );
              }
             
            }
            count++;
          }
          else {
            skippedHeader++;
          }
        });
      }
	        }
    ],
			scrollY: '250vh',
			scrollX: true,
			scrollCollapse: true,
			paging: false,
			"aaSorting": [1, "asc"],
            } );

           /* oTable1 = $('#current').dataTable( {
               
               scrollY: '50vh',
              scrollX: true,
              scrollCollapse: true,
              paging: false,
               "aaSorting": [1, "asc"]
           } );*/

		   $('#auditColumn').on("select2:select select2:unselect", function(e) {
		
		var columns = $(this).val();

		if(columns=="" || columns==null)
		{
			oTable.columns().visible(true);
		}
		else{
			oTable.columns().visible(false);
			oTable.columns(columns).visible(true);
		}
	
		});
     });

     duplicateName = true;
     function validateNow() {
          var selVal = [];
        

          flag = deforayValidator.init({
               formId: 'auditTrail'
          });
          if (flag) {
               if (duplicateName) {
                    $.blockUI();

                    document.getElementById('auditTrail').submit();
               }
          }
     }
   
    

</script>
