<?php

use Laminas\Session\Container;

$sessionLogin = new Container('credo');
$roleCode = $sessionLogin->roleCode;
$acl=$this->layout()->acl;

?>
<link rel="stylesheet" href="<?php echo $this->basePath() . '/assets/plugins/datepicker/daterangepicker.css' ?>" rel="stylesheet">
<div class="bg-body-light">
    <div class="content content-full">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
            <h1 class="flex-sm-fill font-size-h2 font-w400 mt-2 mb-0 mb-sm-2">Alerts</h1>
        </div>
    </div>
</div>
<div class="content">
    <div class="block block-rounded block-bordered">
        <div class="block-header block-header-default">
        </div>
        <div class="block-content block-content-full">
        <table id="advanceFilter" class="table" cellpadding="1" cellspacing="3" style="margin-left:1%;margin-top:20px;width: 98%;margin-bottom: 0px;">
                <tr>
                    <td><b> Date Range:</b></td>
                    <td>
                        <input type="text" class="form-control" id="alertedOn" placeholder="Alerted On" name="alertedOn" title="Please select alerted On Date" style="width:100%;" readonly>
                    </td>
                    <td><b>Alert Type:</b></td>
                    <td>
                    <select class="form-control" id="alertType" name="alertType" title="Please select alert type" style="width:100%;">
                        <option value="">All</option>
                            <?php
                            foreach($alertType as $alert)
                            {
                                $alrt = $alert['Expression1'];
                                ?>
                            <option value="<?php echo $alrt; ?>"><?php echo $alrt; ?></option>
                                <?php
                            }
                            ?>
                    </select>
                    </td>
                </tr>
                <tr>
                <td><b>Facility Name:</b></td>
                    <td>
                        <select class="form-control" id="facilityName" name="facilityName" title="Please select facility name" style="width:100%;">
                            <option value="">All</option>
                            <?php
                            foreach ($facilityResult['facility'] as $facilityRow)
                            {
                                ?>
                            <option value="<?php echo base64_encode($facilityRow['facility_id']); ?>"><?php echo ($facilityRow['facility_name']); ?></option>
                          <?php
                            }
                            ?>
                        </select>
                    </td>
                   <td></td>
                        </tr>
                <tr>
                    <td colspan="12" style=""><input type="button" onclick="searchVlRequestData();" value="Search" class="btn btn-info btn-sm">
                        &nbsp;<button class="btn btn-danger btn-sm" onclick="document.location.href = document.location"><span>Reset</span></button>
                    </td>
                </tr>
            </table>
            <table id="alertsDataTable" class="table table-bordered table-striped table-vcenter">
                <thead>
                    <tr>
                        <th>Facility Name</th>
                        <th>Lab Name</th>
                        <th>Alert Text</th>
                        <th>Alert Type</th>
                        <th>Alert Status</th>
                        <th>Alerted On</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
              <td colspan='5' class='dataTables_empty'>Loading data from server</td>
                       
                    </tr>
                </tbody>
                <tfoot>
                    <tr>
                        <th>Facility Name</th>
                        <th>Lab Name</th>
                        <th>Alert Text</th>
                        <th>Alert Type</th>
                        <th>Alert Status</th>
                        <th>Alerted On</th>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>
<script src="<?php echo $this->basePath() . '/assets/js/plugins/moment/moment.min.js'; ?>"></script>
<script type="text/javascript">
    
    let searchExecuted = false;
    /* Table initialisation */
    oTable = null;
    $(document).ready(function() {
      
        oTable = $('#alertsDataTable').dataTable({
            "bAutoWidth": false,
            "bProcessing": true,
            "bServerSide": true,
          
            "sAjaxSource": "<?php echo $this->url('monitoring', array('action' => 'system-alerts')); ?>",
            "fnServerData": function(sSource, aoData, fnCallback) {
                aoData.push({
                    "name": "alertedOn",
                    "value": $("#alertedOn").val()
                });
                aoData.push({
                    "name": "alertType",
                    "value": $("#alertType").val()
                });
                aoData.push({
                    "name": "facilityName",
                    "value": $("#facilityName").val()
                });
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
                });
            }
        });

        $('#alertedOn').daterangepicker({
            format: 'DD-MMM-YYYY',
            autoUpdateInput: false,
            separator: ' to ',
            startDate: moment().subtract('days', 29),
            endDate: moment(),
            maxDate: moment(),
            ranges: {
                'Today': [moment(), moment()],
                'Yesterday': [moment().subtract('days', 1), moment().subtract('days', 1)],
                'Last 7 Days': [moment().subtract('days', 6), moment()],
                'Last 30 Days': [moment().subtract('days', 29), moment()],
                'Last 60 Days': [moment().subtract('days', 59), moment()],
                'Last 180 Days': [moment().subtract('days', 179), moment()],
                'This Month': [moment().startOf('month'), moment().endOf('month')],
                'Last Month': [moment().subtract('month', 1).startOf('month'), moment().subtract('month', 1).endOf('month')]
            }
        },
        function(start, end) {
            startDate = start.format('YYYY-MM-DD');
            endDate = end.format('YYYY-MM-DD');
            $('input[name="alertedOn"]').on('apply.daterangepicker', function(ev, picker) {
                $(this).val(picker.startDate.format('DD-MMM-YYYY') + ' to ' + picker.endDate.format('DD-MMM-YYYY'));
            });

        });

    });

    function searchVlRequestData() {
        searchExecuted = true;
        $.blockUI();
        oTable.fnDraw();
        $.unblockUI();
    }

    function updateStatus(obj, optVal) {
		if (obj.value != '') {
			conf = confirm("<?php echo _("Are you sure you want to change the status?"); ?>");
			if (conf) {
				$.post("<?php echo $this->url('monitoring', array('action' => 'update-alert-status')); ?>", {
						status: obj.value,
						id: obj.id
					},
					function(data) {
						if (data != "") {
							oTable.fnDraw();
							alert("<?php echo _("Updated successfully"); ?>.");
						}
					});
			} else {
				window.top.location.href = window.top.location;
			}
		}
	}

</script>