<div class="bg-body-light">
     <div class="content content-full">
          <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
               <h1 class="flex-sm-fill font-size-h2 font-w400 mt-2 mb-0 mb-sm-2">Add Super Admin Details</h1>
               <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                    <ol class="breadcrumb">
                         <li class="breadcrumb-item">Super Admin</li>
                         <li class="breadcrumb-item active" aria-current="page">Add</li>
                    </ol>
               </nav>
          </div>
     </div>
</div>

<div class="content">
     <div class="block block-rounded block-bordered">
          <div class="block-header block-header-default">
               <h3 class="block-title">Super Admin</h3>
          </div>
          <div class="block-content">
               <div class="col-lg-12 col-xl-12">
                    <form name="addSuperAdminInformation" id="addSuperAdminInformation"  class="mb-5" action="<?php echo $this->url('super-admin', array('action' => 'add')); ?>" method="post">
                         <div class="form-group row">
                              <label class="col-sm-2 col-form-label" for="name">Name<span class="mandatory">*</span></label>
                              <div class="col-sm-4">
                                   <input type="text" title="Please enter the Name" class="form-control isRequired" id="name" name="name" placeholder="Name">
                              </div>

                         </div>

                         <div class="row form-group">
                              <label class="col-sm-2 col-form-label" for="emailAddress">Email Address <span class="mandatory">*</span></label>
                              <div class="col-sm-4">
                                   <input type="email" title="Please enter the Email Address" class="form-control isEmail isRequired" id="emailAddress" name="emailAddress" placeholder="Email address" onblur="checkNameValidation('system_admin', 'email', this, null,'The email address that you entered already exists. Please enter different email address')"/>
                              </div>
                         </div>
                         <div class="row form-group">
                              <label class="col-sm-2 col-form-label" for="password">Password<span class="mandatory">*</span></label>
                              <div class="col-sm-4">
                                   <input type="password" title="Please enter the Password" class="form-control isRequired" id="password" name="password" placeholder="Password">
                              </div>
                         </div>

                         <div class="row items-push">
                              <div class="col-lg-7 offset-lg-4">
                                   <a href="<?php echo $this->url('super-admin', array('action' => 'index')); ?>" class="btn btn-danger">Cancel</a>&nbsp;
                                   <button type="submit" class="btn btn-primary" onclick="validateNow();return false;"><i class="fa fa-fw fa-check"></i> Submit
                              </div>
                         </div>
                    </form>
               </div>
          </div>
     </div>
</div>

<script type="text/javascript">

duplicateName = true;
function validateNow() {
     flag = deforayValidator.init({
          formId: 'addSuperAdminInformation'
     });
     if (flag) {
          if (duplicateName) {
               $.blockUI();
               document.getElementById('addSuperAdminInformation').submit();
          }
     }
}

function checkNameValidation(tableName, fieldName, obj, fnct, msg){
     checkValue = document.getElementById(obj.id).value;
     if($.trim(checkValue)!= ''){
          $.post("<?php echo $this->url('common', array('action' => 'index')); ?>", {tableName: tableName, fieldName: fieldName, value: checkValue, fnct: fnct},
          function(data) {
               if (data > 0)
               {
                    alert(msg);
                    duplicateName = false;
                    document.getElementById(obj.id).value = "";
               }
               else {
                    duplicateName = true;
               }
          });
     }
}
</script>
