<?php
use Zend\Session\Container;
$sessionLogin = new Container('credo');
$uId = array();
//\Zend\Debug\Debug::dump($result['facilityMap']);die;
foreach($result['facilityMap'] as $data){
    $uId[] = $data['user_id'];
}
?>
<style type="text/css">
  .select2-selection__choice{
    color: black !important;
  }
</style>

<div class="bg-body-light">
     <div class="content content-full">
          <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
               <h1 class="flex-sm-fill font-size-h2 font-w400 mt-2 mb-0 mb-sm-2">Facilities</h1>
               <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                    <ol class="breadcrumb">
                         <a href="<?php echo $this->url('facilities', array('action' => 'index')); ?>"><li class="breadcrumb-item">Facilities Details</li></a>
                         <li class="breadcrumb-item active" aria-current="page">&nbsp;/ Edit</li>
                    </ol>
               </nav>
          </div>
     </div>
</div>

<div class="content">
    <div class="block block-rounded block-bordered">
        <div class="block-header block-header-default">
            <h3 class="block-title">Edit Facilities Details</h3>
        </div>
        <div class="block-content">
            <div class="col-md-12 table-responsive" id="hide">
                <form name="facilityInformation" id="facilityInformation"  class="mb-5" action="<?php echo $this->url('facilities', array('action' => 'edit')); ?>" method="post">
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" for="">Facility Name<span class="mandatory">*</span></label>
                        <div class="col-sm-4">
                            <input type="text" value="<?php echo $result['facility_name']; ?>" class="form-control isRequired" id="facilityName" name="facilityName" placeholder="Enter the facility name" title="Please enter the facility name" onblur="checkNameValidation('facility', 'facility_name', this,'NULL', 'The facility name that you entered already exists . Please try another name..');">
                        </div>
                        <label class="col-sm-2 col-form-label" for="">Email</label>
                        <div class="col-sm-4">
                            <input type="text" value="<?php echo $result['email']; ?>" class="form-control" id="email" name="email" placeholder="Enter the email" title="Please enter the email">
                        </div>
                    </div>

                    <div class="form-group row">
                    <label class="col-sm-2 col-form-label" for="">Alternate Email</label>
                        <div class="col-sm-4">
                            <input type="text" value="<?php echo $result['alt_email']; ?>" class="form-control" id="altEmail" name="altEmail" placeholder="Enter the alternate email" title="Please enter the alternate email">
                        </div>
                        <label class="col-sm-2 col-form-label" for="">Latitude</label>
                        <div class="col-sm-4">
                            <input type="text" value="<?php echo $result['latitude']; ?>"  class="form-control" id="latitude" name="latitude" placeholder="Enter the latitude" title="Please enter the latitude">
                        </div>


                    </div>

                    <div class="form-group row">
                    <label class="col-sm-2 col-form-label" for="">Longitude</label>
                        <div class="col-sm-4">
                            <input type="text" value="<?php echo $result['longitude']; ?>"  class="form-control" id="longitude" name="longitude" placeholder="Enter the longitude" title="Please enter the longitude">
                        </div>

                        <?php foreach($globalConfigResult as $config){ ?>
                                    <label style=" margin-bottom: 4%; " class="col-sm-2 col-form-label" for=""><?php echo ucfirst($config['global_value']); ?></label>
                                    <div class="col-sm-4">
                                        <select class="form-control" id="<?php echo $config['global_name']; ?>" name="<?php echo $config['global_name']; ?>" placeholder="Enter the <?php echo lcfirst($config['global_value']); ?>" title="Please enter the <?php echo lcfirst($config['global_value']); ?>" onchange="getLocationDeatils('<?php echo $config["global_name"];?>',null,null,null);">
                                            <option value="">-- Select --</option>
                                        </select>
                                    </div>
                                <?php } ?>

                        <label class="col-sm-2 col-form-label" for="">Status<span class="mandatory">*</span></label>
                        <div class="col-sm-4">
                            <select class="form-control isRequired" id="facilityStatus" name="facilityStatus" title="Please select the facility status">
                                <option value="">--select--</option>
                                <option value="active" <?php echo($result['status'] == 'active' )?'selected="selected"':''; ?>>Active</option>
                                <option value="inactive" <?php echo($result['status'] == 'inactive' )?'selected="selected"':''; ?>>Inactive</option>
                            </select>
                        </div>
                    </div>

                    <div class="form-group row">
                         <label class="col-sm-2 col-form-label" for="">Map User</label>
                         <div class="col-sm-4">
                              <select name="from[]" id="search" class="form-control" size="8" multiple="multiple">
                                   <?php foreach($userResult as $user){
                                       if(!in_array($user["user_id"],$uId)){
                                        ?>
                                        <option value="<?php echo $user['user_id']; ?>" ><?php echo ucwords($user['user_name']); ?></option>
                                   <?php }
                                   } ?>
                              </select>
                         </div>

                         <div class="col-md-2">
                              <button type="button" id="search_rightAll" class="btn btn-block"><i class="glyphicon glyphicon-forward"></i> >> </button>
                              <button type="button" id="search_rightSelected" class="btn btn-block"><i class="glyphicon glyphicon-chevron-right"> > </i></button>
                              <button type="button" id="search_leftSelected" class="btn btn-block"><i class="glyphicon glyphicon-chevron-left"></i> < </button>
                              <button type="button" id="search_leftAll" class="btn btn-block"><i class="glyphicon glyphicon-backward"></i> << </button>
                         </div>

                         <div class="col-sm-4">
                              <select name="to[]" id="search_to" class="form-control" size="8" multiple="multiple">
                                <?php foreach($result['facilityMap'] as $user){ ?>
                                        <option value="<?php echo $user['user_id']; ?>" selected='selected'><?php echo ucwords($user['user_name']); ?></option>
                                   <?php } ?>
                              </select>

                         </div>
                    </div>

                    <div class="row items-push">
                        <div class="col-lg-7 offset-lg-4">
                             <input type="hidden" name="selectedMapUser" id="selectedMapUser"/>
                            <input type="hidden" name="facilityId" value="<?php echo base64_encode($result['facility_id']); ?>"/>
                            <a href="<?php echo $this->url('facilities', array('action' => 'index')); ?>" class="btn btn-danger">Cancel</a>&nbsp;
                            <button type="submit" class="btn btn-primary" onclick="validateNow();return false;"><i class="fa fa-fw fa-check"></i> Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="//crlcu.github.io/multiselect/dist/js/multiselect.min.js"></script>
<script type="text/javascript">

     jQuery(document).ready(function($) {
        <?php
         foreach($globalConfigResult as $config){
             if($config['global_name']=='location_one'){
             ?>
             getLocationDeatils('<?php echo $config["global_name"];?>','<?php echo $result['province'];?>',null,null);
             <?php
             }else if($config['global_name']=='location_two')
             {
                 ?>
                getLocationDeatils('<?php echo $config["global_name"];?>','<?php echo $result['province'];?>','<?php echo $result['district'];?>',null);
                <?php
             }else if($config['global_name']=='location_three')
             {
                 ?>
                getLocationDeatils('<?php echo $config["global_name"];?>','<?php echo $result['province'];?>','<?php echo $result['district'];?>','<?php echo $result['city'];?>');
                <?php
             }
         }
         ?>

          $('#search').multiselect({
               search: {
                    left: '<input type="text" name="q" class="form-control" placeholder="Search..." />',
                    right: '<input type="text" name="q" class="form-control" placeholder="Search..." />',
               },
               fireSearch: function(value) {
                    return value.length > 3;
               }
          });
     });

     duplicateName = true;
     function validateNow() {

          var selVal = [];
          $('#search_to option').each(function(i, selected){
               selVal[i] = $(selected).val();
          });
          $("#selectedMapUser").val(selVal);


          flag = deforayValidator.init({
               formId: 'facilityInformation'
          });
          if (flag) {
               if (duplicateName) {
                    $.blockUI();
                    document.getElementById('facilityInformation').submit();
               }
          }
     }
     function checkNameValidation(tableName, fieldName, obj, fnct, msg){
         checkValue = document.getElementById(obj.id).value;
         if($.trim(checkValue)!= ''){
             $.post("<?php echo $this->url('common', array('action' => 'index')); ?>", { tableName: tableName, fieldName: fieldName, value: checkValue, companyId: companyId, existingCompanyId: existingCompanyId, fnct: fnct, srcfrom: 'SuperAdmin'},
             function(data) {
                 if (data > 0)
                 {
                         alert(msg);
                         duplicateName = false;
                         document.getElementById(obj.id).value = "";
                 }
                 else {
                         duplicateName = true;
                 }
             });
         }
     }
    function getLocationDeatils(globalName,value1,value2,value3)
     {

        var selectValue = document.getElementById(globalName).value;
        var innerId = '';
        var path = '';
        var selectedValue = '';
        if(value1!=null || value2!=null || value3!=null)
        {
            if(globalName=='location_one'){
                path = 'get-province';
                innerId = 'location_one';
                selectValue = value1;
                selectedValue = value1;
            }else if(globalName=='location_two'){
                path = 'get-district';
                innerId = 'location_two';
                selectValue = value1;
                selectedValue = value2;
            }else if(globalName=='location_three'){
                path = 'get-city';
                innerId = 'location_three';
                selectValue = value2;
                selectedValue = value3;
            }
        }else{
            if(globalName=='location_one' && selectValue==''){
                path = 'get-province';
                innerId = 'location_one';
            }else if(globalName=='location_one' && selectValue!=''){
                path = 'get-district';
                innerId = 'location_two';
                $("#location_three").html("<option value=''>-- Select --</option>");
            }else if(globalName=='location_two' && selectValue!=''){
                path = 'get-city';
                innerId = 'location_three';

            }
        }
            if(path!=''){
                $.blockUI();
                $.post("/common/"+path, {selectValue:selectValue},
                function(data) {
                    $("#"+innerId).html(data);
                    if(selectedValue!=''){
                        $("#"+innerId).val(selectedValue);
                    }
                    $.unblockUI();
                });
            }
     }
</script>
