<?php

use Application\Service\CommonService;
use Laminas\Session\Container;

$sessionLogin = new Container('credo');
$common = new CommonService();
$configResult = $this->CustomConfig();
// \Zend\Debug\Debug::dump($result);die;
// Extend the TCPDF class to create custom Header and Footer
class MYPDF extends TCPDF
{

    //Page header
    public function setHeading($logo, $text, $labname)
    {
        $this->logo = $logo;
        $this->text = $text;
        $this->labname = $labname;
    }

    public function Header()
    {

        if (trim($this->logo) != "") {
            if (file_exists(UPLOAD_PATH . DIRECTORY_SEPARATOR . "logo_image" . DIRECTORY_SEPARATOR . $this->logo)) {
                $image_file = UPLOAD_PATH . DIRECTORY_SEPARATOR . "logo_image" . DIRECTORY_SEPARATOR . $this->logo;
                $this->Image($image_file, 15, 10, 15, '', '', '', 'T', false, 300, '', false, false, 0, false, false, false);
            }
        }

        $this->SetFont('helvetica', '', 7);
        $this->writeHTMLCell(30, 0, 10, 26, $this->text, 0, 0, 0, true, 'A', true);
        $this->SetFont('helvetica', '', 13);
        $this->writeHTMLCell(0, 0, 0, 10, 'Recency Test - Specimen Manifest ', 0, 0, 0, true, 'C', true);
        $this->SetFont('helvetica', '', 10);
        $this->writeHTMLCell(0, 0, 0, 20, $this->labname, 0, 0, 0, true, 'C', true);

        // if (trim($this->logo) != "") {
        //     if (file_exists(UPLOAD_PATH . DIRECTORY_SEPARATOR . "logo_image" . DIRECTORY_SEPARATOR . $this->logo)) {
        //         $image_file = UPLOAD_PATH . DIRECTORY_SEPARATOR . "logo_image" . DIRECTORY_SEPARATOR . $this->logo;
        //         $this->Image($image_file, 262, 10, 15, '', '', '', 'T', false, 300, '', false, false, 0, false, false, false);
        //     }
        // }
        $this->SetFont('helvetica', '', 7);
        $this->writeHTMLCell(30, 0, 255, 26, $this->text, 0, 0, 0, true, 'A', true);
        $html = '<hr/>';
        $this->writeHTMLCell(0, 0, 10, 32, $html, 0, 0, 0, true, 'J', true);
    }

    // Page footer
    public function Footer()
    {
        // Position at 15 mm from bottom
        $this->SetY(-15);
        // Set font
        $this->SetFont('helvetica', '', 8);
        // Page number
        $this->Cell(0, 10,  'Specimen Manifest generated on : ' . date('d/m/Y H:i:s') . ' | Page ' . $this->getAliasNumPage() . '/' . $this->getAliasNbPages(), 0, false, 'C', 0, '', 0, false, 'T', 'M');
    }
    /* public static function getPageContentHeight(\TCPDF $pdf, $page)
    {
        // get total height of the page in user units
        $totalHeight = $pdf->getPageHeight($page) / $pdf->getScaleFactor();
        $margin = $pdf->getMargins();
        $pdfHeight->$totalHeight - $margin['bottom'] - $margin['top'];
    } */
}

if (!file_exists(UPLOAD_PATH . DIRECTORY_SEPARATOR . "package_barcode") && !is_dir(UPLOAD_PATH . DIRECTORY_SEPARATOR . "package_barcode")) {
    mkdir(UPLOAD_PATH . DIRECTORY_SEPARATOR . "package_barcode");
}
if ($result) {

    // create new PDF document
    $pdf = new MYPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
    $pdf->setHeading($globalConfigResult['logo_image'], $globalConfigResult['header'], $result[0]['testing_facility_name']);

    // set document information
    $pdf->SetCreator('RECENCY APP');
    $pdf->SetAuthor('RECENCY APP');
    $pdf->SetTitle('Specimen Manifest - ' . $result[0]['manifest_code']);
    $pdf->SetSubject('Specimen Manifest', $result[0]['manifest_code']);
    $pdf->SetKeywords('Specimen Manifest', $result[0]['manifest_code']);

    // set default header data
    $pdf->SetHeaderData(PDF_HEADER_LOGO, PDF_HEADER_LOGO_WIDTH, PDF_HEADER_TITLE, PDF_HEADER_STRING);

    // set header and footer fonts
    $pdf->setHeaderFont(array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
    $pdf->setFooterFont(array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

    // set default monospaced font
    $pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

    // set margins
    $pdf->SetMargins(PDF_MARGIN_LEFT, 36, PDF_MARGIN_RIGHT);
    $pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
    $pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

    // set auto page breaks
    $pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

    // set image scale factor
    $pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

    // set some language-dependent strings (optional)
    if (@file_exists(dirname(__FILE__) . '/lang/eng.php')) {
        require_once(dirname(__FILE__) . '/lang/eng.php');
        $pdf->setLanguageArray($l);
    }

    // set font
    $pdf->SetFont('helvetica', '', 10);
    $pdf->setPageOrientation('L');
    // add a page
    $pdf->AddPage();
    $tbl = '';

    $tbl .= '<table nobr="true" style="width:100%;" border="0" cellpadding="2">';
    $tbl .= '<tr nobr="true">';
    $tbl .= '<td style="width:50%;" align="center"><h1>' . $result[0]['manifest_code'] . '</h1></td>';
    $tbl .= '<td style="width:50%;" align="center"><strong> <img style="width:200px;height:30px;" src="'.$common->getBarcodeImageContent($result[0]['manifest_code'], 'C39').'"></strong></td>';
    $tbl .= '</tr>';
    $tbl .= '</table>';
    $tbl .= '<table nobr="true" style="width:100%;" border="1" cellpadding="2">
        
            <tr nobr="true">
                <td  style="font-size:11px;width:5%;" align="center"><strong>S/N</strong></td>
                <td  style="font-size:11px;width:15%;" align="center"><strong>SAMPLE ID</strong></td>
                <td  style="font-size:11px;width:15%;" align="center"><strong>HEALTH FACILITY, DISTRICT</strong></td>
                <td  style="font-size:11px;width:15%;" align="center"><strong>PATIENT (or) TRACNET ID</strong></td>
                <td  style="font-size:11px;width:5%;" align="center"><strong>AGE</strong></td>
                
                <td  style="font-size:11px;width:6%;" align="center"><strong>GENDER</strong></td>
                <td  style="font-size:11px;width:8%;" align="center"><strong>SPECIMEN TYPE</strong></td>
                <td  style="font-size:11px;width:10%;" align="center"><strong>COLLECTION DATE</strong></td>
                <td  style="font-size:11px;width:23%;" align="center"><strong>SAMPLE BARCODE</strong></td>
            </tr>';

    $sampleCounter = 1;

    $tbl .= '</table>';

    foreach ($result as $sample) {
        $collectionDate = '';
        if (isset($sample['sample_collection_date']) && $sample['sample_collection_date'] != '' && $sample['sample_collection_date'] != NULL && $sample['sample_collection_date'] != '0000-00-00 00:00:00') {
            $cDate = explode(" ", $sample['sample_collection_date']);
            $collectionDate = $common->humanDateFormat($cDate[0]);
        }
        $patientDOB = '';
        if (isset($sample['dob']) && $sample['dob'] != '' && $sample['dob'] != NULL && $sample['dob'] != '0000-00-00') {
            $patientDOB = $common->humanDateFormat($sample['dob']);
        }
        $tbl .= '<table nobr="true" style="width:100%;" border="1" cellpadding="2">';
        $tbl .= '<tr nobr="true">';
        $tbl .= '<td style="font-size:11px;width:5%;" align="center"><br><br>' . $sampleCounter . '.</td>';
        $tbl .= '<td style="font-size:11px;width:15%;" align="center"><br><br>' . $sample['sample_id'] . '</td>';
        $tbl .= '<td style="font-size:11px;width:15%;" align="center"><br><br>' . ($sample['facility_name']) . ', ' . ($sample['district_name']) . '</td>';
        $tbl .= '<td style="font-size:11px;width:15%;" align="center"><br><br>' . ucwords($sample['patient_id']) . '<br>' . $sample['patient_on_art'] . '</td>';
        $tbl .= '<td style="font-size:11px;width:5%;" align="center"><br><br>' . ucwords($sample['age']) . '</td>';
        // $tbl .= '<td style="font-size:11px;width:6%;" align="center"><br><br>' . $patientDOB . '</td>';
        $tbl .= '<td style="font-size:11px;width:6%;" align="center"><br><br>' . ucwords($sample['gender']) . '</td>';
        $tbl .= '<td style="font-size:11px;width:8%;" align="center"><br><br>' . $sample['sample_name']. '</td>';
        $tbl .= '<td style="font-size:11px;width:10%;" align="center"><br><br>' . $collectionDate . '</td>';
        $tbl .= '<td style="font-size:11px;width:23%;" align="center"><br><br> <img style="width:200px;height:30px;" src="'.$common->getBarcodeImageContent($sample['manifest_code'], 'C39').'"></td>';
        $tbl .= '</tr>';
        $tbl .= '</table>';

        $sampleCounter++;
    }


    $tbl .= '<br><br><br><br><table cellspacing="0" style="width:100%;">';
    $tbl .= '<tr style="">';
    $tbl .= '<td align="right" style="font-size:10px;width:15%;"><b>Generated By : </b></td><td align="left" style="width:18.33%;"><span style="font-size:12px;">' . $sessionLogin->userName . '</span></td>';
    $tbl .= '<td align="right" style="font-size:10px;width:15%;"><b>Verified By :  </b></td><td style="width:18.33%;"></td>';
    $tbl .= '<td align="right" style="font-size:10px;width:15%;"><b>Received By : <br>(at Referral lab/NRL)</b></td><td style="width:18.33%;"></td>';
    $tbl .= '</tr>';
    $tbl .= '</table>';
}
$pdf->writeHTML($tbl);

$pdf->Output($result[0]['manifest_code']  . '-Recency-Testing-Specimen-Manifest.pdf', 'I');

exit;
