
<?php
$district = '<option value="">-- Select --</option>';
if(count($result['district'])>0){
    foreach($result['district'] as $name){
        $district .='<option value="'.$name['district_id'].'">'.$name['district_name'].'</option>';
    }
}
//$district .='<option value="other">Other</option>';

$facility = '';
if(count($result['facility'])>0){
    foreach($result['facility'] as $name){
        $facility .='<option value="'.base64_encode($name['facility_id']).'">'.$name['facility_name'].'</option>';
    }
}
//$facility .='<option value="other">Other</option>';

echo $district.'##'.$facility;

