<?php
$city = '<option value="">-- Select --</option>';
if(count($result['city'])>0){
    foreach($result['city'] as $name){
        $city .='<option value="'.$name['city_id'].'">'.$name['city_name'].'</option>';
    }
}
$city .='<option value="other">Other</option>';


$facility = '';
if(count($result['facility'])>0){
    foreach($result['facility'] as $name){
        $facility .='<option value="'.base64_encode($name['facility_id']).'">'.$name['facility_name'].'</option>';
    }
}
//$facility .='<option value="other">Other</option>';

echo $city.'##'.$facility;