<?php
return array(
    'sss' => array(
        'Application\\Controller\\RolesController' => array(
            'index' => 'allow',
            'add' => 'allow',
        ),
    ),
    'manager' => array(
        'Application\\Controller\\RolesController' => array(
            'index' => 'allow',
            'add' => 'deny',
        ),
    ),
    'admin' => array(
        'Application\\Controller\\RecencyController' => array(
            'index' => 'allow',
            'add' => 'allow',
            'download-result-pdf' => 'allow',
            'edit' => 'allow',
            'email-result' => 'allow',
            'email-result-pdf' => 'allow',
            'export-recency' => 'allow',
            'generate-pdf' => 'allow',
        ),
        'Application\\Controller\\VlDataController' => array(
            'index' => 'allow',
            'get-sample-data' => 'allow',
            'update-vl-sample-result' => 'allow',
            'upload-result' => 'allow',
        ),
        'Application\\Controller\\IndexController' => array(
            'analysis-dashboard' => 'allow',
            'index' => 'allow',
            'quality-control-dashboard' => 'allow',
            'export-recency-data' => 'allow',
        ),
        'Application\\Controller\\CityController' => array(
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
        ),
        'Application\\Controller\\DistrictController' => array(
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
        ),
        'Application\\Controller\\FacilitiesController' => array(
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
        ),
        'Application\\Controller\\GlobalConfigController' => array(
            'index' => 'allow',
            'edit' => 'allow',
        ),
        'Application\\Controller\\ProvinceController' => array(
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
        ),
        'Application\\Controller\\RolesController' => array(
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
        ),
        'Application\\Controller\\UserController' => array(
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
            'edit-profile' => 'allow',
        ),
        'Application\\Controller\\ManifestsController' => array(
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
            'genarate-manifest' => 'allow',
        ),
        'Application\\Controller\\MonitoringController' => array(
            'all-user-login-history' => 'allow',
            'api-history' => 'allow',
            'audit-trail' => 'allow',
            'system-alerts' => 'allow',
            'user-activity-log' => 'allow',
        ),
        'Application\\Controller\\PrintResultsController' => array(
            'index' => 'allow',
        ),
        'Application\\Controller\\QualityCheckController' => array(
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
            'export-qc-data' => 'allow',
        ),
        'Application\\Controller\\ReportsController' => array(
            'age-wise-infection-report' => 'allow',
            'export-long-term-infected-data' => 'allow',
            'export-modality' => 'allow',
            'export-r-infected-data' => 'allow',
            'export-tat-report' => 'allow',
            'export-weekly-report' => 'allow',
            'lt-infection' => 'allow',
            'qc-report' => 'allow',
            'recent-infection' => 'allow',
            'tat-report' => 'allow',
            'weekly-report' => 'allow',
        ),
        'Application\\Controller\\SettingsController' => array(
            'index' => 'allow',
            'add' => 'allow',
            'add-sample' => 'allow',
            'edit' => 'allow',
            'edit-sample' => 'allow',
        ),
    ),
    'user' => array(
        'Application\\Controller\\RecencyController' => array(
            'index' => 'allow',
            'add' => 'allow',
            'download-result-pdf' => 'deny',
            'edit' => 'allow',
            'email-result' => 'deny',
            'email-result-pdf' => 'deny',
            'export-recency' => 'allow',
            'generate-pdf' => 'allow',
        ),
        'Application\\Controller\\VlDataController' => array(
            'index' => 'allow',
            'get-sample-data' => 'allow',
            'update-vl-sample-result' => 'allow',
            'upload-result' => 'allow',
        ),
        'Application\\Controller\\IndexController' => array(
            'analysis-dashboard' => 'allow',
            'index' => 'allow',
            'quality-control-dashboard' => 'allow',
            'export-recency-data' => 'allow',
        ),
        'Application\\Controller\\CityController' => array(
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
        ),
        'Application\\Controller\\DistrictController' => array(
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
        ),
        'Application\\Controller\\FacilitiesController' => array(
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
        ),
        'Application\\Controller\\GlobalConfigController' => array(
            'index' => 'allow',
            'edit' => 'allow',
        ),
        'Application\\Controller\\ProvinceController' => array(
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
        ),
        'Application\\Controller\\RolesController' => array(
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
        ),
        'Application\\Controller\\UserController' => array(
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
            'edit-profile' => 'deny',
        ),
        'Application\\Controller\\ManifestsController' => array(
            'index' => 'allow',
            'add' => 'deny',
            'edit' => 'allow',
            'genarate-manifest' => 'allow',
        ),
        'Application\\Controller\\MonitoringController' => array(
            'all-user-login-history' => 'allow',
            'api-history' => 'deny',
            'audit-trail' => 'allow',
            'system-alerts' => 'deny',
            'user-activity-log' => 'allow',
        ),
        'Application\\Controller\\PrintResultsController' => array(
            'index' => 'allow',
        ),
        'Application\\Controller\\QualityCheckController' => array(
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
            'export-qc-data' => 'allow',
        ),
        'Application\\Controller\\ReportsController' => array(
            'age-wise-infection-report' => 'deny',
            'export-long-term-infected-data' => 'deny',
            'export-modality' => 'deny',
            'export-r-infected-data' => 'deny',
            'export-tat-report' => 'deny',
            'export-weekly-report' => 'deny',
            'lt-infection' => 'deny',
            'qc-report' => 'deny',
            'recent-infection' => 'deny',
            'tat-report' => 'deny',
            'weekly-report' => 'deny',
        ),
        'Application\\Controller\\SettingsController' => array(
            'index' => 'allow',
            'add' => 'allow',
            'add-sample' => 'allow',
            'edit' => 'allow',
            'edit-sample' => 'allow',
        ),
    ),
    'remote_order_user' => array(
        'Application\\Controller\\RecencyController' => array(
            'index' => 'allow',
            'add' => 'allow',
            'download-result-pdf' => 'allow',
            'edit' => 'allow',
            'email-result' => 'allow',
            'email-result-pdf' => 'allow',
            'export-recency' => 'allow',
            'generate-pdf' => 'allow',
        ),
        'Application\\Controller\\VlDataController' => array(
            'index' => 'allow',
            'get-sample-data' => 'allow',
            'update-vl-sample-result' => 'allow',
            'upload-result' => 'allow',
        ),
        'Application\\Controller\\IndexController' => array(
            'analysis-dashboard' => 'allow',
            'index' => 'allow',
            'quality-control-dashboard' => 'allow',
            'export-recency-data' => 'allow',
        ),
        'Application\\Controller\\CityController' => array(
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
        ),
        'Application\\Controller\\DistrictController' => array(
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
        ),
        'Application\\Controller\\FacilitiesController' => array(
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
        ),
        'Application\\Controller\\GlobalConfigController' => array(
            'index' => 'allow',
            'edit' => 'allow',
        ),
        'Application\\Controller\\ProvinceController' => array(
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
        ),
        'Application\\Controller\\RolesController' => array(
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
        ),
        'Application\\Controller\\UserController' => array(
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
            'edit-profile' => 'allow',
        ),
        'Application\\Controller\\ManifestsController' => array(
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
            'genarate-manifest' => 'allow',
        ),
        'Application\\Controller\\MonitoringController' => array(
            'all-user-login-history' => 'allow',
            'api-history' => 'allow',
            'audit-trail' => 'allow',
            'system-alerts' => 'allow',
            'user-activity-log' => 'allow',
        ),
        'Application\\Controller\\PrintResultsController' => array(
            'index' => 'allow',
        ),
        'Application\\Controller\\QualityCheckController' => array(
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
            'export-qc-data' => 'allow',
        ),
        'Application\\Controller\\ReportsController' => array(
            'age-wise-infection-report' => 'allow',
            'export-long-term-infected-data' => 'allow',
            'export-modality' => 'allow',
            'export-r-infected-data' => 'allow',
            'export-tat-report' => 'allow',
            'export-weekly-report' => 'allow',
            'lt-infection' => 'allow',
            'qc-report' => 'allow',
            'recent-infection' => 'allow',
            'tat-report' => 'allow',
            'weekly-report' => 'allow',
        ),
        'Application\\Controller\\SettingsController' => array(
            'index' => 'allow',
            'add' => 'allow',
            'add-sample' => 'allow',
            'edit' => 'allow',
            'edit-sample' => 'allow',
        ),
    ),
);
