<?php
/**
 * Configuration file generated by ZFTool
 * The previous configuration file is stored in application.config.old
 *
 * @see https://github.com/zendframework/ZFTool
 */
return array(
    'modules' => array(
        'Laminas\Mail',
        'Laminas\Serializer',
        'Laminas\Mvc\Plugin\FilePrg',
        'Laminas\Mvc\Plugin\FlashMessenger',
        'Laminas\Mvc\Plugin\Identity',
        'Laminas\Mvc\Plugin\Prg',
        'Laminas\Session',
        'Laminas\Mvc\Middleware',
        'Laminas\Mvc\I18n',
        'Laminas\Router',
        'Laminas\Form',
        'Laminas\I18n',
        'Laminas\Log',
        'Laminas\InputFilter',
        'Laminas\Filter',
        'Laminas\Validator',
        'Laminas\Hydrator',
        'Laminas\Di',
        'Laminas\Db',
        'Laminas\Cache',
        'Laminas\ZendFrameworkBridge',
        'Laminas\Diactoros',
        'Application',
        'Api',
        'EdpModuleLayouts'
    ),
    'module_listener_options' => array(
        'module_paths' => array(
            './module',
            './vendor',
        ),
        'config_glob_paths' => array(
            'config/autoload/{{,*.}global,{,*.}local}.php',
        ),
    ),
);
