<?php
use Zend\Session\Container;
$sessionLogin = new Container('credo');
$arr = array();
// now we create an associative array so that we can easily create view variables
for ($i = 0; $i < sizeof($globalConfigResult); $i++) {
    $arr[$globalConfigResult[$i]['global_name']] = $globalConfigResult[$i]['global_value'];
}
$resultArr = array();
//Set selected field
if(isset($arr['mandatory_fields']) && trim($arr['mandatory_fields'])!= ''){
  $explodField = explode(",",$arr['mandatory_fields']);
  for($f=0;$f<count($explodField); $f++){
    $resultArr[] = $explodField[$f];
  }
}
// \Zend\Debug\Debug::dump($resultArr);die;
$sample = in_array("Sample Id",$resultArr)?"isRequired":"";
$patient = in_array("Patient Id",$resultArr)?"isRequired":"";
$facility = in_array("Facility Name",$resultArr)?"isRequired":"";
$hivDiagnosisDate = in_array("Hiv Diagnosis Date",$resultArr)?"isRequired":"";
$hivRecencyDate = in_array("Hiv Recency Date",$resultArr)?"isRequired":"";
$controlLineResult = in_array("Positive Verification Line",$resultArr)?"isRequired":"";
$positiveVerificationLine = in_array("Positive Verification Line",$resultArr)?"isRequired":"";
$longTermVerificationLine = in_array("Long Term Verification Line",$resultArr)?"isRequired":"";
$dob = in_array("Dob",$resultArr)?"isRequired":"";
$age = in_array("Age",$resultArr)?"isRequired":"";
$gender = in_array("Gender",$resultArr)?"isRequired":"";
$locationOne = in_array("Province",$resultArr)?"isRequired":"";
$locationTwo = in_array("District",$resultArr)?"isRequired":"";
$locationThree = in_array("City",$resultArr)?"isRequired":"";

$residence = in_array("Residence",$resultArr)?"isRequired":"";
$marital = in_array("Marital Status",$resultArr)?"isRequired":"";
$education = in_array("Education Level",$resultArr)?"isRequired":"";
$risk = in_array("Risk Population",$resultArr)?"isRequired":"";
$pregnancy = in_array("Pregnancy Status",$resultArr)?"isRequired":"";
$partner = in_array("Current Sexual Partner",$resultArr)?"isRequired":"";
$testing = in_array("Past Hiv Testing",$resultArr)?"isRequired":"";
$last = in_array("Test Last 12 Month",$resultArr)?"isRequired":"";

?>
<style>
.btnHide{display:none;}
</style>
<div class="bg-body-light">
     <div class="content content-full">
          <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
               <h1 class="flex-sm-fill font-size-h2 font-w400 mt-2 mb-0 mb-sm-2">Recency</h1>
               <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                    <ol class="breadcrumb">
                         <a href="<?php echo $this->url('recency', array('action' => 'index')); ?>"><li class="breadcrumb-item">Recency Details</li></a>
                         <li class="breadcrumb-item active" aria-current="page">&nbsp;/ Add</li>
                    </ol>
               </nav>
          </div>
     </div>
</div>


<div class="content">
     <div class="block block-rounded block-bordered">
          <div class="block-header block-header-default">
               <h3 class="block-title">Add Recency Details</h3>
          </div>

          <!--  Start Tab view-->
          <div class="row">
               <div class="col-md-12">
                    <div class="js-wizard-simple block block block-rounded block-bordered">
                         <ul class="nav nav-tabs nav-tabs-block nav-justified" role="tablist">
                              <li class="nav-item">
                                   <a class="nav-link active" href="javascript:void()" id="step1" onclick="validateStep2()">1. Recency Test</a>
                              </li>
                              <li class="nav-item">
                                   <a class="nav-link" href="javascript:void()" id="step2" onclick="validateStep1();">2. Behaviour</a>
                              </li>
                         </ul>
                         <form name="recencyInformation" id="recencyInformation"  class="mb-5" action="<?php echo $this->url('recency', array('action' => 'add')); ?>" method="post">
                              <div class="block-content block-content-sm">
                                   <!-- <div class="progress" data-wizard="progress" style="height: 8px;">
                                   <div class="progress-bar progress-bar-striped progress-bar-animated bg-primary" role="progressbar" style="width: 30%;" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100"></div>
                              </div> -->
                         </div>
                         <div class="block-content block-content-full tab-content" style="min-height: 300px;">

                              <div class="tab-pane active" id="wizard-progress-step1" role="tabpanel">

                                   <div class="form-group row">
                                        <label class="col-sm-2 col-form-label" for="">Sample Id<?php echo(in_array("Sample Id",$resultArr)?"<span class='mandatory'>*</span>":""); ?></label>
                                        <div class="col-sm-4">
                                             <input type="text" class="form-control <?php echo $sample; ?>" id="sampleId" name="sampleId" placeholder="Enter the sample id" title="Please enter the sample id">
                                        </div>

                                        <label class="col-sm-2 col-form-label" for="">Patient Id <?php echo(in_array("Patient Id",$resultArr)?"<span class='mandatory'>*</span>":""); ?></label>
                                        <div class="col-sm-4">
                                             <input type="text" class="form-control <?php echo $patient; ?>" id="patientId" name="patientId" placeholder="Enter the patient id" title="Please enter the patient id">
                                        </div>
                                   </div>
                                   <div class="form-group row">
                                        <label class="col-sm-2 col-form-label" for="">Facility Name <?php echo(in_array("Facility Name",$resultArr)?"<span class='mandatory'>*</span>":""); ?></label>
                                        <div class="col-sm-4">
                                             <select class="form-control <?php echo $facility; ?>" id="facilityId" name="facilityId" title="Please select the facility name">
                                                  <option value="">--Select--</option>
                                                  <?php foreach($facilityResult['facility'] as $facility){ ?>
                                                       <option value="<?php echo base64_encode($facility['facility_id']); ?>"><?php echo $facility['facility_name']; ?></option>
                                                  <?php } ?>
                                             </select>
                                        </div>

                                        <label class="col-sm-2 col-form-label" for="">HIV Diagnosis Date <?php echo(in_array("Hiv Diagnosis Date",$resultArr)?"<span class='mandatory'>*</span>":""); ?></label>
                                        <div class="col-sm-4">
                                             <input type="text" class="js-datepicker form-control <?php echo $hivDiagnosisDate; ?>" id="hivDiagnosisDate" name="hivDiagnosisDate" data-week-start="1" data-autoclose="true" data-today-highlight="true" data-date-format="dd-M-yyyy" value="" placeholder="Enter the HIV diagnosis date" title="Please enter the HIV diagnosis date"  readonly="readonly">
                                        </div>
                                   </div>

                                   <div class="form-group row">
                                        <label class="col-sm-2 col-form-label" for="">HIV Recency Date<?php echo(in_array("Hiv Recency Date",$resultArr)?"<span class='mandatory'>*</span>":""); ?></label>
                                        <div class="col-sm-4">
                                             <input type="text" class="js-datepicker form-control <?php echo $hivRecencyDate; ?>" id="hivRecencyDate" name="hivRecencyDate" data-week-start="1" data-autoclose="true" data-today-highlight="true" data-date-format="dd-M-yyyy" value="" placeholder="Enter the HIV recency date" title="Please enter the HIV recency date"  readonly="readonly">
                                        </div>

                                        <label class="col-sm-2 col-form-label" for="">Control Line
                                             <?php echo(in_array("Control Line",$resultArr)?"<span class='mandatory'>*</span>":""); ?></label>
                                        <div class="col-sm-4">
                                             <select class="form-control
                                                  <?php echo $controlLineResult; ?>" id="controlLine" name="controlLine" title="Please select the control line">
                                                  <option value="">--Select--</option>
                                                  <option value="present">Present(Positive/P)</option>
                                                  <option value="absent">Absent(Negative/N)</option>
                                                  <option value="invalid">Invalid</option>
                                                  <option value="no_result">Result Not Available</option>
                                             </select>
                                        </div>
                                   </div>

                                   <div class="form-group row">
                                        <label class="col-sm-2 col-form-label" for="">Positive Verification
                                             <?php echo(in_array("Positive Verification Line",$resultArr)?"<span class='mandatory'>*</span>":""); ?></label>
                                        <div class="col-sm-4">
                                             <select class="form-control
                                                  <?php echo $positiveVerificationLine; ?>" id="positiveVerificationLine" name="positiveVerificationLine" title="Please select the positive verification line">
                                                  <option value="">--Select--</option>
                                                  <option value="present">Present(Positive/P)</option>
                                                  <option value="absent">Absent(Negative/N)</option>
                                                  <option value="invalid">Invalid</option>
                                                  <option value="no_result">Result Not Available</option>
                                             </select>
                                        </div>

                                        <label class="col-sm-2 col-form-label" for="">Long Term Verification
                                             <?php  echo(in_array("Long Term Verification Line",$resultArr)?"<span class='mandatory'>*</span>":""); ?></label>
                                        <div class="col-sm-4">
                                             <select class="form-control <?php echo $longTermVerificationLine; ?>" id="longTermVerificationLine" name="longTermVerificationLine" title="Please select the long term verification line">
                                                  <option value="">--Select--</option>
                                                  <option value="present">Present(Positive/P)</option>
                                                  <option value="absent">Absent(Negative/N)</option>
                                                  <option value="invalid">Invalid</option>
                                                  <option value="no_result">Result Not Available</option>
                                             </select>
                                        </div>
                                   </div>
                                        <!-- end work test -->
                                   <div class="form-group row">
                                        <label class="col-sm-2 col-form-label" for="">DOB <?php echo(in_array("Dob",$resultArr)?"<span class='mandatory'>*</span>":""); ?></label>
                                        <div class="col-sm-4">
                                             <input type="text" class="js-datepicker form-control <?php echo $dob; ?>" id="dob" name="dob" data-week-start="1" data-autoclose="true" data-today-highlight="true" data-date-format="dd-M-yyyy" value="" placeholder="Enter the dob" title="Please enter the dob" onchange="ageCalculate();"  readonly="readonly">
                                        </div>

                                        <label class="col-sm-2 col-form-label" for="">Age <?php echo(in_array("Age",$resultArr)?"<span class='mandatory'>*</span>":""); ?></label>
                                        <div class="col-sm-4">
                                             <input type="text" class="form-control <?php echo $age; ?>" id="age" name="age" value="" placeholder="Enter the age" title="Please enter the age">
                                        </div>
                                   </div>
                                   <div class="form-group row">
                                        <label class="col-sm-2 col-form-label" for="">Gender <?php echo(in_array("Gender",$resultArr)?"<span class='mandatory'>*</span>":""); ?></label>
                                        <div class="col-sm-4">
                                             <select class="form-control <?php echo $gender; ?>" id="gender" name="gender" title="Please select the gender">
                                                  <option value="">--Select--</option>
                                                  <option value="male">Male</option>
                                                  <option value="female">Female</option>
                                                  <option value="transgender">Transgender</option>
                                             </select>
                                        </div>

                                        <label style=" margin-bottom: 4%; " class="col-sm-2 col-form-label" for=""><?php echo ucfirst($globalConfigResult[0]['global_value']); ?><?php echo(in_array("Province",$resultArr)?"<span class='mandatory'>*</span>":""); ?></label>
                                        <div class="col-sm-4">
                                            <select class="form-control <?php echo $locationOne; ?>" id="<?php echo $globalConfigResult[0]['global_name']; ?>" name="<?php echo $globalConfigResult[0]['global_name']; ?>" placeholder="Enter the <?php echo lcfirst($globalConfigResult[0]['global_value']); ?>" title="Please enter the <?php echo lcfirst($globalConfigResult[0]['global_value']); ?>" onchange="getLocationDeatils('<?php echo $globalConfigResult[0]['global_name'];?>');">
                                                <option value="">-- Select --</option>
                                            </select>
                                        </div>

                                        <label style=" margin-bottom: 4%; " class="col-sm-2 col-form-label" for=""><?php echo ucfirst($globalConfigResult[1]['global_value']); ?><?php echo(in_array("District",$resultArr)?"<span class='mandatory'>*</span>":""); ?></label>
                                        <div class="col-sm-4">
                                            <select class="form-control <?php echo $locationTwo; ?>" id="<?php echo $globalConfigResult[1]['global_name']; ?>" name="<?php echo $globalConfigResult[1]['global_name']; ?>" placeholder="Enter the <?php echo lcfirst($globalConfigResult[1]['global_value']); ?>" title="Please enter the <?php echo lcfirst($globalConfigResult[1]['global_value']); ?>" onchange="getLocationDeatils('<?php echo $globalConfigResult[1]['global_name'];?>');">
                                                <option value="">-- Select --</option>
                                            </select>
                                        </div>

                                        <label style=" margin-bottom: 4%; " class="col-sm-2 col-form-label" for=""><?php echo ucfirst($globalConfigResult[2]['global_value']); ?><?php echo(in_array("City",$resultArr)?"<span class='mandatory'>*</span>":""); ?></label>
                                        <div class="col-sm-4">
                                            <select class="form-control <?php echo $locationThree; ?>" id="<?php echo $globalConfigResult[2]['global_name']; ?>" name="<?php echo $globalConfigResult[2]['global_name']; ?>" placeholder="Enter the <?php echo lcfirst($globalConfigResult[2]['global_value']); ?>" title="Please enter the <?php echo lcfirst($globalConfigResult[2]['global_value']); ?>" onchange="getLocationDeatils('<?php echo $globalConfigResult[2]['global_name'];?>');">
                                                <option value="">-- Select --</option>
                                            </select>
                                        </div>

                                   </div>

                              </div>

                              <div class="tab-pane" id="wizard-progress-step2" role="tabpanel">
                                   <div class="form-group row">
                                        <label class="col-sm-2 col-form-label" for="">Residence <?php echo(in_array("Residence",$resultArr)?"<span class='mandatory'>*</span>":""); ?></label>
                                        <div class="col-sm-4">
                                             <select class="form-control" id="residence" name="residence" title="Please select the residence">
                                                  <option value="">--Select--</option>
                                                  <option value="urban">Urban</option>
                                                  <option value="rural">Rural</option>
                                             </select>
                                        </div>

                                        <label class="col-sm-2 col-form-label" for="">Marital Status <?php echo(in_array("Marital Status",$resultArr)?"<span class='mandatory'>*</span>":""); ?></label>
                                        <div class="col-sm-4">
                                             <select class="form-control" id="maritalStatus" name="maritalStatus" title="Please select the marital status">
                                                  <option value="">--Select--</option>
                                                  <option value="never_married">Never Married</option>
                                                  <option value="married_cohabited">Married - Cohabited</option>
                                                  <option value="married_cohabiting">Married Cohabiting</option>
                                                  <option value="widow">Widow</option>
                                                  <option value="divorce_separated">Divorce - Separated</option>
                                             </select>
                                        </div>
                                   </div>

                                   <div class="form-group row">
                                        <label class="col-sm-2 col-form-label" for="">Education Level <?php echo(in_array("Education Level",$resultArr)?"<span class='mandatory'>*</span>":""); ?></label>
                                        <div class="col-sm-4">
                                             <select class="form-control" id="educationLevel" name="educationLevel" title="Please select the education level">
                                                  <option value="">--Select--</option>
                                                  <option value="primary">Primary</option>
                                                  <option value="university_or_higher">University or Higher</option>
                                             </select>
                                        </div>
                                        <label class="col-sm-2 col-form-label" for="">Risk Population <?php echo(in_array("Risk Population",$resultArr)?"<span class='mandatory'>*</span>":""); ?></label>
                                        <div class="col-sm-4">
                                             <select class="form-control" id="riskPopulation" name="riskPopulation" title="Please select the risk population">
                                                  <option value="">--Select--</option>
                                                  <?php foreach($facilityResult['riskPopulations'] as $riskPo){?>
                                                       <option value="<?php echo base64_encode($riskPo['rp_id']); ?>"><?php echo str_replace('_', ' ', $riskPo['name']); ?></option>
                                                  <?php } ?>
                                             </select>
                                        </div>
                                   </div>

                                   <div class="form-group row">
                                        <label class="col-sm-2 col-form-label" for="">Pregnancy Status<?php echo(in_array("Pregnancy Status",$resultArr)?"<span class='mandatory'>*</span>":""); ?></label>
                                        <div class="col-sm-4">
                                             <select class="form-control" id="pregnancyStatus" name="pregnancyStatus" title="Please select the pregnancy status">
                                                  <option value="">--Select--</option>
                                                  <option value="currently_pregnant">Currently Pregnant</option>
                                                  <option value="not_pregnant">Not Pregnant</option>
                                                  <option value="not_known">Not Known</option>
                                             </select>
                                        </div>

                                        <label class="col-sm-2 col-form-label" for="">Current Sexual Partner <?php echo(in_array("Current Sexual Partner",$resultArr)?"<span class='mandatory'>*</span>":""); ?></label>
                                        <div class="col-sm-4">
                                             <select class="form-control" id="currentSexualPartner" name="currentSexualPartner" title="Please select the current sexual partner">
                                                  <option value="">--Select--</option>
                                                  <option value="1">1</option>
                                                  <option value="2_3">2 - 3</option>
                                                  <option value=">3">>3</option>
                                             </select>
                                        </div>
                                   </div>

                                   <div class="form-group row">
                                        <label class="col-sm-2 col-form-label" for="">Past HIV Testing <?php echo(in_array("Past Hiv Testing",$resultArr)?"<span class='mandatory'>*</span>":""); ?></label>
                                        <div class="col-sm-4">
                                             <select class="form-control" id="pastHivTesting" name="pastHivTesting" title="Please enter the past HIV testing">
                                                  <option value="">--Select--</option>
                                                  <option value="yes">Yes</option>
                                                  <option value="no">No</option>
                                                  <option value="not_known">Not Known</option>
                                             </select>
                                        </div>
                                        <label class="col-sm-2 col-form-label" for="">Test Last 12 Month <?php echo(in_array("Test Last 12 Month",$resultArr)?"<span class='mandatory'>*</span>":""); ?></label>
                                        <div class="col-sm-4">
                                             <select class="form-control" id="testLast12Month" name="testLast12Month" title="Please enter the test last 12 month">
                                                  <option value="">--Select--</option>
                                                  <option value="yes">Yes</option>
                                                  <option value="no">No</option>
                                                  <option value="not_known">Not Known</option>
                                             </select>
                                        </div>
                                   </div>
                              </div>
                         </div>
                         <!-- END Steps Content -->
                         <div class="block-content block-content-sm block-content-full bg-body-light rounded-bottom">
                              <div class="row">
                                   <div class="col-6">
                                        <button type="button" class="btn btn-secondary btnHide" onclick="validateStep2()">
                                             <i class="fa fa-angle-left mr-1"></i> Previous
                                        </button>
                                        <a   href="<?php echo $this->url('recency', array('action' => 'index')); ?>" class="btn btn-danger d-none btnHide" data-wizard="finish" >Cancel</a>&nbsp;
                                        <button  type="submit" class="btn btn-primary d-none btnHide" data-wizard="finish" onclick="validateNow();return false;"><i class="fa fa-check mr-1"></i> Submit</button>
                                   </div>
                                   <div class="col-6 text-right">
                                        <!-- <button type="button" class="btn btn-secondary" data-wizard="next"> -->
                                        <button type="button" class="btn btn-secondary nxtBtn" onclick="validateStep1()">
                                             Next <i class="fa fa-angle-right ml-1"></i>
                                        </button>
                                   </div>
                              </div>
                         </div>
                    </form>
               </div>
          </div>
     </div>
     <!--  end tab view-->
</div>
</div>


<script type="text/javascript">

     jQuery(document).ready(function($) {

          $("#positiveVerificationLine").change(function() {
               if($(this).val() == 'absent'){

                    var text = $(this).find('option:selected').text();
                    $('#longTermVerificationLine').val('');

                    $("#longTermVerificationLine").attr("disabled",true);
                    $("#longTermVerificationLine").removeClass("isRequired");
               }else{
                    $("#longTermVerificationLine").attr("disabled",false);
                    $("#longTermVerificationLine").addClass("isRequired");

               }
          });

          <?php
          foreach($globalConfigResult as $config){
               ?>
               getLocationDeatils('<?php echo $config["global_name"];?>');
               <?php
               break;
          }
          ?>

     });

function validateStep1()
{
    if( ( $("#sampleId").val() != "" ) || ( $("#patientId").val() != "" ) ){
        flag = deforayValidator.init({
                    formId: 'recencyInformation'
        });
        if (flag) {
            $("#residence").addClass("<?php echo $residence;?>");
            $("#maritalStatus").addClass("<?php echo $marital;?>");
            $("#educationLevel").addClass("<?php echo $education;?>");
            $("#riskPopulation").addClass("<?php echo $risk;?>");
            $("#pregnancyStatus").addClass("<?php echo $pregnancy;?>");
            $("#currentSexualPartner").addClass("<?php echo $partner;?>");
            $("#pastHivTesting").addClass("<?php echo $testing;?>");
            $("#testLast12Month").addClass("<?php echo $last;?>");

            $("#step1,#wizard-progress-step1").removeClass("active");
            $("#step2,#wizard-progress-step2").addClass("active");

            $(".btnHide").show();
            $(".nxtBtn").hide();
        }
    }else{
            $(".btnHide").hide();
            $("#sampleId").focus();
            $("#sampleId").css("border","1px solid rgb(207, 51, 57)");
            alert("Please enter either sample or patient id  ",'err');
    }
}
function validateStep2()
{
    $("#residence").removeClass('isRequired');
    $("#maritalStatus").removeClass('isRequired');
    $("#educationLevel").removeClass('isRequired');
    $("#riskPopulation").removeClass('isRequired');
    $("#pregnancyStatus").removeClass('isRequired');
    $("#currentSexualPartner").removeClass('isRequired');
    $("#pastHivTesting").removeClass('isRequired');
    $("#testLast12Month").removeClass('isRequired');

    $("#step1,#wizard-progress-step1").addClass("active");
    $("#step2,#wizard-progress-step2").removeClass("active");
    $(".btnHide").hide();
    $(".nxtBtn").show();
}
     function validateNow() {
          if( ( $("#sampleId").val() != "" ) || ( $("#patientId").val() != "" ) ){
               flag = deforayValidator.init({
                    formId: 'recencyInformation'
               });
               if (flag) {
                    $.blockUI();
                    document.getElementById('recencyInformation').submit();
               }
          }else{
               $("#sampleId").focus();
               $("#sampleId").css("border","1px solid rgb(207, 51, 57)");
               alert("Please enter either sample or patient id  ",'err');
          }
     }


     function ageCalculate(){
          var today = new Date();
          var birthDate = new Date($("#dob").val());
          var dob = diff_years(today,birthDate);
          $("#age").val(dob);
     }
     function diff_years(dt2, dt1)
     {
          var diff =(dt2.getTime() - dt1.getTime()) / 1000;
          diff /= (60 * 60 * 24);
          return Math.abs(Math.round(diff/365.25));
     }
     function getLocationDeatils(globalName)
     {
          var selectValue = document.getElementById(globalName).value;
          var innerId = '';
          var path = '';
          if(globalName=='location_one' && selectValue==''){
               path = 'get-province';
               innerId = 'location_one';
          }else if(globalName=='location_one' && selectValue!=''){
               path = 'get-district';
               innerId = 'location_two';
               $("#location_three").html("<option value=''>-- Select --</option>");
          }else if(globalName=='location_two' && selectValue!=''){
               path = 'get-city';
               innerId = 'location_three';
          }
          if(path!=''){
               $.blockUI();
               $.post("/common/"+path, {selectValue:selectValue},
               function(data) {
                    $("#"+innerId).html(data);
                    $.unblockUI();
               });
          }
     }
</script>
