<?php
// \Zend\Debug\Debug::dump($result);die;
// \Zend\Debug\Debug::dump($facilityResult['riskPopulations']);die;
use Zend\Session\Container;
use Application\Service\CommonService;
$sessionLogin = new Container('credo');
$common = new CommonService();
$dob = '';
$file_open_date = '';
if($result->hiv_diagnosis_date!= '' && $result->hiv_diagnosis_date!= null && $result->hiv_diagnosis_date!= '0000-00-00'){
    $hivDiagnosisDate = $common->humanDateFormat($result->hiv_diagnosis_date);
}
if($result->hiv_recency_date!= '' && $result->hiv_recency_date!= null && $result->hiv_recency_date!= '0000-00-00'){
    $hivRecencyDate = $common->humanDateFormat($result->hiv_recency_date);
}
if($result->dob!= '' && $result->dob!= null && $result->dob!= '0000-00-00'){
    $dob = $common->humanDateFormat($result->dob);
}
?>
<div class="bg-body-light">
     <div class="content content-full">
          <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
               <h1 class="flex-sm-fill font-size-h2 font-w400 mt-2 mb-0 mb-sm-2">Recency</h1>
               <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                    <ol class="breadcrumb">
                         <a href="<?php echo $this->url('recency', array('action' => 'index')); ?>"><li class="breadcrumb-item">Recency Details</li></a>
                         <li class="breadcrumb-item active" aria-current="page">&nbsp;/ Edit</li>
                    </ol>
               </nav>
          </div>
     </div>
</div>


<div class="content">
    <div class="block block-rounded block-bordered">
        <div class="block-header block-header-default">
            <h3 class="block-title">Edit Recency Details</h3>
        </div>
        <div class="block-content">
            <div class="col-md-12 table-responsive" id="hide">
                <form name="recencyInformation" id="recencyInformation"  class="mb-5" action="<?php echo $this->url('recency', array('action' => 'edit')); ?>" method="post">
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" for="">Sample Id</label>
                        <div class="col-sm-4">
                            <input type="text" value="<?php echo $result['sample_id']; ?>" class="form-control" id="sampleId" name="sampleId" placeholder="Enter the sample id" title="Please enter the sample id">
                        </div>

                        <label class="col-sm-2 col-form-label" for="">Patient Id</label>
                        <div class="col-sm-4">
                            <input type="text" value="<?php echo $result['patient_id']; ?>" class="form-control" id="patientId" name="patientId" placeholder="Enter the patient id" title="Please enter the patient id">
                        </div>
                    </div>

                    <div class="form-group row">
                    <label class="col-sm-2 col-form-label" for="">Facility Name<span class="mandatory">*</span></label>
                        <div class="col-sm-4">
                            <select class="form-control isRequired" id="facilityId" name="facilityId" title="Please select the facility name">
                                <option value="">--Select--</option>
                                <?php foreach($facilityResult['facility'] as $facility){?>
                                    <option value="<?php echo base64_encode($facility['facility_id']); ?>" <?php echo($result['facility_id'] == $facility['facility_id'] )?'selected="selected"':''; ?>><?php echo $facility['facility_name']; ?></option>
                                <?php } ?>
                            </select>
                        </div>

                        <label class="col-sm-2 col-form-label" for="">HIV Diagnosis Date<span class="mandatory">*</span></label>
                        <div class="col-sm-4">
                            <input type="text" value="<?php echo $hivDiagnosisDate; ?>" class="js-datepicker form-control isRequired" id="hivDiagnosisDate" name="hivDiagnosisDate" data-week-start="1" data-autoclose="true" data-today-highlight="true" data-date-format="dd-M-yyyy" value="" placeholder="Enter the HIV diagnosis date" title="Please enter the HIV diagnosis date"  readonly="readonly">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" for="">HIV Recency Date<span class="mandatory">*</span></label>
                        <div class="col-sm-4">
                            <input type="text" value="<?php echo $hivRecencyDate; ?>" class="js-datepicker form-control isRequired" id="hivRecencyDate" name="hivRecencyDate" data-week-start="1" data-autoclose="true" data-today-highlight="true" data-date-format="dd-M-yyyy" value="" placeholder="Enter the HIV recency date" title="Please enter the HIV recency date"  readonly="readonly">
                        </div>

                        <label class="col-sm-2 col-form-label" for="">HIV Recency Result<span class="mandatory">*</span></label>
                        <div class="col-sm-4">
                            <input type="text" value="<?php echo $result['hiv_recency_result']; ?>" class="form-control isRequired" id="hivRecencyResult" name="hivRecencyResult" placeholder="Enter the HIV recency result" title="Please enter the HIV recency result">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" for="">DOB</label>
                        <div class="col-sm-4">
                            <input type="text" value="<?php echo $dob;?>" class="js-datepicker form-control" id="dob" name="dob" data-week-start="1" data-autoclose="true" data-today-highlight="true" data-date-format="dd-M-yyyy" value="" placeholder="Enter the dob" title="Please enter the dob" onchange="ageCalculate();"  readonly="readonly">
                        </div>

                        <label class="col-sm-2 col-form-label" for="">Age</label>
                        <div class="col-sm-4">
                            <input type="text" value="<?php echo $result['age'];?>" class="form-control" id="age" name="age" value="" placeholder="Enter the age" title="Please enter the age">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" for="">Gender</label>
                        <div class="col-sm-4">
                            <select class="form-control" id="gender" name="gender" title="Please select the gender">
                                <option value="">--Select--</option>
                                <option value="male" <?php echo($result['gender'] == 'male' )?'selected="selected"':''; ?>>Male</option>
                                <option value="female" <?php echo($result['gender'] == 'female' )?'selected="selected"':''; ?>>Female</option>
                                <option value="transgender" <?php echo($result['gender'] == 'transgender' )?'selected="selected"':''; ?>>Transgender</option>
                            </select>
                        </div>
                        <label class="col-sm-2 col-form-label" for="">Marital Status</label>
                        <div class="col-sm-4">
                            <select class="form-control" id="maritalStatus" name="maritalStatus" title="Please select the marital status">
                                <option value="">--Select--</option>
                                <option value="never_married" <?php echo($result['marital_status'] == 'never_married' )?'selected="selected"':''; ?>>Never Married</option>
                                <option value="married_cohabited" <?php echo($result['marital_status'] == 'married_cohabited' )?'selected="selected"':''; ?>>Married - Cohabited</option>
                                <option value="married_cohabiting" <?php echo($result['marital_status'] == 'married_cohabiting' )?'selected="selected"':''; ?>>Married cohabiting</option>
                                <option value="widow" <?php echo($result['marital_status'] == 'widow' )?'selected="selected"':''; ?>>Widow</option>
                                <option value="divorce_separated" <?php echo($result['marital_status'] == 'divorce_separated' )?'selected="selected"':''; ?>>Divorce - Separated</option>
                            </select>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" for="">Residence</label>
                        <div class="col-sm-4">
                            <select class="form-control" id="residence" name="residence" title="Please select the residence">
                            <option value="">--Select--</option>
                            <option value="urban" <?php echo($result['residence'] == 'urban' )?'selected="selected"':''; ?>>Urban</option>
                            <option value="rural" <?php echo($result['residence'] == 'rural' )?'selected="selected"':''; ?>>Rural</option>
                            </select>
                        </div>
                        <label class="col-sm-2 col-form-label" for="">Education Level</label>
                        <div class="col-sm-4">
                            <select class="form-control" id="educationLevel" name="educationLevel" title="Please select the education level">
                            <option value="">--Select--</option>
                            <option value="primary" <?php echo($result['education_level'] == 'primary' )?'selected="selected"':''; ?>>Primary</option>
                            <option value="university_or_higher" <?php echo($result['education_level'] == 'university_or_higher' )?'selected="selected"':''; ?>>University or Higher</option>
                            </select>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" for="">Risk Population</label>
                        <div class="col-sm-4">
                            <select class="form-control" id="riskPopulation" name="riskPopulation" title="Please select the risk population">
                                <option value="">--Select--</option>
                                <?php foreach($facilityResult['riskPopulations'] as $riskPo){?>
                                    <option value="<?php echo base64_encode($riskPo['rp_id']); ?>" <?php echo($result['risk_population'] == $riskPo['rp_id'] )?'selected="selected"':''; ?>><?php echo str_replace('_', ' ', $riskPo['name']); ?></option>
                                <?php } ?>
                            </select>
                        </div>
                        <label class="col-sm-2 col-form-label" for="">Pregnancy Status</label>
                        <div class="col-sm-4">
                            <select class="form-control" id="pregnancyStatus" name="pregnancyStatus" title="Please select the pregnancy status">
                            <option value="">--Select--</option>
                            <option value="currently_pregnant" <?php echo($result['pregnancy_status'] == 'currently_pregnant' )?'selected="selected"':''; ?>>Currently Pregnant</option>
                            <option value="not_pregnant" <?php echo($result['pregnancy_status'] == 'not_pregnant' )?'selected="selected"':''; ?>>Not Pregnant</option>
                            <option value="not_known" <?php echo($result['pregnancy_status'] == 'not_known' )?'selected="selected"':''; ?>>Not Known</option>
                            </select>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" for="">Current Sexual Partner</label>
                        <div class="col-sm-4">
                            <select class="form-control" id="currentSexualPartner" name="currentSexualPartner" title="Please select the current sexual partner">
                            <option value="">--Select--</option>
                            <option value="1" <?php echo($result['current_sexual_partner'] == '1' )?'selected="selected"':''; ?>>1</option>
                            <option value="2_3" <?php echo($result['current_sexual_partner'] == '2_3' )?'selected="selected"':''; ?>>2 - 3</option>
                            <option value=">3" <?php echo($result['current_sexual_partner'] == '>3' )?'selected="selected"':''; ?>>>3</option>
                            </select>
                        </div>
                        <label class="col-sm-2 col-form-label" for="">Past HIV Testing</label>
                        <div class="col-sm-4">
                            <select class="form-control" id="pastHivTesting" name="pastHivTesting" title="Please enter the past HIV testing">
                                <option value="">--Select--</option>
                                <option value="yes" <?php echo($result['past_hiv_testing'] == 'yes' )?'selected="selected"':''; ?>>Yes</option>
                                <option value="no" <?php echo($result['past_hiv_testing'] == 'no' )?'selected="selected"':''; ?>>No</option>
                                <option value="not_known" <?php echo($result['past_hiv_testing'] == 'not_known' )?'selected="selected"':''; ?>>Not Known</option>
                            </select>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" for="">Test Last 12 Month</label>
                        <div class="col-sm-4">
                            <select class="form-control" id="testLast12Month" name="testLast12Month" title="Please enter the test last 12 month">
                                <option value="">--Select--</option>
                                <option value="yes" <?php echo($result['test_last_12_month'] == 'yes' )?'selected="selected"':''; ?>>Yes</option>
                                <option value="no" <?php echo($result['test_last_12_month'] == 'no' )?'selected="selected"':''; ?>>No</option>
                                <option value="not_known" <?php echo($result['test_last_12_month'] == 'not_known' )?'selected="selected"':''; ?>>Not Known</option>
                            </select>
                        </div>
                        <?php
                        $i=0;
                        $keyVal = 'one';
                        foreach($globalConfigResult as $key=>$config){ ?>
                                <label style=" margin-bottom: 4%; " class="col-sm-2 col-form-label" for=""><?php echo ucfirst($config['global_value']); ?></label>
                                <div class="col-sm-4">
                                    <input type="text" value="<?php echo $result['location_'.$keyVal];?>" class="form-control" id="configValue" name="configValue[]" placeholder="Enter the <?php echo lcfirst($config['global_value']); ?>" title="Please enter the location <?php echo lcfirst($config['global_value']); ?>">
                                </div>
                        <?php
                        $i++;
                            if($i == 2){
                                $keyVal = 'two';
                            }else if($i > 2){
                                $keyVal = 'three';
                            }
                        } ?>
                    </div>

                    <div class="row items-push">
                        <div class="col-lg-7 offset-lg-4">
                            <input type="hidden" name="recencyId" value="<?php echo $result['recency_id'];?>" />
                            <a href="<?php echo $this->url('recency', array('action' => 'index')); ?>" class="btn btn-danger">Cancel</a>&nbsp;
                            <button type="submit" class="btn btn-primary" onclick="validateNow();return false;"><i class="fa fa-fw fa-check"></i> Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


<script type="text/javascript">
function validateNow() {
    if( ( $("#sampleId").val() != "" ) || ( $("#patientId").val() != "" ) ){
        flag = deforayValidator.init({
            formId: 'recencyInformation'
        });
        if (flag) {
            $.blockUI();
            document.getElementById('recencyInformation').submit();
        }
    }else{
        $("#sampleId").focus();
        $("#sampleId").css("border","1px solid rgb(207, 51, 57)");
        alert("Please enter eaither sample or patient id  ",'err');
    }
}
$(document).ready(function(){
    
});
function ageCalculate(){
    var today = new Date();
    var birthDate = new Date($("#dob").val());
    var dob = diff_years(today,birthDate);
    $("#age").val(dob);
}
function diff_years(dt2, dt1) 
{
    var diff =(dt2.getTime() - dt1.getTime()) / 1000;
    diff /= (60 * 60 * 24);
    return Math.abs(Math.round(diff/365.25));
}

</script>
