<?php
use Application\Service\CommonService;

$common = new CommonService();
// Extend the TCPDF class to create custom Header and Footer
class MYPDF extends TCPDF {

    //Page header
    public function setHeading($firstText,$title,$labName,$secondText) {
        $this->firstText = $firstText;
        $this->labName = $labName;
        $this->title = $title;
        $this->secondText = $secondText;
      }

    public function Header() {
        // Logo
        //$image_file = K_PATH_IMAGES.'logo_example.jpg';
        //$this->Image($image_file, 10, 10, 15, '', 'JPG', '', 'T', false, 300, '', false, false, 0, false, false, false);
        // Set font
        //$this->SetFont('helvetica', 'B', 20);
        // Title
        $this->SetFont('helvetica', 'B', 10);
        $this->writeHTMLCell(0,0,10,8,strtoupper($this->firstText), 0, 0, 0, true, 'C', true);
        $this->SetFont('helvetica', 'B', 8);
        $this->writeHTMLCell(0,0,10,14,strtoupper($this->title), 0, 0, 0, true, 'C', true);
        $this->SetFont('helvetica', 'B', 7);
        $this->writeHTMLCell(0,0,10,20,strtoupper($this->labName), 0, 0, 0, true, 'C', true);
        $this->SetFont('helvetica', 'B', 10);
        $this->writeHTMLCell(0,0,10,26,strtoupper($this->secondText), 0, 0, 0, true, 'C', true);
    }
}

// create new PDF document
$pdf = new MYPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
$pdf->setHeading('MINISTERE DE LA SANTE','MINISTRY OF HEALTH',$result['testFacilityName'],'RESULTATS TESTE RECENCY');
// set document information
$pdf->SetCreator('HIV Recency Testing');
$pdf->SetTitle('HIV Recency Testing');
//$pdf->SetSubject('TCPDF Tutorial');
//$pdf->SetKeywords('TCPDF, PDF, example, test, guide');

// set default header data
$pdf->SetHeaderData(PDF_HEADER_LOGO, PDF_HEADER_LOGO_WIDTH, PDF_HEADER_TITLE, PDF_HEADER_STRING);

// set header and footer fonts
$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

// set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

// set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

// set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

// set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

// set some language-dependent strings (optional)
//if (@file_exists(dirname(__FILE__).'/lang/eng.php')) {
//    require_once(dirname(__FILE__).'/lang/eng.php');
//    $pdf->setLanguageArray($l);
//}

// ---------------------------------------------------------

// set font
$pdf->SetFont('helvetica', '', 10);
$pdf->AddPage();

$html = '<br/><br/>';
$html.='<table style="padding:0px 2px 2px 2px;">';

$html .='<tr>';
$html .='<td colspan="3" style="line-height:7px;"></td>';
$html .='</tr>';
$html .='<tr>';
$html .='<td colspan="3" style="line-height:2px;border-bottom:2px solid #d3d3d3;"></td>';
$html .='</tr>';
$html .='<tr>';
$html .='<td colspan="3" style="line-height:7px;"></td>';
$html .='</tr>';
     
$html .='<tr>';
$html .='<td style="line-height:11px;font-size:11px;font-weight:bold;text-align:left;">SAMPLE ID</td>';
$html .='<td colspan="2" style="line-height:11px;font-size:11px;font-weight:bold;text-align:left;">SAMPLE COLLECTION DATE</td>';
$html .='</tr>';
$html .='<tr>';
$html .='<td style="line-height:11px;font-size:11px;text-align:left;">'.$result['sample_id'].'</td>';
$html .='<td style="line-height:11px;font-size:11px;text-align:left;">'.$common->humanDateFormat($result['sample_collection_date']).'</td>';
$html .='</tr>';
$html .='<tr>';
$html .='<td colspan="3" style="line-height:10px;"></td>';
$html .='</tr>';

$html .='<tr>';
$html .='<td style="line-height:11px;font-size:11px;font-weight:bold;text-align:left;">PATIENT ID</td>';
$html .='<td style="line-height:11px;font-size:11px;font-weight:bold;text-align:left;">AGE</td>';
$html .='<td style="line-height:11px;font-size:11px;font-weight:bold;text-align:left;">GENDER</td>';
$html .='</tr>';
$html .='<tr>';
$html .='<td style="line-height:11px;font-size:11px;text-align:left;">'.$result['patient_id'].'</td>';
$html .='<td style="line-height:11px;font-size:11px;text-align:left;">'.$result['age'].'</td>';
$html .='<td style="line-height:11px;font-size:11px;text-align:left;">'.$result['gender'].'</td>';
$html .='</tr>';
$html .='<tr>';
$html .='<td colspan="3" style="line-height:10px;"></td>';
$html .='</tr>';

$html .='<tr>';
$html .='<td style="line-height:11px;font-size:11px;font-weight:bold;text-align:left;">HEALTH CENTER NAME</td>';
$html .='<td style="line-height:11px;font-size:11px;font-weight:bold;text-align:left;">District</td>';
$html .='<td style="line-height:11px;font-size:11px;font-weight:bold;text-align:left;">Province</td>';
$html .='</tr>';
$html .='<tr>';
$html .='<td style="line-height:11px;font-size:11px;text-align:left;">'.$result['facility_name'].'</td>';
$html .='<td style="line-height:11px;font-size:11px;text-align:left;">'.$result['district_name'].'</td>';
$html .='<td style="line-height:11px;font-size:11px;text-align:left;">'.$result['province_name'].'</td>';
$html .='</tr>';
$html .='<tr>';
$html .='<td colspan="3" style="line-height:10px;"></td>';
$html .='</tr>';

// $html .='<tr>';
// $html .='<td colspan="3" style="line-height:11px;font-size:11px;font-weight:bold;text-align:left;">CLINICAN NAME</td>';
// $html .='</tr>';
// $html .='<tr>';
// $html .='<td style="line-height:11px;font-size:11px;text-align:left;"></td>';
// $html .='</tr>';
// $html .='<tr>';
// $html .='<td colspan="3" style="line-height:10px;"></td>';
// $html .='</tr>';
     
$html .='<tr>';
$html .='<td colspan="3" style="line-height:2px;border-bottom:2px solid #d3d3d3;"></td>';
$html .='</tr>';

$html .='<tr>';
$html .='<td colspan="3" style="line-height:10px;"></td>';
$html .='</tr>';
$html .='<tr>';
$html .='<td style="line-height:11px;font-size:11px;font-weight:bold;text-align:left;">SAMPLE RECEIPT DATE</td>';
$html .='<td colspan="2" style="line-height:11px;font-size:11px;font-weight:bold;text-align:left;">SAMPLE TEST DATE</td>';
$html .='</tr>';
$html .='<tr>';
$html .='<td style="line-height:11px;font-size:11px;text-align:left;">'.$common->humanDateFormat($result['sample_receipt_date']).'</td>';
$html .='<td style="line-height:11px;font-size:11px;text-align:left;">'.$common->humanDateFormat($result['hiv_recency_test_date']).'</td>';
$html .='</tr>';
$html .='<tr>';
$html .='<td colspan="3" style="line-height:10px;"></td>';
$html .='</tr>';


$sampleTypes = array('whole_blood' => 'Whole Blood', 'plasma' => 'Plasma');
$receivedSpecimenType = '';
if(isset($result['received_specimen_type'])){
    $receivedSpecimenType = $sampleTypes[$result['received_specimen_type']];
}



$html .='<tr>';
$html .='<td style="line-height:11px;font-size:11px;font-weight:bold;text-align:left;">SPECIMEN TYPE</td>';
$html .='<td style="line-height:11px;font-size:11px;font-weight:bold;text-align:left;">ASSAY NAME</td>';
// $html .='<td colspan="2" style="line-height:11px;font-size:11px;font-weight:bold;text-align:left;">VL PLATFORM(if VL performed)</td>';
$html .='</tr>';
$html .='<tr>';
$html .='<td style="line-height:11px;font-size:11px;text-align:left;">'.$receivedSpecimenType.'</td>';
$html .='<td colspan="2" style="line-height:11px;font-size:11px;text-align:left;"></td>';
// $html .='<td style="line-height:11px;font-size:11px;text-align:left;"></td>';
$html .='</tr>';


$html .='<tr>';
$html .='<td colspan="3" style="line-height:10px;"></td>';
$html .='</tr>';
$html .='<tr>';
$html .='<td colspan="3" style="line-height:2px;border-bottom:2px solid #d3d3d3;"></td>';
$html .='</tr>';


$html .='<tr>';
$html .='<td colspan="3" style="line-height:10px;"></td>';
$html .='</tr>';

$html .='<tr>';
$html .='<td colspan="3" style="line-height:11px;font-size:11px;font-weight:bold;">RESULTS</td>';
$html .='</tr>';
$html .='<tr>';
$html .='<td colspan="3" ></td>';
$html .='</tr>';

$html .='<tr>';
$html .='<td colspan="3" style="line-height:11px;font-size:11px;font-weight:bold;text-align:left;">HIV RECENCY*&nbsp;&nbsp;&nbsp;<span style="font-weight:normal;">'.$result['final_outcome'].'</span></td>';
$html .='</tr>';

$html .='<tr>';
$html .='<td style="line-height:11px;font-size:11px;text-align:left;"></td>';
$html .='</tr>';

if(isset($result['vl_result']) && !empty($result['vl_result'])){
    $html .='<tr>';
    $html .='<td colspan="3" style="line-height:11px;font-size:11px;font-weight:bold;text-align:left;">VIRAL LOAD RESULT(copies/ml)**&nbsp;&nbsp;&nbsp;<span style="font-weight:normal;">'.$result['vl_result'].'</span></td>';
    $html .='</tr>';
}

$html .='<tr>';
$html .='<td style="line-height:11px;font-size:11px;text-align:left;"></td>';
$html .='</tr>';


$html .='<tr>';
$html .='<td colspan="3" style="line-height:10px;"></td>';
$html .='</tr>';

$html .='<tr>';
$html .='<td colspan="3" style="line-height:2px;border-bottom:2px solid #d3d3d3;"></td>';
$html .='</tr>';
$html .='<tr>';
$html .='<td colspan="3" style="line-height:14px;"></td>';
$html .='</tr>';


$html .='<tr>';
$html .='<td  style="line-height:11px;font-size:11px;font-weight:bold;">TESTED BY&nbsp;&nbsp;:&nbsp;&nbsp;<span style="font-weight:normal;">'.$result['tester_name'].'</span></td>';
$html .='<td colspan="3" style="line-height:11px;font-size:11px;font-weight:bold;">APPROVED BY&nbsp;&nbsp;:&nbsp;&nbsp;<span style="font-weight:normal;"></span></td>';
$html .='</tr>';
$html .='<tr>';
$html .='<td colspan="3" style="line-height:10px;"></td>';
$html .='</tr>';

$html .='<tr>';
$html .='<td colspan="3" style="line-height:2px;border-bottom:2px solid #d3d3d3;"></td>';
$html .='</tr>';
$html .='<tr>';
$html .='<td colspan="3" style="line-height:2px;"></td>';
$html .='</tr>';
$html .='<tr>';
$html .='<td colspan="3">';
$html .='<table>';
$html .='<tr>';
$html .='<td colspan="2" style="font-size:9px;text-align:left;width:60%;"> *Test results are based on RITA and reported as RITA Recent, Long-term or Inconclusive</td>';
$html .='<td style="font-size:9px;text-align:left;">Printed on : '.date('d-M-Y H:i:s').'</td>';
$html .='</tr>';
$html .='<tr>';
$html .='<td style="font-size:9px;text-align:left;width:60%;">**VL result is only provided for “Recent’ HIV Recency test results</td>';
$html .='</tr>';


$html .='</table>';
$html .='</td>';
$html .='</tr>';
$html.='</table>';
$pdf->writeHTML($html);
$pdf->lastPage();
$filename = 'Recency-Result-' . date('d-M-Y-H-i-s') . '.pdf';
$pdf->Output(TEMP_UPLOAD_PATH . DIRECTORY_SEPARATOR . $filename,"F");
echo $filename;


