<?php if(count($result)>0){ ?>
<script>
Highcharts.chart('recencyLabActivity', {
    credits: {
            enabled: false
        },
    chart: {
        type: 'column'
    },
    title: {
        text: ''
    },
    subtitle: {
        text: ''
    },
    xAxis: {
        categories: [
            <?php  foreach($result['date'] as $res){?>
                    '<?php echo $res; ?>',
               <?php } ?>
        ],
        crosshair: true
    },
    yAxis: {
        min: 0,
        title: {
            text: ''
        }
    },
    tooltip: {
        headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
        pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
            '<td style="padding:0"><b>{point.y:.1f}</b></td></tr>',
        footerFormat: '</table>',
        shared: true,
        useHTML: true
    },
    plotOptions: {
        column: {
            pointPadding: 0.2,
            borderWidth: 0
        }
    },
    series: [
        <?php
           if(isset($result['labActivity']) && count($result['labActivity']) >0){
              foreach($result['labActivity'] as $key=>$condition){
              ?>
        {
        name: '<?php echo $key;?>',
        data: [<?php
                  foreach($condition as $count){
                    echo $count.",";
                  }
              ?>]

    }, 
    <?php
              }
           }
            ?>]


});
</script>
<?php }else{
    echo "<h2 style='text-align:center;'>No data available</h2>";
} ?>