<?php if(count($result)>0){ ?>
<script>
Highcharts.chart('testerWiseInvalid', {
    credits: {
            enabled: false
    },
    exporting: {
    buttons: {
      contextButton: {
        menuItems: [
          'printChart',
          'separator',
          'downloadPNG',
          'downloadJPEG',
          'downloadPDF',
          'downloadSVG',
          'separator',
          'downloadCSV',
          'downloadXLS',
          'viewData'
        ]
      }
    }
    },
    chart: {
        type: 'column'
    },
    title: {
        text: ''
    },
    subtitle: {
        text: ''
    },
    xAxis: {
        categories: [
            <?php  foreach($result['testerName'] as $res){?>
                    '<?php echo $res; ?>',
               <?php } ?>
        ],
        crosshair: true,
        min: 0,
        max: 4,
        scrollbar: {
            enabled: true
        }
    },
    yAxis: {
        min: 0,
        title: {
            text: ''
        }
    },
    tooltip: {
        headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
        pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
            '<td style="padding:0"><b>{point.y}</b></td></tr>',
        footerFormat: '</table>',
        shared: true,
        useHTML: true
    },
    plotOptions: {
        column: {
            pointPadding: 0.2,
            borderWidth: 0
        },
        series: {
            dataLabels: {
                enabled: true,
                format: '{point.y}'
            }
        }
    },
    colors: [
        '#80699B',
        '#AA4643',
        '#24CBE5',
        '#A47D7C',
        '#fec16f',
        '#989898',
        '#f5c3f5',
        '#215682',
        '#8dafbc',
        '#66d3c5'
	],
    series: [
        <?php
           if(isset($result['finalOutCome']) && count($result['finalOutCome']) >0){
              foreach($result['finalOutCome'] as $key=>$condition){
              ?>
        {
        name: '<?php echo $key;?>',
        data: [<?php
                  foreach($condition as $count){
                    echo $count.",";
                  }
              ?>]

    }, 
    <?php
              }
           }
            ?>]


});
</script>
<?php }else{
    echo "<h2 style='text-align:center;'>No data available</h2>";
} ?>