<?php if(count($result)>0){
    $n=count($result['facilityName']);
    if($n>4){
        $max='4';
    }else{
        $max=$n-1;
    }
?>
<script>
Highcharts.chart('facilityWiseInvalid', {
    credits: {
            enabled: false
    },
    exporting: {
    buttons: {
      contextButton: {
        menuItems: [
          'printChart',
          'separator',
          'downloadPNG',
          'downloadJPEG',
          'downloadPDF',
          'downloadSVG',
          'separator',
          'downloadCSV',
          'downloadXLS',
          'viewData'
        ]
      }
    }
    },
    chart: {
        type: 'column'
    },
    title: {
        text: "N=<?php echo $result['total']; ?>"
    },
    xAxis: {
        categories: [
            <?php  foreach($result['facilityName'] as $res){?>
                    '<?php echo $res; ?>',
               <?php } ?>
        ],
        crosshair: true,
        min: 0,
        max: '<?php echo $max; ?>',
        scrollbar: {
            enabled: true
        },
        title: {
            enabled: true,
            text: 'Name of Facility',
            style: {
                fontSize: '15px',
            }
        }
    },
    yAxis: {
        min: 0,
        title: {
            text: ''
        }
    },
    tooltip: {
        headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
        pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
            '<td style="padding:0"><b>{point.y}</b></td></tr>',
        footerFormat: '</table>',
        shared: true,
        useHTML: true
    },
    plotOptions: {
        column: {
            pointPadding: 0.2,
            borderWidth: 0
        },
        series: {
            dataLabels: {
                enabled: true,
                format: '{point.y}'
            }
        }
    },
    colors: [
        '#92A8CD',
        '#AA4643',
        '#24CBE5',
        '#A47D7C',
        '#fec16f',
        '#989898',
        '#f5c3f5',
        '#215682',
        '#8dafbc',
        '#66d3c5'
	],
    series: [
        <?php
           if(isset($result['fInvalidReport']) && count($result['fInvalidReport']) >0){
              foreach($result['fInvalidReport'] as $key=>$condition){
              ?>
        {
        name: '<?php echo $key;?>',
        data: [<?php
                  foreach($condition as $count){
                    echo $count.",";
                  }
              ?>]

    }, 
    <?php
              }
           }
            ?>]


});
</script>
<?php }else{
    echo "<br><br><br><br><br><br><br><h2 style='text-align:center;color:#aaa'>No data available</h2>";
} ?>