<?php

use Zend\Session\Container;
$sessionLogin = new Container('credo');
$roleCode = $sessionLogin->roleCode;
$editAction = '{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center",bSortable:false}';
?>
<div class="bg-body-light">
     <div class="content content-full">
          <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
               <h1 class="flex-sm-fill font-size-h2 font-w400 mt-2 mb-0 mb-sm-2">Recency Data</h1>
                    <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                         <ol class="breadcrumb">
                              <li class="breadcrumb-item">
                                   <?php //if($roleCode == "user"){ ?>
                                   <a href="<?php echo $this->url('recency',array('action' => 'add'));?>" class="btn btn-primary pull-right" style="margin-top:-5px;"><i class="fa fa-plus"></i>&nbsp;Add New Recency</a>
                                   <?php if($roleCode=='admin'){ ?>
                                   <a href="javascript:void(0)" class="btn btn-primary pull-right" style="margin-top:-5px;" onclick="exportRecencyData();"><i class="fa fa-download"></i>&nbsp;Export Excel</a>
                                   <?php } ?>
                              <?php     //}
                              ?>
                              </li>
                         </ol>
                    </nav>
               </div>
          </div>
     </div>
     <div class="content">
          <div class="block block-rounded block-bordered">
               <div class="block-header block-header-default">
               </div>
               <div class="block-content block-content-full">
                    <table id="facilityDataTable" class="table-responsive table table-bordered table-striped table-vcenter table-responsive">
                         <thead>
                              <tr>
                                    <th>Sample Id</th>
                                    <th>Patient Id</th>
                                    <th>Facility Name</th>
                                    <th>HIV Diagnosis Date</th>
                                    <th>HIV Recency Date</th>
                                    <th>Control Line</th>
                                    <th>Positive Verification</th>
                                    <th>Long Term Verification</th>
                                    <th>Kit Lot Number</th>
                                    <th>Kit Expiry Date</th>
                                    <th>Term Outcome</th>
                                    <th>Final Outcome</th>
                                    <th>VL Result</th>
                                    <th>Tester Name</th>
                                    <th>DOB</th>
                                    <th>Age</th>
                                    <th>Gender</th>
                                    <th>Martial Status</th>
                                    <th>Residence</th>
                                    <th>Edication Level</th>
                                    <th>Risk Population</th>
                                    <th>Pregnancy Status</th>
                                    <th>Current Sexual Partner</th>
                                    <th>Past HIV Testing</th>
                                    <th>Last HIV Status</th>
                                    <th>Patient On Art</th>
                                    <th>Last 12 Month</th>
                                    <th>Experienced Violence Last 12 Month</th>
                                    <th>Form Initiation Datetime</th>
                                    <th>Form Transfer Datetime</th>
                                    <th>Action</th>
                              </tr>
                         </thead>
                         <tbody>
                              <tr>
                                <?php if($roleCode == "user"){
                                   echo "<td colspan='9' class='dataTables_empty'>Loading data from server</td>";
                                }else{
                                    echo "<td colspan='8' class='dataTables_empty'>Loading data from server</td>";
                                }?>
                              </tr>
                              <tr>
                              </tbody>
                         </table>
                    </div>
               </div>
          </div>

          <script type="text/javascript">
          /* Table initialisation */
          oTable = null;
          $(document).ready(function() {
            oTable = $('#facilityDataTable').dataTable({
                "bAutoWidth": false,
                "bProcessing": true,
                "bServerSide": true,
                "aoColumns": [
                        <?php echo $editAction;?>
                ],
                "sAjaxSource": "<?php echo $this->url('recency',array('action' => 'index')); ?>",
                "fnServerData": function ( sSource, aoData, fnCallback ) {
                    $.ajax({
                        "dataType": 'json',
                        "type": "POST",
                        "url": sSource,
                        "data": aoData,
                        "success": fnCallback
                    });
                }
            } );
          });
        
        function exportRecencyData()
        {
            $.blockUI();
            $.post("<?php echo $this->url('recency',array('action'=>'export-recency')); ?>",
                function(data){
                if(data == "" || data == null || data == undefined){
                $.unblockUI();
                alert('Unable to generate download');
                }else{
                $.unblockUI();
                document.location.href = '/temporary/'+data;
                }
            });
        }
     </script>
