<?php 

$format = $result['format'];

if(count($result)>0){
    $n=count($result['monthyear']);
    if($n>4){
        $max='4';
    }else{
        $max=$n-1;
    }
?>
<script>
Highcharts.chart('infectionByMonthSex', {
    credits: {
            enabled: false
    },
    exporting: {
    filename : 'Recent Infection by Month',
    buttons: {
      contextButton: {
        menuItems: [
          'printChart',
          'separator',
          'downloadPNG',
          'downloadJPEG',
          'downloadPDF',
          'downloadSVG',
          'separator',
          'downloadCSV',
          'downloadXLS',
          'viewData'
        ]
      }
    }
    },
    chart: {
        type: 'column'
    },
    title: {
        text: ""
    },
    xAxis: {
        categories: [
            <?php  foreach($result['monthyear'] as $res){?>
                    '<?php echo $res; ?>',
               <?php } ?>
        ],
        crosshair: true,
        min: 0,
        max: '<?php echo $max; ?>',
        scrollbar: {
            enabled: true
        },
        title: {
            enabled: true,
            text: 'Month (N=<?php echo $result['total']; ?>)',
            style: {
                fontSize: '12px',
            }
        }
    },
    yAxis: {
        min: 0,
        <?php if($format =='percentage') { ?>
        max:100,
        <?php } ?> 
        title: {
            <?php if($format =='percentage') { ?>
            text: 'Recent Infection %'
            <?php } else { ?>
            text: 'Recent Infections'
            <?php } ?>
        }        
    },
    tooltip: {
        headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
        pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
            '<td style="padding:0"><b>{point.y}</b></td></tr>',
        footerFormat: '</table>',
        shared: true,
        useHTML: true
    },
    
    plotOptions: {
        series: {
            borderWidth: 0,
            dataLabels: {
                enabled: true,
                formatter: function() {
                    <?php if($format =='percentage') { ?>
                        return this.y > 0 ? this.y + '%' : 0;
                    <?php } else { ?>
                        return this.y;
                    <?php } ?>                    
                }
            }
        }
    },
    colors: [
        '#ad7bf7',
        '#0178b7',
        '#898989'
	],
    series: [
        <?php
        $k=0;
           if(isset($result['finalOutCome']) && count($result['finalOutCome']) >0){
              foreach($result['finalOutCome'] as $key=>$condition){
              ?>
        {
        name: '<?php echo $key;?>',
        data: [<?php
                  foreach($condition as $count){
                ?>
                
                { y: <?php echo $count; ?>}, 
                <?php
                $k++;
                  }
              ?>
              
              ]

    }, 
    <?php
              }
           }
            ?>]
    
});
</script>
<?php }else{
    echo "<br><br><br><br><br><br><br><h2 style='text-align:center;color:#aaa'>No data available</h2>";
} ?>