<?php 

$format = $result['format'];

if(count($result)>0){
$color=['#ad7bf7','#0178b7','#898989','#cca9ff','#4fafe2','#a8a8a8','#dfd0f4','#9cd5f4','#dbd9d9'];
?>
<script>
Highcharts.chart('container', {
    credits: {
            enabled: false
    },
    exporting: {
    chartOptions:{
        title: {
            text:'Recent Infection by Gender',
        }
    }   ,     
    filename : 'Recent Infection by Gender',
    buttons: {
      contextButton: {
        menuItems: [
          'printChart',
          'separator',
          'downloadPNG',
          'downloadJPEG',
          'downloadPDF',
          'downloadSVG',
          'separator',
          'downloadCSV',
          'downloadXLS',
          'viewData'
        ]
      }
    }
    },
    chart: {
        type: 'column'
    },
    title: {
        text: ""
    },
    xAxis: {
        categories: [
            <?php  foreach($result['gender'] as $res){?>
                    '<?php echo $res; ?>',
               <?php } ?>
        ],
        crosshair: true,
        title: {
            enabled: true,
            text: 'Gender (N=<?php echo $result['total']; ?>)',
            style: {
                fontWeight: 'normal'
            }
        }
    },
    yAxis: {
        min: 0,
        <?php if($format =='percentage') { ?>
        max:100,
        <?php } ?>        
        title: {
            <?php if($format =='percentage') { ?>
            text: 'Final Outcome %'
            <?php } else { ?>
            text: 'Number of Tests'
            <?php } ?>
        }
    },
    legend: {
      enabled: true,
    },    
    tooltip: {
        headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
        pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
            '<td style="padding:0"><b>{point.y:1f}</b></td></tr>',
        footerFormat: '</table>',
        shared: true,
        useHTML: true
    },
    plotOptions: {
        series: {
            borderWidth: 0,
            dataLabels: {
                enabled: true,
                formatter: function() {
                    <?php if($format =='percentage') { ?>
                        return this.y > 0 ? this.y + '%' : 0;
                    <?php } else { ?>
                        return this.y;
                    <?php } ?>                    
                }
            }
        }
    },
    colors: [
        '#0d233a',
        '#ada4ec',
        '#24CBE5',
        '#A47D7C',
        '#fec16f',
        '#989898',
        '#f5c3f5',
        '#215682',
        '#8dafbc',
        '#66d3c5'
	],
    series: [
        <?php
        $k=0;
           if(isset($result['finalOutCome']) && count($result['finalOutCome']) >0){
              foreach($result['finalOutCome'] as $seriesName => $values){
              ?>
        {
        name: '<?php echo $seriesName;?>',
        color : "#555",
        data: [<?php
                  foreach($values as $valueName => $count){
                    //echo $count.",";
                ?>
                
                { name : '<?php echo $valueName; ?>', y: <?php echo $count; ?>, color: '<?php echo $color[$k]; ?>'}, 
                <?php
                $k++;
                  }
              ?>
              
              ]

    }, 
    <?php
              }
           }
            ?>]


});
</script>
<?php }else{
    echo "<br><br><br><br><br><br><br><h2 style='text-align:center;color:#aaa'>No data available</h2>";
} ?>