<?php if(count($result)>0){
?>
<script>
Highcharts.chart('infectionByAge', {
    credits: {
            enabled: false
    },
    exporting: {
    buttons: {
      contextButton: {
        menuItems: [
          'printChart',
          'separator',
          'downloadPNG',
          'downloadJPEG',
          'downloadPDF',
          'downloadSVG',
          'separator',
          'downloadCSV',
          'downloadXLS',
          'viewData'
        ]
      }
    }
    },
    chart: {
        type: 'column'
    },
    title: {
        text: ""
    },
    xAxis: {
        categories: [
            <?php  foreach($result['ageGroup'] as $res){?>
                    '<?php echo $res; ?>',
               <?php } ?>
        ],
        crosshair: true,
        title: {
            enabled: true,
            text: 'Age Report <br>(N=<?php echo $result['total']; ?>)',
            style: {
                fontSize: '15px',
            }
        }
    },
    yAxis: {
        min: 0,
        title: {
            text: 'Recent'
        }
    },
    tooltip: {
        headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
        pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
            '<td style="padding:0"><b>{point.y}</b></td></tr>',
        footerFormat: '</table>',
        shared: true,
        useHTML: true
    },
    
    plotOptions: {
        series: {
            borderWidth: 0,
            dataLabels: {
                enabled: true,
                format: '{point.y}'
            }
        }
    },
    colors: [
        '#ad7bf7',
        '#0178b7',
        '#898989'
	],
    series: [
        <?php
        $k=0;
           if(isset($result['finalOutCome']) && count($result['finalOutCome']) >0){
              foreach($result['finalOutCome'] as $key=>$condition){
              ?>
        {
        name: '<?php echo $key;?>',
        data: [<?php
                  foreach($condition as $count){
                ?>
                
                { y: <?php echo $count; ?>}, 
                <?php
                $k++;
                  }
              ?>
              
              ]

    }, 
    <?php
              }
           }
            ?>]
    
});
</script>
<?php }else{
    echo "<h2 style='text-align:center;'>No data available</h2>";
} ?>