<?php
use Zend\Session\Container;
use Application\Service\CommonService;
$sessionLogin = new Container('credo');
$common = new CommonService()
// \Zend\Debug\Debug::dump($result);die;
?>
<style>
<?php
if($result['term_outcome']==''){
?>
.outcome{display:none;}
<?php
}
?>
.colour{color:red;}
</style>

<div class="bg-body-light">
     <div class="content content-full">
          <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
               <h1 class="flex-sm-fill font-size-h2 font-w400 mt-2 mb-0 mb-sm-2">View Recency Data</h1>
               <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                    <ol class="breadcrumb">
                         <a href="<?php echo $this->url('recency', array('action' => 'index')); ?>"><li class="breadcrumb-item">Recency Details</li></a>
                         <li class="breadcrumb-item active" aria-current="page">&nbsp;/ View</li>
                    </ol>
               </nav>
          </div>
     </div>
</div>

<!-- /.content -->

<div class="content">
     <div class="block block-rounded block-bordered">
          <div class="block-header block-header-default">
            <a href="<?php echo $this->url('recency', array('action' => 'index')); ?>" class="btn btn-primary">Back</a>
          </div>
          <section class="content">
               <!-- left column -->
               <div class="">
                    <div class="box box-primary">
                         <div class="box-header">
                         </div><!-- /.box-header -->
                         <div class="box-body">
                              <h3 class="block-title" style=" margin-bottom: 4%; ">Recency</h3>
                              <div class="row">
                                   <div class="col-md-6">
                                        <div class="form-group">
                                             <label for="company" class="col-lg-4 control-label">Sample Id</label>
                                             <label for="company" class="col-lg-1 control-label">: </label>
                                             <span style="text-align: left;" for="company" class="col-lg-6 control-label">
                                                  <?php echo ucwords($result['sample_id']); ?>
                                             </span>
                                        </div>
                                   </div>
                                   <div class="col-md-6">
                                        <div class="form-group">
                                             <label for="company" class="col-lg-4 control-label">Patient Id</label>
                                             <label for="company" class="col-lg-1 control-label">: </label>
                                             <span style="text-align: left;" for="company" class="col-lg-6 control-label">
                                                  <?php echo ucwords($result->patient_id); ?>
                                             </span>
                                        </div>
                                   </div>

                                   <div class="col-md-6">
                                        <div class="form-group">
                                             <label for="orderDate" class="col-lg-4 control-label">Facility Name</label>
                                             <label for="company" class="col-lg-1 control-label">: </label>
                                             <span style="text-align: left;" for="company" class="col-lg-4 control-label">
                                                  <?php echo ucwords($result->facility_name); ?>
                                             </span>
                                        </div>
                                   </div>
                                   <div class="col-md-6">
                                        <div class="form-group">
                                             <label for="orderDate" class="col-lg-4 control-label">HIV Diagnosis Date</label>
                                             <label for="company" class="col-lg-1 control-label">: </label>
                                             <span style="text-align: left;" for="company" class="col-lg-4 control-label">
                                                  <?php echo ($result->hiv_diagnosis_date!='' && $result->hiv_diagnosis_date!='0000:00:00')?$common->humanDateFormat($result->hiv_diagnosis_date):''; ?>
                                             </span>
                                        </div>
                                   </div>


                                   <div class="col-md-6">
                                        <div class="form-group">
                                             <label for="termsOfPay" class="col-lg-4 control-label">Past HIV Testing</label>
                                             <label for="company" class="col-lg-1 control-label">: </label>
                                             <span style="text-align: left;" for="company" class="col-lg-4 control-label">
                                                  <?php echo ucwords($result->past_hiv_testing); ?>
                                             </span>
                                        </div>
                                   </div>
                                   <?php if($result->past_hiv_testing == 'yes'){ ?>
                                   <div class="col-md-6">
                                        <div class="form-group">
                                             <label for="otherRef" class="col-lg-4 control-label">Tested In Last 12 Months?</label>
                                             <label for="company" class="col-lg-1 control-label">: </label>
                                             <span style="text-align: left;" for="company" class="col-lg-4 control-label">
                                                  <?php echo ucwords(str_replace('_', ' ', $result->test_last_12_month)); ?>
                                             </span>
                                        </div>
                                   </div>

                                   <div class="col-md-6">
                                        <div class="form-group">
                                             <label for="otherRef" class="col-lg-4 control-label">Last HIV Status?</label>
                                             <label for="company" class="col-lg-1 control-label">: </label>
                                             <span style="text-align: left;" for="company" class="col-lg-4 control-label">
                                                  <?php echo ucwords(str_replace('_', ' ', $result->last_hiv_status)); ?>
                                             </span>
                                        </div>
                                   </div>
                                   <?php } ?>

                                   <?php if($result->last_hiv_status == 'positive'){ ?>
                                        <div class="col-md-6">
                                             <div class="form-group">
                                                  <label for="otherRef" class="col-lg-4 control-label">Is the Patient on ART? </label>
                                                  <label for="company" class="col-lg-1 control-label">: </label>
                                                  <span style="text-align: left;" for="company" class="col-lg-4 control-label">
                                                       <?php echo ucwords(str_replace('_', ' ', $result->patient_on_art)); ?>
                                                  </span>
                                             </div>
                                        </div>


                                        <?php
                                        }
                                        elseif ($result->last_hiv_status == 'negative')
                                        { ?>

                                        <div class="col-md-6">
                                             <div class="form-group">
                                                  <label for="company" class="col-lg-1 control-label"> </label>
                                                  <span style="text-align: left;" for="company" class="col-lg-4 control-label">

                                                  </span>
                                             </div>
                                        </div>

                                        <?php
                                        } ?>

                                   <div class="col-md-6">
                                        <div class="form-group">
                                             <label for="otherRef" class="col-lg-4 control-label">Recency Test not performed</label>
                                             <label for="company" class="col-lg-1 control-label">: </label>
                                             <span style="text-align: left;" for="company" class="col-lg-4 control-label">
                                             <input type="checkbox" disabled class="form-check-input" style="border:none;" name="recencyTestPerformed" id="recencyTestPerformedYes"
                                             <?php echo($result['recency_test_performed'] == 'true' )?'checked="checked"':''; ?> value="true"/>&nbsp;Yes
                                             </span>
                                        </div>
                                   </div>
                                   <?php if($result->recency_test_performed == '')
                                   {
                                    ?>
                                    <div class="col-md-6">
                                         <div class="form-group">
                                              <label for="termsOfPay" class="col-lg-4 control-label">HIV Recency Date</label>
                                              <label for="company" class="col-lg-1 control-label">: </label>
                                              <span style="text-align: left;" for="company" class="col-lg-4 control-label">
                                                   <?php echo ($result->hiv_recency_date!='' && $result->hiv_recency_date!='0000:00:00')?$common->humanDateFormat($result->hiv_recency_date):''; ?>
                                              </span>
                                         </div>
                                    </div>
                                    <div class="col-md-6">
                                         <div class="form-group">
                                              <label for="otherRef" class="col-lg-4 control-label">Control Line</label>
                                              <label for="company" class="col-lg-1 control-label">: </label>
                                              <span style="text-align: left;" for="company" class="col-lg-4 control-label">
                                                   <?php
                                                   if($result['control_line'] == 'present')
                                                   {
                                                        echo "Present";
                                                   }
                                                   elseif ($result['control_line'] == 'absent') {
                                                        echo "Absent";
                                                   }
                                                   ?>
                                              </span>
                                         </div>
                                    </div>
                                    <div class="col-md-6">
                                         <div class="form-group">
                                              <label for="otherRef" class="col-lg-4 control-label">Positive Verification</label>
                                              <label for="company" class="col-lg-1 control-label">: </label>
                                              <span style="text-align: left;" for="company" class="col-lg-4 control-label">
                                                   <?php
                                                   if($result['positive_verification_line'] == 'present')
                                                   {
                                                        echo "Present";
                                                   }
                                                   elseif ($result['positive_verification_line'] == 'absent') {
                                                        echo "Absent";
                                                   }

                                                   ?>
                                              </span>
                                         </div>
                                    </div>
                                    <div class="col-md-6">
                                         <div class="form-group">
                                              <label for="otherRef" class="col-lg-4 control-label">Long Term Verification</label>
                                              <label for="company" class="col-lg-1 control-label">: </label>
                                              <span style="text-align: left;" for="company" class="col-lg-4 control-label">
                                                   <?php
                                                   if($result['long_term_verification_line'] == 'present')
                                                   {
                                                        echo "Present";
                                                   }
                                                   elseif ($result['long_term_verification_line'] == 'absent') {
                                                        echo "Absent";
                                                   }

                                                   ?>
                                              </span>
                                         </div>
                                    </div>
                                   <?php
                                   }
                                   elseif ($result->recency_test_performed == 'true')
                                   { ?>

                                   <div class="col-md-6">
                                        <div class="form-group">
                                             <label for="otherRef" class="col-lg-4 control-label">Reason of Recency Test Not Performed</label>
                                             <label for="company" class="col-lg-1 control-label">: </label>
                                             <span style="text-align: left;" for="company" class="col-lg-4 control-label">

                                                  <?php
                                                  if($result['recency_test_not_performed'] == 'other')
                                                  {
                                                        echo ucwords(str_replace('_', ' ', $result->other_recency_test_not_performed));
                                                  }else
                                                  {
                                                       echo ucwords(str_replace('_', ' ', $result->recency_test_not_performed));
                                                  }
                                                  ?>

                                             </span>
                                        </div>
                                   </div>

                                   <?php
                                   } ?>
                                   <div class="col-md-6 outcome">
                                        <div class="form-group">
                                             <label for="otherRef" class="col-lg-4 control-label">Outcome</label>
                                             <label for="company" class="col-lg-1 control-label">: </label>
                                             <span style="text-align: left;" for="company" class="col-lg-4 control-label">
                                              <?php echo $result['term_outcome'];?>
                                             </span>
                                        </div>
                                   </div>
                              </div>
                              <!--  -->
                         </div>
                         <hr>
                         <h3 class="block-title" style=" margin-bottom: 4%; ">Behaviours</h3>
                         <div class="box-body">
                         <div class="row">
                                   <div class="col-md-6">
                                        <div class="form-group">
                                             <label for="termsOfPay" class="col-lg-4 control-label">DOB</label>
                                             <label for="company" class="col-lg-1 control-label">: </label>
                                             <span style="text-align: left;" for="company" class="col-lg-4 control-label">
                                                  <?php echo ($result->dob!='' && $result->dob!='0000:00:00')?$common->humanDateFormat($result->dob):''; ?>
                                             </span>
                                        </div>
                                   </div>
                                   <div class="col-md-6">
                                        <div class="form-group">
                                             <label for="otherRef" class="col-lg-4 control-label"> Age</label>
                                             <label for="company" class="col-lg-1 control-label">: </label>
                                             <span style="text-align: left;" for="company" class="col-lg-4 control-label">
                                                  <?php echo ucwords($result->age); ?>
                                             </span>
                                        </div>
                                   </div>
                              </div>

                              <div class="row">
                                   <div class="col-md-6">
                                        <div class="form-group">
                                             <label for="termsOfPay" class="col-lg-4 control-label">Gender</label>
                                             <label for="company" class="col-lg-1 control-label">: </label>
                                             <span style="text-align: left;" for="company" class="col-lg-4 control-label">
                                                  <?php echo ucwords(str_replace('_', ' ', $result->gender));?>
                                             </span>
                                        </div>
                                   </div>



                              <?php if($result->gender != 'male') {  ?>
                                   <div class="col-md-6">
                                        <div class="form-group">
                                             <label for="termsOfPay" class="col-lg-4 control-label">Pregnancy Status</label>
                                             <label for="company" class="col-lg-1 control-label">: </label>
                                             <span style="text-align: left;" for="company" class="col-lg-4 control-label">
                                                  <?php echo ucwords(str_replace('_', ' ', $result->pregnancy_status));?>
                                             </span>
                                        </div>
                                   </div>

                              <?php } ?>
                              </div>

                              <div class="row">
                                   <div class="col-md-6">
                                        <div class="form-group">
                                             <label for="company" class="col-lg-4 control-label">Marital Status</label>
                                             <label for="company" class="col-lg-1 control-label">: </label>
                                             <span style="text-align: left;" for="company" class="col-lg-6 control-label">
                                                  <?php echo ucwords(str_replace('_', ' ', $result->marital_status));?>
                                             </span>
                                        </div>
                                   </div>
                                   <div class="col-md-6">
                                        <div class="form-group">
                                             <label for="orderDate" class="col-lg-4 control-label">Education Level</label>
                                             <label for="company" class="col-lg-1 control-label">: </label>
                                             <span style="text-align: left;" for="company" class="col-lg-4 control-label">
                                                  <?php echo ucwords(str_replace('_', ' ', $result->education_level));?>
                                             </span>
                                        </div>
                                   </div>
                              </div>
                              <div class="row">
                                   <div class="col-md-6">
                                        <div class="form-group">
                                             <label for="orderDate" class="col-lg-4 control-label">Risk Population</label>
                                             <label for="company" class="col-lg-1 control-label">: </label>
                                             <span style="text-align: left;" for="company" class="col-lg-4 control-label">
                                                  <?php  echo ucwords(str_replace('_', ' ', $result->name)); ?>
                                             </span>
                                        </div>
                                   </div>
                                   <div class="col-md-6">
                                        <div class="form-group">
                                             <label for="company" class="col-lg-4 control-label">Residence</label>
                                             <label for="company" class="col-lg-1 control-label">: </label>
                                             <span style="text-align: left;" for="company" class="col-lg-6 control-label">
                                                  <?php echo ucwords($result->residence); ?>
                                             </span>
                                        </div>
                                   </div>

                              </div>

                              <div class="row">
                                   <div class="col-md-6">
                                        <div class="form-group">
                                             <label for="otherRef" class="col-lg-4 control-label">Current Sexual Partner</label>
                                             <label for="company" class="col-lg-1 control-label">: </label>
                                             <span style="text-align: left;" for="company" class="col-lg-4 control-label">
                                                  <?php echo ucwords(str_replace('_', ' - ', $result->current_sexual_partner));?>
                                             </span>
                                        </div>
                                   </div>
                                   <div class="col-md-6">
                                        <div class="form-group">
                                             <label for="otherRef" class="col-lg-4 control-label">Experienced violence in last 12 months</label>
                                             <label for="company" class="col-lg-1 control-label">: </label>
                                             <span style="text-align: left;" for="company" class="col-lg-4 control-label">
                                                  <?php echo ucwords(str_replace('_', ' - ', $result->exp_violence_last_12_month));?>
                                             </span>
                                        </div>
                                   </div>
                              </div>

                              <div class="row">
                                   <div class="col-md-6">
                                        <div class="form-group">
                                             <label for="otherRef" class="col-lg-4 control-label">Comments</label>
                                             <label for="company" class="col-lg-1 control-label">: </label>
                                             <span style="text-align: left;" for="company" class="col-lg-4 control-label">
                                                  <?php echo ucwords(str_replace('_', ' ', $result->notes));?>
                                             </span>
                                        </div>
                                   </div>
                              </div>

                         </div>
                    </div>
               </div>
          </section>
     </div>
</div>
