<?php

use Laminas\Session\Container;

$sessionLogin = new Container('credo');
$roleCode = $sessionLogin->roleCode;
$acl=$this->layout()->acl;
$ageArray = array('15-19', '20-24', '25-29', '30-34', '35-39', '40-44', '45-49', '50+');
?>
<style>
    th:empty {
        display: none !important;
    }

    td:empty {
        display: none !important;
    }

    /* Started freeze the columns */
    .frezz td:first-child,
    .frezz td:first-child {
        position: sticky !important;
        left: -1%;
        z-index: 1;
        background-color: white;
        padding: 18px !important;
    }

    .frezz th:nth-of-type(1),
    .frezz th:nth-of-type(1) {
        position: sticky !important;
        left: -1%;
        z-index: 1;
        background-color: white;
        padding: 18px !important;
    }

    /* end here */
</style>
<link rel="stylesheet" href="<?php echo $this->basePath() . '/assets/plugins/datepicker/daterangepicker.css' ?>" rel="stylesheet">
<div class="bg-body-light">
    <div class="content content-full">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
            <h1 class="flex-sm-fill font-size-h2 font-w400 mt-2 mb-0 mb-sm-2">Age-wise Infection Report</h1>
        </div>
    </div>
</div>
<div class="content">
    <div class="row sticky-div" style="margin-bottom: 20px; ">
        <div class="form-group row" style="margin: 0px !important;padding: 15px 0px;">
            <div class="col-sm-4" style=" margin-top:10px;">
                <input type="text" id="sampleTestedDates" name="sampleTestedDates" class="form-control" placeholder="Select Sample Collection Date Range" readonly style="background:#fff;" value="" />
            </div>
            <?php
            foreach ($globalConfigResult as $config) { ?>
                <?php if ($config['global_name'] == 'location_one' || $config['global_name'] == 'location_two' || $config['global_name'] == 'location_three') { ?>
                    <div class="col-sm-2" style=" margin-top: 10px; ">
                        <select class="form-control" id="<?php echo $config['global_name']; ?>" name="<?php echo $config['global_name']; ?>" title="Please enter the <?php echo lcfirst($config['global_value']); ?>" onchange="getLocationDeatils('<?php echo $config["global_name"]; ?>');">
                            <option value="">-- Select --</option>
                        </select>
                    </div>
            <?php }
            } ?>
            <div class="col-sm-2" style=" margin-top: 10px; ">
                <select class="form-control" id="facilityId" name="facilityId" title="Please choose facility">
                    <option value="">-- Select --</option>
                </select>
            </div>

            <div class="col-sm-2" style=" margin-top: 10px; ">
                <select class="form-control" id="testingFacility" name="testingFacility" title="Please select testing facility name" style="width:100%;">
                    <option value=""> -- Select-- </option>
                    <?php foreach ($facilityResult['facilityTest'] as $facilityRow) { ?>
                        <option value="<?php echo $facilityRow['facility_id']; ?>"><?php echo ucwords($facilityRow['facility_name']); ?></option>
                    <?php } ?>
                </select>
            </div>
            <div class="col-sm-2" style=" margin-top: 10px; ">
                <select class="form-control" id="testingModality" name="testingModality" title="Please select testing modality" style="width:100%;">
                    <option value=""> -- Select-- </option>
                    <?php foreach ($testingFacility as $row) { ?>
                        <option value="<?php echo $row['testing_facility_type_id']; ?>"><?php echo ucwords($row['testing_facility_type_name']); ?></option>
                    <?php } ?>
                </select>
            </div>
            <div class="col-sm-2" style=" margin-top: 10px; ">
                <input type="text" class="form-control" id="hivRecencyTest" placeholder="Hiv Recency Test Date" name="hivRecencyTest" title="Please select HIV Recency Test Dates" style="width:100%;" readonly>
            </div>
            <?php if (isset($acl) && $acl->isAllowed($roleCode, 'Application\Controller\VlDataController', 'export-modality')) { ?>
                <div class="items-push col-lg-2" style=" margin-top: 10px; ">
                    <a href="javascript:void(0);" class="btn btn-hero-success" onclick="exportReport();"><i class="fa fa-fw fa-download"></i> Export Excel</a>
                </div>
            <?php } ?>
            <div class="items-push col-lg-2" style=" margin-top: 10px; ">
                <a href="javascript:void(0);" class="btn btn-hero-primary" onclick="getReport();"><i class="fa fa-fw fa-search"></i> Search</a>
            </div>
        </div>
    </div>
    <div class="block block-rounded block-bordered" id="setModality">
        <div class="block-header block-header-default">
            <span>RTRI Results</span>
        </div>
        <div class="block-content block-content-full">
            <table id="modalityRTRI" class="table table-bordered table-striped table-vcenter table-responsive frezz table-center">
                <tr>
                    <th align="center">AGE
                        <?php foreach ($ageArray as $age) {
                            echo '<th colspan="2" style="text-align:center;">' . $age;
                        } ?>
                <tr>
                    <th align="center">Gender
                        <?php foreach (range(1, 16) as $x) {
                            if ($x % 2) {
                                echo '<th align="center">Female';
                            } else {
                                echo '<th align="center">Male';
                            }
                        } ?>
                <tr>
                    <td align="center">Recent
                        <?php $index = 0;
                        foreach (range(1, 16) as $x) {
                            if ($x % 2) {
                                echo '<td align="right">' . $result['rtriRecent' . $ageArray[$index] . 'F'];
                            } else {
                                echo '<td align="right">' . $result['rtriRecent' . $ageArray[$index] . 'M'];
                                $index++;
                            }
                        } ?>
                <tr>
                    <td align="center">Long Term
                        <?php $index = 0;
                        foreach (range(1, 16) as $x) {
                            if ($x % 2) {
                                echo '<td align="right">' . $result['rtriLT' . $ageArray[$index] . 'F'];
                            } else {
                                echo '<td align="right">' . $result['rtriLT' . $ageArray[$index] . 'M'];
                                $index++;
                            }
                        } ?>
            </table>
        </div>
        <div class="block-header block-header-default">
            <span>Confirmed Results</span>
        </div>
        <div class="block-content block-content-full">
            <table id="modalityConfirm" class="table table-bordered table-striped table-vcenter table-responsive frezz table-center">
                <tr>
                    <th align="center">AGE
                        <?php foreach ($ageArray as $age) {
                            echo '<th colspan="2" style="text-align:center;">' . $age;
                        } ?>
                <tr>
                    <th align="center">Gender
                        <?php foreach (range(1, 16) as $x) {
                            if ($x % 2) {
                                echo '<th align="center">Female';
                            } else {
                                echo '<th align="center">Male';
                            }
                        } ?>
                <tr>
                    <td align="center">Recent
                        <?php $index = 0;
                        foreach (range(1, 16) as $x) {
                            if ($x % 2) {
                                echo '<td align="right">' . $result['confirmedRecent' . $ageArray[$index] . 'F'];
                            } else {
                                echo '<td align="right">' . $result['confirmedRecent' . $ageArray[$index] . 'M'];
                                $index++;
                            }
                        } ?>
                <tr>
                    <td align="center">Long Term
                        <?php $index = 0;
                        foreach (range(1, 16) as $x) {
                            if ($x % 2) {
                                echo '<td align="right">' . $result['confirmedLT' . $ageArray[$index] . 'F'];
                            } else {
                                echo '<td align="right">' . $result['confirmedLT' . $ageArray[$index] . 'M'];
                                $index++;
                            }
                        } ?>
            </table>
        </div>
    </div>
</div>

<script type="text/javascript">
    let searchExecuted = false;
    $(document).ready(function() {
        $('#page-container').removeClass('sidebar-o');
        <?php foreach ($globalConfigResult as $config) {
        ?>
            getLocationDeatils('<?php echo $config["global_name"]; ?>');
        <?php
            break;
        } ?>

        $('#sampleTestedDates').daterangepicker({
                format: 'DD-MMM-YYYY',
                autoUpdateInput: false,
                separator: ' to ',
                startDate: moment().subtract('days', 29),
                endDate: moment(),
                maxDate: moment(),
                ranges: {
                    'Today': [moment(), moment()],
                    'Yesterday': [moment().subtract('days', 1), moment().subtract('days', 1)],
                    'Last 7 Days': [moment().subtract('days', 6), moment()],
                    'Last 30 Days': [moment().subtract('days', 29), moment()],
                    'Last 60 Days': [moment().subtract('days', 59), moment()],
                    'Last 180 Days': [moment().subtract('days', 179), moment()],
                    'This Month': [moment().startOf('month'), moment().endOf('month')],
                    'Last Month': [moment().subtract('month', 1).startOf('month'), moment().subtract('month', 1).endOf('month')]
                }
            },
            function(start, end) {
                startDate = start.format('YYYY-MM-DD');
                endDate = end.format('YYYY-MM-DD');
                $('input[name="sampleTestedDates"]').on('apply.daterangepicker', function(ev, picker) {
                    $(this).val(picker.startDate.format('DD-MMM-YYYY') + ' to ' + picker.endDate.format('DD-MMM-YYYY'));
                });
            });
        $("#location_one").select2({
            placeholder: "Choose Province",
            allowClear: true,
        });
        $("#location_two").select2({
            placeholder: "Choose District",
            allowClear: true,
        });
        $("#location_three").select2({
            placeholder: "Choose City",
            allowClear: true,
        });
        $("#facilityId").select2({
            placeholder: "Choose Facility",
            allowClear: true,
        });
        $("#testingFacility").select2({
            placeholder: "Choose Testing Site",
            allowClear: true,
        });
        $("#testingModality").select2({
            placeholder: "Choose Testing Modality",
            allowClear: true,
        });
        $('#hivRecencyTest').daterangepicker({
                format: 'DD-MMM-YYYY',
                autoUpdateInput: false,
                separator: ' to ',
                startDate: moment().subtract('days', 29),
                endDate: moment(),
                maxDate: moment(),
                ranges: {
                    'Today': [moment(), moment()],
                    'Yesterday': [moment().subtract('days', 1), moment().subtract('days', 1)],
                    'Last 7 Days': [moment().subtract('days', 6), moment()],
                    'Last 30 Days': [moment().subtract('days', 29), moment()],
                    'Last 60 Days': [moment().subtract('days', 59), moment()],
                    'Last 180 Days': [moment().subtract('days', 179), moment()],
                    'This Month': [moment().startOf('month'), moment().endOf('month')],
                    'Last Month': [moment().subtract('month', 1).startOf('month'), moment().subtract('month', 1).endOf('month')]
                }
            },
            function(start, end) {
                startDate = start.format('YYYY-MM-DD');
                endDate = end.format('YYYY-MM-DD');
                $('input[name="hivRecencyTest"]').on('apply.daterangepicker', function(ev, picker) {
                    $(this).val(picker.startDate.format('DD-MMM-YYYY') + ' to ' + picker.endDate.format('DD-MMM-YYYY'));
                });

            });

        $("#advanceFilter input, #advanceFilter select").on("change", function() {
            searchExecuted = false;
        });
    });

    function searchData() {
        searchExecuted = true;
        //getFacilityListByLocation();
    }

    function getLocationDeatils(globalName) {
        var selectValue = document.getElementById(globalName).value;
        var innerId = '';
        var path = '';

        if (globalName == 'location_one' && selectValue == '') {
            path = 'get-province';
            innerId = 'location_one';
        } else if (globalName == 'location_one' && selectValue != '') {
            path = 'get-district';
            innerId = 'location_two';
            $("#location_three").html("<option value=''>-- Select --</option>");

        } else if (globalName == 'location_two' && selectValue != '') {
            path = 'get-city';
            innerId = 'location_three';
            if (selectValue == 'other') {
                $("#otherDistrictName").show();
                $("#otherDistrictName").addClass('isRequired');
            } else {
                $("#otherDistrictName").hide();
                $("#otherDistrictName").removeClass('isRequired');
            }
        } else if (globalName == 'location_three' && selectValue != '') {
            path = 'get-facility';
            if (selectValue == 'other') {
                $("#otherCityName").show();
                $("#otherCityName").addClass('isRequired');
            } else {
                $("#otherCityName").hide();
                $("#otherCityName").removeClass('isRequired');
            }
        }
        if (path != '') {
            $.blockUI();
            $.post("/common/" + path, {
                    selectValue: selectValue
                },
                function(data) {
                    if (globalName == 'location_one' && selectValue != '') {
                        var splitOption = data.split("##");
                        $("#" + innerId).html(splitOption[0]);
                        $("#facilityId").html(splitOption[1]);
                    } else if (globalName == 'location_two' && selectValue != '') {
                        var splitOption = data.split("##");
                        $("#" + innerId).html(splitOption[0]);
                        $("#facilityId").html(splitOption[1]);
                    } else if (globalName == 'location_three' && selectValue != '') {
                        $("#facilityId").html(data);
                    } else {
                        $("#" + innerId).html(data);
                    }
                    $.unblockUI();
                });
        }
    }

    /*function getFacilityListByLocation(globalName) {
        $.post("< ?php echo $this->url('facilities', array('action' => 'get-facility-by-location')); ?>", {
                locationOne: $("#location_one").val(),
                locationTwo: $("#location_two").val(),
                locationThree: $("#location_three").val(),
                hivRecencyTest: $("#hivRecencyTest").val(),
                globalName: globalName
            },
            function(data) {
                $("#facilityId").html('<option value="">-- Select --</option>' + data);
            });
    }*/

    function getReport() {
        $.blockUI();
        $.post("<?php echo $this->url('vl-data', array('action' => 'get-age-wise-infection-report')); ?>", {
            sampleTestedDates: $("#sampleTestedDates").val(),
            locationOne: $("#location_one").val(),
            locationTwo: $("#location_two").val(),
            locationThree: $("#location_three").val(),
            fName: $("#facilityId").val(),
            testingFacility: $("#testingFacility").val(),
            testingModality: $("#testingModality").val(),
            hivRecencyTest: $("#hivRecencyTest").val()
        }, function(data) {
            $('#setModality').html(data);
            $.unblockUI();
        });
    }

    function exportReport() {
        if (searchExecuted === false) {
            searchData();
        }
        $.blockUI();
        $.post("<?php echo $this->url('vl-data', array('action' => 'export-modality')); ?>", {
            sampleTestedDates: $("#sampleTestedDates").val(),
            locationOne: $("#location_one").val(),
            locationTwo: $("#location_two").val(),
            locationThree: $("#location_three").val(),
            fName: $("#facilityId").val(),
            testingFacility: $("#testingFacility").val(),
            testingModality: $("#testingModality").val()
        }, function(data) {
            if (data == "" || data == null || data == undefined) {
                $.unblockUI();
                alert('Unable to generate download');
            } else {
                $.unblockUI();
                document.location.href = '/temporary/' + data;
            }
        });
    }
</script>