<?php
$common = new \Application\Service\CommonService();
?>
<hr/>
<a href="javascript:void(0)" class="btn btn-info saveResult"  onclick="updateVlResult();">Save Result</a>
<br/><br/>
<table class="table table-bordered table-striped table-vcenter" id="sampleData">
<thead>
                        <tr>
    <th>Sample ID</th><th>Patient ID</th><th>Recency Date</th><th>Viral Load Result</th><th>Recency Outcome</th><th>Final outcome</th><th>Action</th>
</tr>
</thead>
<?php
if(count($result)>0){
    foreach($result as $sample){
    ?>
    <tr>
        <td><?php echo $sample['sample_id'];?></td>
        <td><?php echo $sample['patient_id'];?></td>
        <td><?php echo $common->humanDateFormat($sample['hiv_recency_date']);?></td>
        <td>
        <?php
        if($sample['term_outcome']!='' && $sample['term_outcome']=='Long Term' && $sample['final_outcome']=='Long Term'){
        }else if($sample['term_outcome']!=''){
            if($sample['vl_result']==''){ ?>
                <input type="text" class="form-control vlResultData" data-term-outcome = "<?php echo $sample['term_outcome'];?>" name="vlResult[]" id="<?php echo $sample['recency_id'];?>" value="<?php echo $sample['vl_result'];?>" onchange="getVlResult();"/>
            <?php }else{ ?>
        <span id="span<?php echo $sample['recency_id'];?>"><?php echo $sample['vl_result'];?></span>
        <input style="display:none;" type="text" class="form-control vlResultData" data-term-outcome = "<?php echo $sample['term_outcome'];?>" name="vlResult[]" id="<?php echo $sample['recency_id'];?>" value="<?php echo $sample['vl_result'];?>" onchange="getVlResult();"/>
            <?php }
         } ?>
        </td>
        <td><?php echo $sample['term_outcome'];?></td>
        <td><?php echo $sample['final_outcome'];?></td>
        <td>
        <?php
        if($sample['vl_result']!=''){
            ?>
                <a href="javascript:void(0);" class="btn btn-info btn-sm" onclick="editVlResult('<?php echo $sample['recency_id'];?>');"> <i class="fa fa-edit"></i> Edit</a>
            <?php
        }
        ?>
        </td>
    </tr>
    <?php
    }
}else{
    ?>
    <tr>
    <td colspan="2">No data available</td>
</tr>
    <?php
}
?>
</table>
<br/>
<a href="javascript:void(0)" class="btn btn-info saveResult" onclick="updateVlResult();">Save Result</a>
<br/><br/>
<script>
$(document).ready(function(){
    $('#sampleData').dataTable({"ordering": false});
});
</script>
