<?php
$common = new \Application\Service\CommonService();
?>
<hr/>
<a href="javascript:void(0)" class="btn btn-info saveResult"  onclick="updateVlResult();">Save Result</a>
<br/><br/>
<table class="table table-bordered table-striped table-vcenter" id="sampleData">
<thead>
                        <tr>
    <th>Sample ID</th><th>Patient ID</th><th>Recency Date</th><th>Viral Load Result Date</th><th>Viral Load Result</th><th>Recency Outcome</th><th>Final outcome</th><th>Action</th>
</tr>
</thead>
<?php
if(count($result)>0){
    foreach($result as $key=>$sample){
    ?>
    <tr>
        <td><?php echo $sample['sample_id'];?></td>
        <td><?php echo $sample['patient_id'];?></td>
        <td><?php echo $common->humanDateFormat($sample['hiv_recency_date']);?></td>
        <td>
        <?php if($sample['final_outcome'] ==''){
            if($sample['vl_test_date']==''){ ?>
                <input type="text" class="js-datepicker form-control" id="vlTestDate<?php echo $sample['recency_id'];?>" name="vlTestDate[]" data-week-start="1" data-autoclose="true" data-today-highlight="true" data-date-format="dd-M-yyyy" title="Please enter the vl test date" readonly="readonly">
            <?php }else{ ?>
                <span id="vlDateSpan<?php echo $sample['recency_id'];?>"><?php echo $common->humanDateFormat($sample['vl_test_date']);?></span>
                <input style="display:none;" type="text" value="<?php echo $common->humanDateFormat($sample['vl_test_date']);?>" class="js-datepicker form-control" id="vlTestDate<?php echo $sample['recency_id'];?>" name="vlTestDate[]" data-week-start="1" data-autoclose="true" data-today-highlight="true" data-date-format="dd-M-yyyy" title="Please enter the vl test date" readonly="readonly">
            <?php }
         }else{
            if($sample['vl_test_date']!=''){ ?>
                <input type="hidden" class="js-datepicker form-control" id="vlTestDate<?php echo $sample['recency_id'];?>" name="vlTestDate[]" data-week-start="1" data-autoclose="true" data-today-highlight="true" data-date-format="dd-M-yyyy" value="<?php echo $common->humanDateFormat($sample['vl_test_date']);?>" title="Please enter the vl test date">
                <span id="vlDateSpan<?php echo $sample['recency_id'];?>"><?php echo $common->humanDateFormat($sample['vl_test_date']);?></span>
            <?php }
         } ?>
        </td>
        <td>
        <?php if($sample['final_outcome'] ==''){
            if($sample['vl_result']==''){ ?>
                <input type="text" class="form-control vlResultData" data-term-outcome = "<?php echo $sample['term_outcome'];?>" name="vlResult[]" id="<?php echo $sample['recency_id'];?>" value="<?php echo $sample['vl_result'];?>" onchange="getVlResult();"/>
            <?php }else{ ?>
                <span id="span<?php echo $sample['recency_id'];?>"><?php echo $sample['vl_result'];?></span>
                <input style="display:none;" type="text" class="form-control vlResultData" data-term-outcome = "<?php echo $sample['term_outcome'];?>" name="vlResult[]" id="<?php echo $sample['recency_id'];?>" value="<?php echo $sample['vl_result'];?>" onchange="getVlResult();"/>
            <?php }
         }else{
            if($sample['vl_result']!=''){ ?>
                <span id="span<?php echo $sample['recency_id'];?>"><?php echo $sample['vl_result'];?></span>
                <input style="display:none;" type="text" class="form-control vlResultData" data-term-outcome = "<?php echo $sample['term_outcome'];?>" name="vlResult[]" id="<?php echo $sample['recency_id'];?>" value="<?php echo $sample['vl_result'];?>" onchange="getVlResult();"/>
            <?php }
         } ?>
        <!-- < ?php
        if($sample['term_outcome']!='' && $sample['term_outcome']=='Long Term' && $sample['final_outcome']=='Long Term'){
        }else if($sample['term_outcome']!=''){
            if($sample['vl_result']==''){ ?>
            < ?php }else{ ?>
            < ?php }
         } ?> -->
        </td>
        <td><?php echo $sample['term_outcome'];?></td>
        <td><?php echo $sample['final_outcome'];?></td>
        <td>
        <?php
        if($sample['vl_result']!=''){
            ?>
                <a href="javascript:void(0);" class="btn btn-info btn-sm" onclick="editVlResult('<?php echo $sample['recency_id'];?>');"> <i class="fa fa-edit"></i> Edit</a>
            <?php
        }
        ?>
        </td>
    </tr>
    <?php
    }
}else{
    ?>
    <tr>
    <td colspan="8" class="dataTables_empty">No data available</td>
</tr>
    <?php
}
?>
</table>
<br/>
<a href="javascript:void(0)" class="btn btn-info saveResult" onclick="updateVlResult();">Save Result</a>
<br/><br/>
<script>

    $(function() {
        $( ".js-datepicker" ).datepicker({ 
          dateFormat: "yyyy-mm-dd",
        });
    }); 
    $(document).ready(function(){
        $('#sampleData').dataTable({"ordering": false});
    });
</script>
