<?php

use Laminas\Session\Container;

$sessionLogin = new Container('credo');
$roleCode = $sessionLogin->roleCode;
$acl=$this->layout()->acl;
if (isset($acl) && $acl->isAllowed($roleCode, 'Application\Controller\Recency', 'generate-pdf')) {
    $editAction = '{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center",bSortable:false}';
}else{
    $editAction = '{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"}';
}
?>
<link rel="stylesheet" href="<?php echo $this->basePath() . '/assets/plugins/datepicker/daterangepicker.css' ?>" rel="stylesheet">
<div class="bg-body-light">
    <div class="content content-full">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
            <h1 class="flex-sm-fill font-size-h2 font-w400 mt-2 mb-0 mb-sm-2">Long Term Infection</h1>
        </div>
    </div>
</div>
<div class="content">
    <div class="block block-rounded block-bordered">
        <div class="block-header block-header-default"></div>

        <div class="block-content block-content-full">
            <div class="form-group row">
                <?php
                foreach ($globalConfigResult as $config) { ?>
                    <?php if ($config['global_name'] == 'location_one' || $config['global_name'] == 'location_two' || $config['global_name'] == 'location_three') { ?>
                        <label style=" margin-bottom: 2.5%; " class="col-sm-2 col-form-label" for=""><?php echo ucfirst($config['global_value']); ?></label>
                        <div class="col-sm-4">
                            <select class="form-control" id="<?php echo $config['global_name']; ?>" name="<?php echo $config['global_name']; ?>" title="Please enter the <?php echo lcfirst($config['global_value']); ?>" onchange="getLocationDeatils('<?php echo $config["global_name"]; ?>');">
                                <option value="">-- Select --</option>
                            </select>
                        </div>
                <?php
                    }
                } ?>
                <label style=" margin-bottom: 2.5%; " class="col-sm-2 col-form-label" for="">Facility</label>
                <div class="col-sm-4">
                    <select class="form-control" id="facilityId" name="facilityId" title="Please choose facility">
                        <option value="">-- Select --</option>
                    </select>
                </div>
                <label style=" margin-bottom: 2.5%; " class="col-sm-2 col-form-label" for="">Testing Site</label>
                <div class="col-sm-4">
                    <select class="form-control" id="testingFacility" name="testingFacility" title="Please select testing facility name" style="width:100%;">
                        <option value=""> -- Select -- </option>
                        <?php foreach ($facilityResult['facilityTest'] as $facilityRow) {
                            // if (2 != (int)$facilityRow['facility_type_id']) continue; 
                        ?>
                            <option value="<?php echo $facilityRow['facility_id']; ?>"><?php echo ucwords($facilityRow['facility_name']); ?></option>
                        <?php } ?>
                    </select>
                </div>
                <label style=" margin-bottom: 2.5%; " class="col-sm-2 col-form-label" for="hivRecencyTest">HIV Recency Test Dates:</label>
                <div class="col-sm-4">
                    <input type="text" class="form-control" id="hivRecencyTest" placeholder="Hiv Recency Test Date" name="hivRecencyTest" title="Please select HIV Recency Test Dates" style="width:100%;" readonly>
                </div>
            </div>
            <div class="row items-push">
                <div class="col-lg-7 ">
                    <a href="javascript:void(0);" class="btn btn-primary" onclick="searchData();"><i class="fa fa-fw fa-check"></i> Search</a>
                    <?php if (isset($acl) && $acl->isAllowed($roleCode, 'Application\Controller\VlData', 'export-long-term-infected-data')) { ?>
                        <a href="javascript:void(0);" class="btn btn-success" onclick="exportRecentLTermInfection();"><i class="fa fa-download"></i>&nbsp;Export Excel</a>
                    <?php
                    } ?>
                </div>
            </div>
            <table id="ltInfectionTable" class="table-responsive table table-bordered table-striped table-vcenter">
                <thead>
                    <tr>
                        <th>Sample ID</th>
                        <th>Facility Name</th>
                        <th>Date Of Testing</th>
                        <th>Control Line</th>
                        <th>Verification Line</th>
                        <th>Long Term Line</th>
                        <th>Assay Test Result</th>
                        <th>VL Result</th>
                        <th>Final Result</th>
                        <th>Gender</th>
                        <th>Age</th>
                        <th>Testing Site</th>
                        <th>VL Test Date</th>
                        <?php if (isset($acl) && $acl->isAllowed($roleCode, 'Application\Controller\Recency', 'generate-pdf')) { ?>
                        <th>Action</th>
                        <?php } ?>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td colspan='14' class='dataTables_empty'>Loading data from server</td>
                    </tr>
                </tbody>
                <tfoot>
                    <tr>
                        <th>Sample ID</th>
                        <th>Facility Name</th>
                        <th>Date Of Testing</th>
                        <th>Control Line</th>
                        <th>Verification Line</th>
                        <th>Long Term Line</th>
                        <th>Assay Test Result</th>
                        <th>VL Result</th>
                        <th>Final Result</th>
                        <th>Gender</th>
                        <th>Age</th>
                        <th>Testing Site</th>
                        <th>VL Test Date</th>
                        <?php if (isset($acl) && $acl->isAllowed($roleCode, 'Application\Controller\Recency', 'generate-pdf')) { ?>
                        <th>Action</th>
                        <?php } ?>

                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>

<script type="text/javascript">
    let searchExecuted = false;
    /* Table initialisation */
    oTable = null;
    $(document).ready(function() {

        $("#facilityId").select2({
            placeholder: "Choose Facility",
            width: "290px",
            allowClear: true,
        });
        $("#testingFacility").select2({
            placeholder: "Choose Testing Site",
            width: "290px",
            allowClear: true,
        });
        oTable = $('#ltInfectionTable').dataTable({
            "bAutoWidth": false,
            "bProcessing": true,
            "bServerSide": true,
            "aoColumns": [
                <?php echo $editAction; ?>
            ],
            "sAjaxSource": "<?php echo $this->url('vl-data', array('action' => 'lt-infection')); ?>",
            "fnServerData": function(sSource, aoData, fnCallback) {
                aoData.push({
                    "name": "fName",
                    "value": $("#facilityId").val()
                });
                aoData.push({
                    "name": "locationOne",
                    "value": $("#location_one").val()
                });
                aoData.push({
                    "name": "locationTwo",
                    "value": $("#location_two").val()
                });
                aoData.push({
                    "name": "locationThree",
                    "value": $("#location_three").val()
                });
                aoData.push({
                    "name": "testingFacility",
                    "value": $("#testingFacility").val()
                });

                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
                });
            }

        });

        <?php foreach ($globalConfigResult as $config) {
        ?>
            getLocationDeatils('<?php echo $config["global_name"]; ?>');
        <?php
            break;
        } ?>

        $('#hivRecencyTest').daterangepicker({
                format: 'DD-MMM-YYYY',
                autoUpdateInput: false,
                separator: ' to ',
                startDate: moment().subtract('days', 29),
                endDate: moment(),
                maxDate: moment(),
                ranges: {
                    'Today': [moment(), moment()],
                    'Yesterday': [moment().subtract('days', 1), moment().subtract('days', 1)],
                    'Last 7 Days': [moment().subtract('days', 6), moment()],
                    'Last 30 Days': [moment().subtract('days', 29), moment()],
                    'Last 60 Days': [moment().subtract('days', 59), moment()],
                    'Last 180 Days': [moment().subtract('days', 179), moment()],
                    'This Month': [moment().startOf('month'), moment().endOf('month')],
                    'Last Month': [moment().subtract('month', 1).startOf('month'), moment().subtract('month', 1).endOf('month')]
                }
            },
            function(start, end) {
                startDate = start.format('YYYY-MM-DD');
                endDate = end.format('YYYY-MM-DD');
                $('input[name="hivRecencyTest"]').on('apply.daterangepicker', function(ev, picker) {
                    $(this).val(picker.startDate.format('DD-MMM-YYYY') + ' to ' + picker.endDate.format('DD-MMM-YYYY'));
                });

            });

        $("#advanceFilter input, #advanceFilter select").on("change", function() {
            searchExecuted = false;
        });
    });

    function searchData() {
        searchExecuted = true;
        $.blockUI();
        oTable.fnDraw();
        $.unblockUI();
    }

    function exportRecencyData() {
        if (searchExecuted === false) {
            searchData();
        }
        $.blockUI();
        $.post("<?php echo $this->url('recency', array('action' => 'export-recency')); ?>",
            function(data) {
                if (data == "" || data == null || data == undefined) {
                    $.unblockUI();
                    alert('Unable to generate download');
                } else {
                    $.unblockUI();
                    document.location.href = '/temporary/' + data;
                }
            });
    }

    /*function getLocationDeatils(globalName, nxtGlobalName) {
        var selectValue = document.getElementById(globalName).value;
        var innerId = '';
        var path = '';
        if (globalName == 'location_one' && selectValue == '') {
            path = 'get-province';
            innerId = 'location_one';
        } else if (globalName == 'location_one' && selectValue != '') {
            path = 'get-district';
            innerId = 'location_two';
            $("#location_three").html("<option value=''>-- Select --</option>");
        } else if (globalName == 'location_two' && selectValue != '') {
            path = 'get-city';
            innerId = 'location_three';
        } else if (globalName == 'location_three' || globalName == 'location_two') {
            getFacilityListByLocation(globalName);
        }
        if (path != '') {
            $.blockUI();
            $.post("/common/" + path, {
                    selectValue: selectValue
                },
                function(data) {
                    $("#" + innerId).html(data);
                    getFacilityListByLocation(globalName);
                    $.unblockUI();
                });
        }
    }*/

    function getLocationDeatils(globalName) {
        var selectValue = document.getElementById(globalName).value;
        var innerId = '';
        var path = '';

        if (globalName == 'location_one' && selectValue == '') {
            path = 'get-province';
            innerId = 'location_one';
        } else if (globalName == 'location_one' && selectValue != '') {
            path = 'get-district';
            innerId = 'location_two';
            $("#location_three").html("<option value=''>-- Select --</option>");

        } else if (globalName == 'location_two' && selectValue != '') {
            path = 'get-city';
            innerId = 'location_three';
            if (selectValue == 'other') {
                $("#otherDistrictName").show();
                $("#otherDistrictName").addClass('isRequired');
            } else {
                $("#otherDistrictName").hide();
                $("#otherDistrictName").removeClass('isRequired');
            }
        } else if (globalName == 'location_three' && selectValue != '') {
            path = 'get-facility';
            if (selectValue == 'other') {
                $("#otherCityName").show();
                $("#otherCityName").addClass('isRequired');
            } else {
                $("#otherCityName").hide();
                $("#otherCityName").removeClass('isRequired');
            }
        }
        if (path != '') {
            $.blockUI();
            $.post("/common/" + path, {
                    selectValue: selectValue
                },
                function(data) {
                    if (globalName == 'location_one' && selectValue != '') {
                        var splitOption = data.split("##");
                        $("#" + innerId).html(splitOption[0]);
                        $("#facilityId").html(splitOption[1]);
                    } else if (globalName == 'location_two' && selectValue != '') {
                        var splitOption = data.split("##");
                        $("#" + innerId).html(splitOption[0]);
                        $("#facilityId").html(splitOption[1]);
                    } else if (globalName == 'location_three' && selectValue != '') {
                        $("#facilityId").html(data);
                    } else {
                        $("#" + innerId).html(data);
                    }
                    $.unblockUI();
                });
        }
    }

    function getFacilityListByLocation(globalName) {
        $.blockUI();
        $.post("<?php echo $this->url('facilities', array('action' => 'get-facility-by-location')); ?>", {
                locationOne: $("#location_one").val(),
                locationTwo: $("#location_two").val(),
                locationThree: $("#location_three").val(),
                globalName: globalName
            },
            function(data) {
                $("#facilityId").html('<option value="">-- Select --</option>' + data);
                $.unblockUI();
            });
    }

    function exportRecentLTermInfection() {
        $.blockUI();
        $.post("<?php echo $this->url('vl-data', array('action' => 'export-long-term-infected-data')); ?>",
            function(data) {
                if (data == "" || data == null || data == undefined) {
                    $.unblockUI();
                    alert('Unable to generate download');
                } else {
                    $.unblockUI();
                    document.location.href = '/temporary/' + data;
                }
            });
    }

    function generateLTermPdf(recencyId) {
        console.log(recencyId);
        $.blockUI();
        $.post("<?php echo $this->url('recency', array('action' => 'generate-pdf')); ?>", {
                recencyId: recencyId
            },
            function(data) {
                if (data == "" || data == null || data == undefined) {
                    $.unblockUI();
                    alert('Unable to generate download');
                } else {
                    $.unblockUI();
                    window.open('/temporary/' + data, 'blank');
                    //document.location.href = '/temporary/'+data;
                }
            });
    }
</script>