<?php

use Laminas\Session\Container;

$alertContainer = new Container('alert');
$sessionLogin = new Container('credo');
$crossLoginSession = new Container('crossLogin');
// \Zend\Debug\Debug::dump($crossLoginSession->logged);
$role = $sessionLogin->roleId;
$roleCode = $sessionLogin->roleCode;
$userName = $sessionLogin->userName;
$nonRemoteUserMsg = $sessionLogin->nonRemoteUserMsg;
$acl = $this->layout()->acl;
$GlobalConfigRes = $this->GlobalConfig();
/* Crosss Login Block Start */
$userCrossLoginRes = $this->UserCrossLogin();
$configResult = $this->CustomConfig();
/* Crosss Login Block End */
$dashboardMenu = "";
if (isset($acl) && $acl->isAllowed($roleCode, 'Application\Controller\IndexController', 'index')) {
     $dashboardMenu .= "<li id='nav-main-item'><a id='lab-dashboard' class='nav-main-link' href='/'><span class='nav-main-link-name'>Laboratory</span></a></li>";
}
if (isset($acl) && $acl->isAllowed($roleCode, 'Application\Controller\IndexController', 'analysis-dashboard')) {
     $dashboardMenu .= "<li id='nav-main-item'><a id='analysis-dashboard' class='nav-main-link' href=" . $this->url('analysis-dashboard') . "><span class='nav-main-link-name'>Analysis</span></a></li>";
}
if (isset($acl) && $acl->isAllowed($roleCode, 'Application\Controller\IndexController', 'quality-control-dashboard')) {
     $dashboardMenu .= "<li id='nav-main-item'><a id='quality-control-dashboard' class='nav-main-link' href=" . $this->url('quality-control-dashboard') . "><span class='nav-main-link-name'>Quality Control</span></a></li>";
}

$userMenu = "";
if (isset($acl) && $acl->isAllowed($roleCode, 'Application\Controller\GlobalConfigController', 'index')) {
     $userMenu .= "<li id='nav-main-item'><a id='global-config' class='nav-main-link' href=" . $this->url('global-config', array('action' => 'index')) . "><span class='nav-main-link-name'>Global Config</span></a></li>";
}
if (isset($acl) && $acl->isAllowed($roleCode, 'Application\Controller\RolesController', 'index')) {
     $userMenu .= "<li id='nav-main-item'><a id='role' class='nav-main-link' href=" . $this->url('roles', array('action' => 'index')) . "><span class='nav-main-link-name'>Roles</span></a></li>";
}
if (isset($acl) && $acl->isAllowed($roleCode, 'Application\Controller\UserController', 'index')) {
     $userMenu .= "<li id='nav-main-item'><a id='user' class='nav-main-link' href=" . $this->url('user', array('action' => 'index')) . "><span class='nav-main-link-name'>User</span></a></li>";
}
if (isset($acl) && $acl->isAllowed($roleCode, 'Application\Controller\FacilitiesController', 'index')) {
     $userMenu .= "<li id='nav-main-item'><a id='facilities' class='nav-main-link' href=" . $this->url('facilities', array('action' => 'index')) . "><span class='nav-main-link-name'>Facilities</span></a></li>";
}
if (isset($acl) && $acl->isAllowed($roleCode, 'Application\Controller\ProvinceController', 'index')) {
     $userMenu .= "<li id='nav-main-item'><a id='province' class='nav-main-link' href=" . $this->url('province', array('action' => 'index')) . "><span class='nav-main-link-name'>" . $GlobalConfigRes[0]['global_value'] . "</span></a></li>";
}
if (isset($acl) && $acl->isAllowed($roleCode, 'Application\Controller\DistrictController', 'index')) {
     $userMenu .= "<li id='nav-main-item'><a id='district' class='nav-main-link' href=" . $this->url('district', array('action' => 'index')) . "><span class='nav-main-link-name'>" . $GlobalConfigRes[1]['global_value'] . "</span></a></li>";
}
if (isset($acl) && $acl->isAllowed($roleCode, 'Application\Controller\CityController', 'index')) {
     $userMenu .= "<li id='nav-main-item'><a id='city' class='nav-main-link' href=" . $this->url('city', array('action' => 'index')) . "><span class='nav-main-link-name'>" . $GlobalConfigRes[2]['global_value'] . "</span></a></li>";
}

$recencyMenu = "";
if (isset($acl) && $acl->isAllowed($roleCode, 'Application\Controller\RecencyController', 'index')) {
     $recencyMenu .= "<li id='nav-main-item'><a id='recency' class='nav-main-link' href=" . $this->url('recency', array('action' => 'index')) . "><span class='nav-main-link-name'><i class='nav-main-link-icon si si-notebook'></i> All Data</span></a></li>";
}

if (isset($acl) && $acl->isAllowed($roleCode, 'Application\Controller\PrintResultsController', 'index')) {
     $recencyMenu .= "<li id='nav-main-item'><a id='print-results' class='nav-main-link' href=" . $this->url('print-results', array('action' => 'index')) . "><span class='nav-main-link-name'><i class='nav-main-link-icon si si-printer'></i> Print Results</span></a></li>";
}
if (isset($acl) && $acl->isAllowed($roleCode, 'Application\Controller\ManifestsController', 'index')) {
     $recencyMenu .= "<li id='nav-main-item'><a id='manifests' class='nav-main-link' href=" . $this->url('manifests', array('action' => 'index')) . "><span class='nav-main-link-name'><i class='nav-main-link-icon si si-film'></i> Specimen Manifests</span></a></li>";
}



$settingsMenu = "";
if (isset($acl) && $acl->isAllowed($roleCode, 'Application\Controller\SettingsController', 'index')) {
     $settingsMenu .= "<li id='nav-main-item'><a id='settings' class='nav-main-link' href=" . $this->url('settings', array('action' => 'index')) . "><span class='nav-main-link-name'><i class='nav-main-link-icon si si-wrench'></i> Settings</span></a></li>";
}


$qcMenu = "";
if (isset($acl) && $acl->isAllowed($roleCode, 'Application\Controller\QualityCheckController', 'index')) {
     $qcMenu = "<li id='nav-main-item'><a id='quality-check' class='nav-main-link' href=" . $this->url('quality-check', array('action' => 'index')) . "><span class='nav-main-link-name'><i class='nav-main-link-icon si si-settings'></i> Quality Check Testing</span></a></li>";
}
$vlDataMenu = "";
if (isset($acl) && $acl->isAllowed($roleCode, 'Application\Controller\VlDataController', 'index')) {
     $vlDataMenu = "<li id='nav-main-item'><a id='vl-data' class='nav-main-link' href=" . $this->url('vl-data', array('action' => 'index')) . "><span class='nav-main-link-name'><i class='nav-main-link-icon si si-notebook'></i> All Pending Results</span></a></li>";
}
$reportMenu = "";
if (isset($acl) && $acl->isAllowed($roleCode, 'Application\Controller\VlDataController', 'recent-infection')) {
     $reportMenu .= "<li id='nav-main-item'><a id='recent-infection' class='nav-main-link' href=" . $this->url('vl-data', array('action' => 'recent-infection')) . "><span class='nav-main-link-name'><i class='nav-main-link-icon si si-notebook'></i> All Recent Infections</span></a></li>";
}
if (isset($acl) && $acl->isAllowed($roleCode, 'Application\Controller\VlDataController', 'lt-infection')) {
     $reportMenu .= "<li id='nav-main-item'><a id='lt-infection' class='nav-main-link' href=" . $this->url('vl-data', array('action' => 'lt-infection')) . "><span class='nav-main-link-name'><i class='nav-main-link-icon si si-notebook'></i> All Long Term Infections</span></a></li>";
}
if (isset($acl) && $acl->isAllowed($roleCode, 'Application\Controller\VlDataController', 'tat-report')) {
     $reportMenu .= "<li id='nav-main-item'><a id='tat-report' class='nav-main-link' href=" . $this->url('vl-data', array('action' => 'tat-report')) . "><span class='nav-main-link-name'><i class='nav-main-link-icon si si-notebook'></i> TAT Report</span></a></li>";
}
if (isset($acl) && $acl->isAllowed($roleCode, 'Application\Controller\VlDataController', 'weekly-report')) {
     $reportMenu .= "<li id='nav-main-item'><a id='weekly-report' class='nav-main-link' href=" . $this->url('vl-data', array('action' => 'weekly-report')) . "><span class='nav-main-link-name'><i class='nav-main-link-icon si si-notebook'></i> Weekly Report</span></a></li>";
}
if (isset($acl) && $acl->isAllowed($roleCode, 'Application\Controller\VlDataController', 'qc-report')) {
     $reportMenu .= "<li id='nav-main-item'><a id='qc-report' class='nav-main-link' href=" . $this->url('vl-data', array('action' => 'qc-report')) . "><span class='nav-main-link-name'><i class='nav-main-link-icon si si-notebook'></i> QC Report</span></a></li>";
}
if (isset($acl) && $acl->isAllowed($roleCode, 'Application\Controller\VlDataController', 'age-wise-infection-report')) {
     $reportMenu .= "<li id='nav-main-item'><a id='age-wise-infection-report' class='nav-main-link' href=" . $this->url('vl-data', array('action' => 'age-wise-infection-report')) . "><span class='nav-main-link-name'><i class='nav-main-link-icon si si-notebook'></i> Age-wise Infection Report</span></a></li>";
}

$emailMenu = "";
if (isset($acl) && $acl->isAllowed($roleCode, 'Application\Controller\VlDataController', 'email-result')) {
     $emailMenu = "<li id='nav-main-item'><a id='email-result' class='nav-main-link' href=" . $this->url('vl-data', array('action' => 'email-result')) . "><span class='nav-main-link-name'><i class='nav-main-link-icon si si-docs'></i> Email Results</span></a></li>";
}

$recentMenu = "";
if (isset($acl) && $acl->isAllowed($roleCode, 'Application\Controller\VlDataController', 'recent-infection')) {
     $recentMenu = "<li id='nav-main-item'><a id='recent-infection' class='nav-main-link' href=" . $this->url('vl-data', array('action' => 'recent-infection')) . "><span class='nav-main-link-name'><i class='nav-main-link-icon si si-notebook'></i> Recent Infections Report</span></a></li>";
}
$monitoringMenu = "";
if (isset($acl) && $acl->isAllowed($roleCode, 'Application\Controller\MonitoringController', 'all-user-login-history')) {
     $monitoringMenu .= "<li id='nav-main-item'><a id='user-login-history' class='nav-main-link' href=" . $this->url('monitoring', array('action' => 'all-user-login-history')) . "><span class='nav-main-link-name'><i class='nav-main-link-icon si si-notebook'></i> User Login History</span></a></li>";
}
if (isset($acl) && $acl->isAllowed($roleCode, 'Application\Controller\MonitoringController', 'audit-trail')) {
     $monitoringMenu .= "<li id='nav-main-item'><a id='audit-trail' class='nav-main-link' href=" . $this->url('monitoring', array('action' => 'audit-trail')) . "><span class='nav-main-link-name'><i class='nav-main-link-icon si si-clock'></i> Audit Trail</span></a></li>";
}
if (isset($acl) && $acl->isAllowed($roleCode, 'Application\Controller\MonitoringController', 'user-activity-log')) {
     $monitoringMenu .= "<li id='nav-main-item'><a id='audit-trail' class='nav-main-link' href=" . $this->url('monitoring', array('action' => 'user-activity-log')) . "><span class='nav-main-link-name'><i class='nav-main-link-icon si si-list'></i> User Activity Log</span></a></li>";
}
// $uploadResultMenu = "";
// $uploadResultMenu="<li id='nav-main-item'><a id='upload-result' class='nav-main-link' href=". $this->url('vl-data', array('action' => 'upload-result')) ."><span class='nav-main-link-name'><i class='nav-main-link-icon si si-notebook'></i> Upload Results</span></a></li>";

?>

<!doctype html>
<html lang="en">

<head>
     <meta charset="utf-8">
     <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">


     <title>Recency Management</title>

     <link rel="shortcut icon" href="<?php echo $this->basePath() . '/assets/media/favicons/favicon.png'; ?>">



     <link rel="icon" type="image/png" sizes="192x192" href="<?php echo $this->basePath() . '/assets/media/favicons/favicon-192x192.png'; ?>">
     <link rel="apple-touch-icon" sizes="180x180" href="<?php echo $this->basePath() . '/assets/media/favicons/apple-touch-icon-180x180.png'; ?>">

     <style>
          .mandatory {
               color: red;
          }

          .not-mandatory {
               color: #FFFFFF;
          }
     </style>
     <!-- Stylesheets -->
     <!-- Fonts and Dashmix framework -->

     <!-- vivek 25th Oct-->
     <!-- <link href="http://code.jquery.com/ui/1.10.2/themes/smoothness/jquery-ui.css" rel="Stylesheet"></link> -->


     <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito+Sans:300,400,400i,600,700">
     <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

     <link rel="stylesheet" href="<?php echo $this->basePath() . '/assets/css/dashmix.min.css' ?>" rel="stylesheet">
     <link rel="stylesheet" href="<?php echo $this->basePath() . '/assets/css/alert.css' ?>" rel="stylesheet">
     <link rel="stylesheet" href="<?php echo $this->basePath() . '/assets/js/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.min.css' ?>" rel="stylesheet">


     <!-- vivek -->
     <link rel="stylesheet" href="<?php echo $this->basePath() . '/assets/js/plugins/select2/css/select2.min.css' ?>">
     <link rel="stylesheet" href="<?php echo $this->basePath() . '/assets/css/select2.css' ?>">

     <link rel="stylesheet" href="<?php echo $this->basePath() . '/assets/js/plugins/datatables/dataTables.bootstrap4.css' ?>" rel="stylesheet">
     <link rel="stylesheet" href="<?php echo $this->basePath() . '/assets/js/plugins/datatables/buttons-bs4/buttons.bootstrap4.min.css' ?>" rel="stylesheet">
</head>

<body>
     <!-- Page Container -->
     <div id="page-container" class="sidebar-o sidebar-mini enable-page-overlay side-scroll page-header-fixed page-header-dark main-content-narrow">

          <!-- sidebar-o enable-page-overlay side-scroll page-header-fixed page-header-dark main-content-narrow -->

          <!-- Side Overlay-->
          <aside id="side-overlay">
               <!-- Side Header -->
               <div class="bg-image" style="background-image: url('<?php echo $this->basePath() . '/assets/media/various/bg_side_overlay_header.jpg'; ?>');">
                    <div class="bg-primary-op">
                         <div class="content-header">
                              <!-- User Avatar -->
                              <a class="img-link mr-1" href="be_pages_generic_profile.html">
                                   <img class="img-avatar img-avatar48" src="<?php echo $this->basePath() . '/assets/media/avatars/avatar10.jpg'; ?>" alt="">
                              </a>
                              <!-- END User Avatar -->

                              <!-- User Info -->
                              <div class="ml-2">
                                   <a class="text-white font-w600" href="#"></a>
                                   <div class="text-white-75 font-size-sm font-italic"></div>
                              </div>
                              <!-- END User Info -->

                              <!-- Close Side Overlay -->
                              <!-- Layout API, functionality initialized in Template._uiApiLayout() -->
                              <a class="ml-auto text-white" href="javascript:void(0)" data-toggle="layout" data-action="side_overlay_close">
                                   <i class="fa fa-times-circle"></i>
                              </a>
                              <!-- END Close Side Overlay -->
                         </div>
                    </div>
               </div>
               <!-- END Side Header -->
          </aside>
          <!-- END Side Overlay -->



          <nav id="sidebar" aria-label="Main Navigation" data-simplebar="init">
               <div class="simplebar-track vertical" style="visibility: hidden;">
                    <div class="simplebar-scrollbar" style="visibility: visible; top: 0px; height: 358px;">
                    </div>
               </div>
               <div class="simplebar-track horizontal" style="visibility: hidden;">
                    <div class="simplebar-scrollbar" style="visibility: visible; left: 0px; width: 138px;">
                    </div>
               </div>
               <div class="simplebar-scroll-content" style="padding-right: 15px; margin-bottom: -30px;">
                    <div class="simplebar-content" style="padding-bottom: 15px; margin-right: -15px;">

                         <!-- Side Header -->
                         <div class="bg-header-dark">
                              <div class="content-header bg-white-10">
                                   <!-- Logo -->
                                   <a class="link-fx font-w600 font-size-md text-white" href="" style=" font-size: 25px; ">
                                        <span class="text-white">Recency</span>&nbsp;<span class="text-white-75">Web</span> </a>
                                   <!-- END Logo -->
                              </div>
                         </div>

                         <!-- END Side Header -->

                         <!-- Side Navigation -->
                         <div class="content-side content-side-full">
                              <ul class="nav-main">
                                   <li class="nav-main-heading"></li>
                                   <?php if ($dashboardMenu != "") {
                                   ?>
                                        <li class="nav-main-item " id="dashboard">
                                             <a class="nav-main-link nav-main-link-submenu" data-toggle="submenu" aria-haspopup="true" aria-expanded="true" href="#">
                                                  <i class="nav-main-link-icon si si-cursor"></i>
                                                  <span class="nav-main-link-name ">Dashboard</span>
                                             </a>
                                             <ul class="nav-main-submenu">
                                                  <?php echo $dashboardMenu; ?>
                                             </ul>
                                        </li>
                                   <?php }
                                   ?>
                                   <?php if ($userMenu != "") { ?>
                                        <li class="nav-main-heading"></li>
                                        <li class="nav-main-item " id="manage">
                                             <a class="nav-main-link nav-main-link-submenu" data-toggle="submenu" aria-haspopup="true" aria-expanded="true" href="#">
                                                  <i class="nav-main-link-icon si si-grid"></i>
                                                  <span class="nav-main-link-name ">Manage</span>
                                             </a>
                                             <ul class="nav-main-submenu">
                                                  <?php echo $userMenu; ?>
                                             </ul>
                                        </li>

                                   <?php }

                                   if ($settingsMenu != '') { ?>
                                        <li class="nav-main-heading" style="padding:3px;"></li>
                                   <?php echo $settingsMenu;
                                   }
                                   if ($recencyMenu != '') { ?>
                                        <li class="nav-main-heading" style="padding:3px;"></li>
                                   <?php echo $recencyMenu;
                                   }
                                   if ($qcMenu != '') { ?>
                                        <li class="nav-main-heading" style="padding:3px;"></li>
                                   <?php echo $qcMenu;
                                   }
                                   if ($vlDataMenu != '') { ?>
                                        <li class="nav-main-heading" style="padding:3px;"></li>
                                   <?php echo $vlDataMenu;
                                   }
                                   if ($emailMenu != '') { ?>
                                        <li class="nav-main-heading" style="padding:3px;"></li>
                                        <?php echo $emailMenu; ?>
                                        <li class="nav-main-heading" style="padding:3px;"></li>
                                   <?php //echo $uploadResultMenu; -->
                                   }
                                   if ($reportMenu != "") { ?>
                                        <li class="nav-main-heading"></li>
                                        <li class="nav-main-item " id="reports">
                                             <a class="nav-main-link nav-main-link-submenu" data-toggle="submenu" aria-haspopup="true" aria-expanded="true" href="#">
                                                  <i class="nav-main-link-icon si si-grid"></i>
                                                  <span class="nav-main-link-name ">Reports</span>
                                             </a>
                                             <ul class="nav-main-submenu">
                                                  <li class="nav-main-heading" style="padding:3px;"></li>
                                                  <?php echo $reportMenu; ?>
                                             </ul>
                                        </li>
                                   <?php
                                   }
                                   if ($monitoringMenu != "") { ?>
                                        <li class="nav-main-heading"></li>
                                        <li class="nav-main-item " id="manage">
                                             <a class="nav-main-link nav-main-link-submenu" data-toggle="submenu" aria-haspopup="true" aria-expanded="true" href="#">
                                                  <i class="nav-main-link-icon si si-eye"></i>
                                                  <span class="nav-main-link-name ">Monitoring</span>
                                             </a>
                                             <ul class="nav-main-submenu">
                                                  <?php echo $monitoringMenu; ?>
                                             </ul>
                                        </li>
                                   <?php
                                   }
                                   ?>
                              </ul>
                         </div>
                    </div>
               </div>
               <!-- END Side Navigation -->
          </nav>
          <!-- END Sidebar -->

          <header id="page-header">
               <!-- Header Content -->
               <div class="content-header">
                    <!-- Left Section -->
                    <div>
                         <!-- Toggle Sidebar -->
                         <button type="button" class="btn btn-dual mr-1" data-toggle="layout" data-action="sidebar_toggle">
                              <i class="fa fa-fw fa-bars"></i>
                         </button>
                         <!-- END Toggle Sidebar -->
                    </div>
                    <!-- END Left Section -->

                    <!-- Right Section -->
                    <div>
                         <!-- User Dropdown -->
                         <div class="dropdown d-inline-block">
                              <!-- Crosss Login Block Start -->
                              <?php if (!empty($configResult['vlsm']['crosslogin']) && $configResult['vlsm']['crosslogin'] === true) {
                              ?>
                                   <a class="btn btn-dual" onclick="setCrossLogin();" href="<?php echo rtrim($configResult['vlsm']['domain'], "/") . '/login/loginProcess.php?u=' . base64_encode($sessionLogin->userEmail) . '&t=' . ($sessionLogin->crossLoginPass) . '&name=' . base64_encode($sessionLogin->userName); ?>">
                                        <span class="d-none d-sm-inline-block"><i class="fa fa-external-link-alt" style=" font-size: 14px; "></i> VLSM</span>
                                   </a>
                              <?php } ?>
                              <!-- Crosss Login Block End -->
                              <button type="button" class="btn btn-dual" id="page-header-user-dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                   <i class="fa fa-fw fa-user d-sm-none"></i>
                                   <span class="d-none d-sm-inline-block"><?php echo $userName; ?></span>
                                   <i class="fa fa-fw fa-angle-down ml-1 d-none d-sm-inline-block"></i>
                              </button>
                              <div class="dropdown-menu dropdown-menu-right p-0" aria-labelledby="page-header-user-dropdown">
                                   <div class="p-2">
                                        <a class="dropdown-item" href="/user/edit-profile/<?php echo base64_encode($sessionLogin->userId); ?>">
                                             <i class="far fa-fw fa-user mr-1"></i> Edit Profile
                                        </a>

                                        <div role="separator" class="dropdown-divider"></div>
                                        <a class="dropdown-item" href="/logout">
                                             <i class="far fa-fw fa-arrow-alt-circle-left mr-1"></i> Sign Out
                                        </a>
                                   </div>
                              </div>
                         </div>
                         <!-- END User Dropdown -->
                    </div>
                    <!-- END Right Section -->
               </div>
               <!-- END Header Content -->
               <!-- Header Loader -->
               <!-- Please check out the Loaders page under Components category to see examples of showing/hiding it -->
               <div id="page-header-loader" class="overlay-header bg-primary-darker">
                    <div class="content-header">
                         <div class="w-100 text-center">
                              <i class="fa fa-fw fa-2x fa-sun fa-spin text-white"></i>
                         </div>
                    </div>
               </div>
               <!-- END Header Loader -->
          </header>
          <!-- END Header -->
          <!-- END Header -->
          <div data-notify="container" class="col-11 col-sm-4 alert alert-danger animated fadeIn" role="alert" data-notify-position="top-center" id="recencyAlert" style="display: none; margin: 0px auto; position: fixed; transition: all 0.5s ease-in-out 0s; z-index: 1033; top: 20px; left: 0px; right: 0px; animation-iteration-count: 1;">
               <button type="button" aria-hidden="true" onclick="dismissAlert();" class="close" data-notify="dismiss" style="position: absolute; right: 10px; top: 5px; z-index: 1035;">×</button>
               <span data-notify="icon"></span> <span data-notify="title"></span>
               <a data-notify="message" id="nonRemoteUserMsg" href="/recency/index"></a>
               <a href="#" target="_blank" data-notify="url"></a>
          </div>
          <main id="main-container">
               <!-- Hero -->
               <?php echo $this->content; ?>
               <!-- END Hero -->
          </main>
          <!-- END Main Container -->
          <!-- Footer -->
          <footer id="page-footer" class="bg-body-light">
               <div class="content py-0">
                    <div class="row font-size-sm">
                         <div class="col-sm-6 order-sm-1 text-center text-sm-left">
                              <strong>Copyright &copy; <?php echo date('Y'); ?> <a href="#"></a></strong> All rights reserved.
                         </div>
                         <div class="col-sm-6 order-sm-1 text-center text-sm-right">
                              <strong>Version 0.1</strong>
                         </div>
                    </div>
               </div>
          </footer>
          <!-- END Footer -->
     </div>
     <!-- END Page Container -->
     <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script> -->
     <script src="<?php echo $this->basePath() . '/assets/js/alert.js'; ?>"></script>
     <script src="<?php echo $this->basePath() . '/assets/js/dashmix.core.min.js'; ?>"></script>
     <script src="<?php echo $this->basePath() . '/assets/js/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js'; ?>"></script>
     <script src="<?php echo $this->basePath() . '/assets/js/plugins/bootstrap-notify/bootstrap-notify.min.js'; ?>"></script>

     <script src="<?php echo $this->basePath() . '/assets/js/dashmix.app.min.js'; ?>"></script>
     <script src="<?php echo $this->basePath() . '/assets/js/pages/be_forms_validation.min.js'; ?>"></script>
     <script src="<?php echo $this->basePath() . '/assets/js/plugins/jquery-validation/jquery.validate.min.js'; ?>"></script>
     <script src="<?php echo $this->basePath() . '/assets/js/plugins/jquery-validation/additional-methods.js'; ?>"></script>
     <script src="<?php echo $this->basePath() . '/assets/js/pages/deforayValidation.js'; ?>"></script>
     <script src="<?php echo $this->basePath() . '/assets/js/jquery.blockUI.js'; ?>"></script>

     <script src="<?php echo $this->basePath() . '/assets/js/plugins/datatables/jquery.dataTables.min.js'; ?>"></script>
     <script src="<?php echo $this->basePath() . '/assets/js/plugins/datatables/dataTables.bootstrap4.min.js'; ?>"></script>
     <script src="<?php echo $this->basePath() . '/assets/js/plugins/datatables/buttons/dataTables.buttons.min.js'; ?>"></script>
     <script src="<?php echo $this->basePath() . '/assets/js/plugins/datatables/buttons/buttons.print.min.js'; ?>"></script>
     <script src="<?php echo $this->basePath() . '/assets/js/plugins/datatables/buttons/buttons.html5.min.js'; ?>"></script>
     <script src="<?php echo $this->basePath() . '/assets/js/plugins/datatables/buttons/buttons.flash.min.js'; ?>"></script>
     <script src="<?php echo $this->basePath() . '/assets/js/plugins/datatables/buttons/buttons.colVis.min.js'; ?>"></script>
     <script src="<?php echo $this->basePath() . '/assets/js/pages/be_tables_datatables.min.js'; ?>"></script>


     <script src="<?php echo $this->basePath() . '/assets/plugins/datepicker/moment.min.js'; ?>"></script>
     <script src="<?php echo $this->basePath() . '/assets/plugins/datepicker/daterangepicker.js'; ?>"></script>


     <!-- vivek -->
     <script src="<?php echo $this->basePath() . '/assets/js/select2.full.min.js'; ?>"></script>
     <script src="<?php echo $this->basePath() . '/assets/js/plugins/select2/js/select2.full.min.js'; ?>"></script>
     <script src="<?php echo $this->basePath() . '/assets/js/select2.full.js'; ?>"></script>

     <script>
          jQuery(function() {
               Dashmix.helpers(['datepicker', 'colorpicker', 'maxlength', 'select2', 'rangeslider']);
          });
     </script>
     <script src="https://apis.google.com/js/platform.js?onload=onLoad" async defer></script>

     <!-- vivek -->
     <!-- <script src="https://apis.google.com/js/platform.js?onload=onLoad" async defer></script> -->
     <!-- <script src="http://code.jquery.com/ui/1.10.2/jquery-ui.js" ></script> -->

     <script src="<?php echo $this->basePath() . '/assets/js/plugins/jquery-bootstrap-wizard/bs4/jquery.bootstrap.wizard.min.js'; ?>"></script>
     <script src="<?php echo $this->basePath() . '/assets/js/pages/be_forms_wizard.min.js'; ?>"></script>

     <script type="text/javascript">
          $(document).ready(function() {
               <?php if (isset($alertContainer->alertMsg) && $alertContainer->alertMsg != "") { ?>
                    alert("<?php echo $alertContainer->alertMsg; ?>");
               <?php $alertContainer->alertMsg = "";
                    unset($alertContainer->alertMsg);
               }
               if ($crossLoginSession->logged) { ?>
                    setCrossLogin();
               <?php } ?>
               <?php if (isset($nonRemoteUserMsg) && $nonRemoteUserMsg != "") { ?>
                    $("#nonRemoteUserMsg").text('<?php echo $nonRemoteUserMsg; ?>');
                    $("#recencyAlert").css("display", "inline-block");

               <?php } ?>

          });
          $(function() {
               str = $(location).attr('pathname');

               splitsUrl = str.split("/", 4);
               if (splitsUrl[1] == 'facilities' || splitsUrl[1] == 'user' || splitsUrl[1] == 'recency' || splitsUrl[1] == 'global-config' || splitsUrl[1] == 'province' || splitsUrl[1] == 'district' || splitsUrl[1] == 'city') {
                    if (splitsUrl[1] != 'recency') {
                         $('#manage').addClass('open');
                         $('#' + splitsUrl[1]).addClass('active');
                    } else if (splitsUrl[1] == 'recency') {
                         $('#manage').removeClass('open');
                         $('#recency-menu').addClass('open');
                         $('#' + splitsUrl[1]).addClass('active');
                    }
               } else if (splitsUrl[1] == 'analysis-dashboard' || splitsUrl[1] == '') {
                    $('#dashboard').addClass('open');
                    if (splitsUrl[1] == '') {
                         $('#lab-dashboard').addClass('active');
                    } else {
                         $('#' + splitsUrl[1]).addClass('active');
                    }
               } else if (splitsUrl[1] == 'quality-control-dashboard' || splitsUrl[1] == '') {
                    $('#dashboard').addClass('open');
                    if (splitsUrl[1] == '') {
                         $('#quality-contrl-dashboard').addClass('active');
                    } else {
                         $('#' + splitsUrl[1]).addClass('active');
                    }
               } else if (splitsUrl[1] == 'quality-check') {
                    $('#manage').removeClass('open');
                    $('#' + splitsUrl[1]).addClass('active');
               } else if (splitsUrl[1] == 'settings') {
                    $('#settings').removeClass('open');
                    $('#' + splitsUrl[1]).addClass('active');
               } else if (splitsUrl[1] == 'vl-data' && splitsUrl[2] == 'recent-infection') {
                    $('#manage').removeClass('open');
                    $('#reports').addClass('open');
                    $('#' + splitsUrl[2]).addClass('active');
               } else if (splitsUrl[1] == 'vl-data' && splitsUrl[2] == 'lt-infection') {
                    $('#manage').removeClass('open');
                    $('#reports').addClass('open');
                    $('#' + splitsUrl[2]).addClass('active');
               } else if (splitsUrl[1] == 'vl-data' && splitsUrl[2] == 'tat-report') {
                    $('#manage').removeClass('open');
                    $('#reports').addClass('open');
                    $('#' + splitsUrl[2]).addClass('active');
               } else if (splitsUrl[1] == 'vl-data' && (splitsUrl[2] == 'weekly-report' || splitsUrl[2] == 'qc-report')) {
                    $('#manage').removeClass('open');
                    $('#reports').addClass('open');
                    $('#' + splitsUrl[2]).addClass('active');
               } else if (splitsUrl[1] == 'vl-data' && splitsUrl[2] == 'age-wise-infection-report') {
                    $('#manage').removeClass('open');
                    $('#reports').addClass('open');
                    $('#' + splitsUrl[2]).addClass('active');
               } else if (splitsUrl[1] == 'vl-data' && splitsUrl[2] == 'email-result') {
                    $('#email-result').removeClass('open');
                    $('#' + splitsUrl[2]).addClass('active');
               } else if (splitsUrl[1] == 'vl-data') {
                    $('#manage').removeClass('open');
                    $('#' + splitsUrl[1]).addClass('active');
               } else if (splitsUrl[1] == 'print-results') {
                    $('#manage').removeClass('open');
                    $('#' + splitsUrl[1]).addClass('active');
               } else if (splitsUrl[1] == 'manifests') {
                    $('#manage').removeClass('open');
                    $('#' + splitsUrl[1]).addClass('active');
               }
          });

          function setCrossLogin() {
               if (typeof(Storage) !== "undefined") {
                    sessionStorage.setItem("crosslogin", "true");
               } else {
                    alert("Your browser doesn't support the session!");
                    sessionStorage.setItem("crosslogin", "false");
               }
          }

          function dismissAlert() {
               $("#recencyAlert").css("display", "none");
               $.post("<?php echo $this->url('common', array('action' => 'set-session')); ?>", {},
                    function(data) {
                         window.location.reload(true);
                    });
          }
     </script>
</body>

</html>
