<?php

use Zend\Session\Container;

$editAction = '{"sClass":"center"},{"sClass":"center"},{"sClass":"center"}';
?>
<div class="bg-body-light">
     <div class="content content-full">
          <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
               <h1 class="flex-sm-fill font-size-h2 font-w400 mt-2 mb-0 mb-sm-2"><?php echo $globalConfigResult[2]['global_value'] ?></h1>
               <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                    <ol class="breadcrumb">
                         <li class="breadcrumb-item">
                              <a href="<?php echo $this->url('city', array('action' => 'add')); ?>" class="btn btn-primary pull-right" style="margin-top:-5px;"><i class="fa fa-plus"></i>&nbsp;Add New <?php echo $globalConfigResult[2]['global_value'] ?></a>
                         </li>
                    </ol>
               </nav>
          </div>
     </div>
</div>
<div class="content">
     <div class="block block-rounded block-bordered">
          <div class="block-header block-header-default">

          </div>
          <div class="block-content block-content-full">
               <table id="CityDataTable" class="table table-bordered table-striped table-vcenter">
                    <thead>
                         <tr>
                              <th><?php echo $globalConfigResult[1]['global_value'] ?> Name</th>
                              <th><?php echo $globalConfigResult[2]['global_value'] ?> Name</th>
                              <th>Action</th>
                         </tr>
                    </thead>
                    <tbody>
                         <tr>
                              <td colspan="3" class="dataTables_empty">Loading data from server</td>
                         </tr>
                         <tr>
                    </tbody>
               </table>
          </div>
     </div>
</div>

<script type="text/javascript">
     /* Table initialisation */
     oTable = null;
     $(document).ready(function() {
          oTable = $('#CityDataTable').dataTable({
               "bAutoWidth": false,
               "bProcessing": true,
               "bServerSide": true,
               "aoColumns": [
                    <?php echo $editAction; ?>
               ],
               "sAjaxSource": "<?php echo $this->url('city', array('action' => 'index')); ?>",
               "fnServerData": function(sSource, aoData, fnCallback) {
                    $.ajax({
                         "dataType": 'json',
                         "type": "POST",
                         "url": sSource,
                         "data": aoData,
                         "success": fnCallback
                    });
               }
          });

     });
</script>