<?php

use Laminas\Session\Container;
use Application\Service\CommonService;

$sessionLogin = new Container('credo');
$common = new CommonService();

$qcTestDateFormat = '';
if ($result->qc_test_date != '' && $result->qc_test_date != null && $result->qc_test_date != '0000-00-00') {
     $qcTestDateFormat = $common->humanDateFormat($result->qc_test_date);
}

$hivRecencyTestDateFormat = '';
if ($result->hiv_recency_test_date != '' && $result->hiv_recency_test_date != null && $result->hiv_recency_test_date != '0000-00-00') {
     $hivRecencyTestDateFormat = $common->humanDateFormat($result->hiv_recency_test_date);
}

$testKitExpiryDateFormat = '';
if ($result->kit_expiry_date != '' && $result->kit_expiry_date != null && $result->kit_expiry_date != '0000-00-00') {
     $testKitExpiryDateFormat = $common->humanDateFormat($result->kit_expiry_date);
}

$lineOutComeColor = "#de1d2b";
$lineOutComeColor2 = "#000000";

?>
<style>
     <?php if ($result['term_outcome'] == '') {
          ?>.outcome {
          display: none;
     }

     <?php
     }

     ?>.btnHide {
          display: none;
     }

     .colour {
          color: red;
     }
</style>

<div class="bg-body-light">
     <div class="content content-full">
          <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
               <h1 class="flex-sm-fill font-size-h2 font-w400 mt-2 mb-0 mb-sm-2">Quality Check</h1>
               <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                    <ol class="breadcrumb">
                         <a href="<?php echo $this->url('quality-check', array('action' => 'index')); ?>">
                              <li class="breadcrumb-item">Quality Test Details</li>
                         </a>
                         <li class="breadcrumb-item active" aria-current="page">&nbsp;/ Edit</li>
                    </ol>
               </nav>
          </div>
     </div>
</div>

<div class="content">
     <div class="block block-rounded block-bordered">
          <div class="block-header block-header-default">
               <h3 class="block-title">Edit Quality Check Testing</h3>
          </div>
          <div class="block-content">
               <div class="col-md-12 table-responsive" id="hide">
                    <form name="qcEditInformation" id="qcEditInformation" class="mb-5" action="<?php echo $this->url('quality-check', array('action' => 'edit')); ?>" method="post">

                         <div class="form-group row">
                              <label class="col-sm-2 col-form-label" for="qcSampleId">QC Sample ID <span class="mandatory">*</span></label>
                              <div class="col-sm-4">
                                   <select class="form-control isRequired" id="qcSampleId" name="qcSampleId" title="Please select the QC Sample ID">
                                        <option value="">--Select--</option>
                                        <?php foreach ($sampleInfo as $sample) { ?>
                                             <option value="<?php echo $sample['qc_sample_no']; ?>" <?php echo ($sample['qc_sample_no'] == $result['qc_sample_id']) ? 'selected="selected"' : ''; ?>><?php echo $sample['qc_sample_no']; ?></option>
                                        <?php } ?>
                                   </select>
                              </div>
                              <label class="col-sm-2 col-form-label" for="">QC Test Date<span class="mandatory">*</span></label>
                              <div class="col-sm-4">
                                   <input type="text" value="<?php echo $qcTestDateFormat; ?>" class="js-datepicker form-control isRequired" id="qcTestDate" name="qcTestDate" data-week-start="1" data-autoclose="true" data-today-highlight="true" data-date-format="dd-M-yyyy" value="" placeholder="Enter the QC Test Date" title="Please enter the QC Test Date" readonly="readonly">
                              </div>
                         </div>

                         <div class="form-group row">
                              <label class="col-sm-2 col-form-label" for="">Reference Result<span class="mandatory">*</span></label>
                              <div class="col-sm-4">
                                   <select class="form-control isRequired" id="referenceResult" name="referenceResult" title="Please select the Reference Result">
                                        <option value="">--select--</option>
                                        <option value="preliminary_recent_sample" <?php echo ($result['reference_result'] == 'preliminary_recent_sample') ? 'selected="selected"' : ''; ?>>Preliminary Recent QC</option>
                                        <option value="long_term_sample" <?php echo ($result['reference_result'] == 'long_term_sample') ? 'selected="selected"' : ''; ?>>Long term QC</option>
                                        <option value="hiv_negative_sample" <?php echo ($result['reference_result'] == 'hiv_negative_sample') ? 'selected="selected"' : ''; ?>>HIV Negative QC</option>
                                   </select>
                              </div>
                              <label class="col-sm-2 col-form-label" for="testKitLotNo">Test Kit Lot No.<span class="mandatory">*</span></label>
                              <div class="col-sm-4">
                                   <select class="form-control isRequired" id="testKitLotNo" name="testKitLotNo" onchange="testKitLotNoChange(this);" title="Please select the test Kit Lot No">
                                        <option value="">--Select--</option>
                                        <?php foreach ($kitInfo as $info) { ?>
                                             <option value="<?php echo $info['kit_lot_no']; ?>" <?php echo ($info['kit_lot_no'] == $result['kit_lot_no']) ? 'selected="selected"' : ''; ?>><?php echo $info['kit_lot_no']; ?></option>
                                        <?php } ?>
                                   </select>
                              </div>

                         </div>

                         <div class="form-group row">
                              <label class="col-sm-2 col-form-label" for="">Test Kit Expiry Date<span class="mandatory">*</span></label>
                              <div class="col-sm-4">
                                   <input type="text" value="<?php echo $testKitExpiryDateFormat; ?>" class="js-datepicker form-control isRequired" id="testKitExpDate" name="testKitExpDate" data-week-start="1" data-autoclose="true" data-today-highlight="true" data-date-format="dd-M-yyyy" placeholder="Enter the kit expiry date" title="Please enter the Kit Expiry date" readonly="readonly">
                              </div>
                              <label class="col-sm-2 col-form-label" for="">QC Test Date <span class="mandatory">*</span></label>
                              <div class="col-sm-4">
                                   <input type="text" value="<?php echo $hivRecencyTestDateFormat; ?>" class="js-datepicker form-control disbaledResult isRequired" id="hivRecencyTestDate" name="hivRecencyTestDate" data-week-start="1" data-autoclose="true" data-today-highlight="true" data-date-format="dd-M-yyyy" value="" placeholder="Enter the QC Test Date" title="Please enter the QC Test Date" readonly="readonly">
                              </div>
                         </div>



                         <div class="form-group row">


                              <label class="col-sm-2 col-form-label" for="">Control Line<span class="mandatory">*</span></label>
                              <div class="col-sm-4">
                                   <select class="form-control disbaledResult isRequired" id="controlLine" name="controlLine" title="Please select the control line" onchange="changeTermLine()">
                                        <option value="">--Select--</option>
                                        <option value="present" <?php echo ($result['control_line'] == 'present') ? 'selected="selected"' : ''; ?>>Present</option>
                                        <option value="absent" <?php echo ($result['control_line'] == 'absent') ? 'selected="selected"' : ''; ?>>Absent</option>
                                   </select>
                              </div>
                              <label class="col-sm-2 col-form-label" for="">Verification Line<span class="mandatory">*</span></label>
                              <div class="col-sm-4">
                                   <select class="form-control disbaledResult isRequired" id="positiveVerificationLine" name="positiveVerificationLine" title="Please select the Verification Line" onchange="changeTermLine()">
                                        <option value="">--Select--</option>
                                        <option value="present" <?php echo ($result['positive_verification_line'] == 'present') ? 'selected="selected"' : ''; ?>>Present(Positive/P)</option>
                                        <option value="absent" <?php echo ($result['positive_verification_line'] == 'absent') ? 'selected="selected"' : ''; ?>>Absent(Negative/N)</option>
                                   </select>
                              </div>
                         </div>
                         <div class="form-group row">

                              <label class="col-sm-2 col-form-label" for="">Long Term Line<span class="mandatory">*</span></label>
                              <div class="col-sm-4">
                                   <select class="form-control disbaledResult isRequired" id="longTermVerificationLine" name="longTermVerificationLine" title="Please select the Long Term Line" onchange="changeTermLine()">
                                        <option value="">--Select--</option>
                                        <option value="present" <?php echo ($result['long_term_verification_line'] == 'present') ? 'selected="selected"' : ''; ?>>Present(Long Term/LT)</option>
                                        <option value="absent" <?php echo ($result['long_term_verification_line'] == 'absent') ? 'selected="selected"' : ''; ?>>Absent(Recent/R)</option>
                                   </select>
                                   <br>
                              </div>
                              <label class="col-sm-2 col-form-label outcome" for="">Outcome</label>
                              <div class="col-sm-4 outcome">
                                   <span class="outcome form-control" style="border:none;" id="outcome"><?php echo $result['term_outcome']; ?></span>
                                   <input type="hidden" name="outcomeData" id="outcomeData" value="<?php echo $result['term_outcome']; ?>" />
                                   <input type="hidden" name="finalResult" id="finalResult" vlue="<?php echo $result['final_result']; ?>" />
                              </div>
                              <label class="col-sm-2 col-form-label" for="">Tester Name<span class="mandatory">*</span></label>
                              <div class="col-sm-4">
                                   <input type="text" value="<?php echo $result['tester_name']; ?>" class="form-control isRequired" id="testerName" name="testerName" placeholder="Enter the tester name" title="Please enter the tester name">
                              </div>
                              <label class="col-sm-2 col-form-label " for="">Testing Facility<span class="mandatory">*</span></label>
                              <div class="col-sm-4">
                                   <select class="form-control isRequired" id="testingFacilityId" name="testingFacilityId" title="Please select the testing facility name">
                                        <option value="">--Select--</option>
                                        <?php foreach ($facilityResult['facilityTest'] as $testingFacility) { ?>
                                             <option value="<?php echo $testingFacility['facility_id']; ?>" <?php echo ($testingFacility['facility_id'] == $result['testing_facility_id']) ? 'selected="selected"' : ''; ?>><?php echo ucwords($testingFacility['facility_name']); ?></option>
                                        <?php } ?>
                                        <!-- <option value="other">Other</option> -->
                                   </select>
                                   &nbsp;
                                   <input style="display:none;" type="text" class="form-control col-sm-12" id="otherTestingFacility" name="otherTestingFacility" title="Please Enter facility name" value="" placeholder="Enter facility name">
                                   &nbsp;
                              </div>

                              <label class="col-sm-2 col-form-label" for="">Comments<span class="mandatory">*</span></label>
                              <div class="col-sm-4">
                                   <textarea class="form-control isRequired" name="comment" id="comment" title="Please enter comments"><?php echo $result['comment']; ?></textarea>
                              </div>
                         </div>

                         <div class="row items-push">
                              <div class="col-lg-7 offset-lg-4">
                                   <input type="hidden" name="qualityCheckId" value="<?php echo $result['qc_test_id']; ?>" />
                                   <a href="<?php echo $this->url('quality-check', array('action' => 'index')); ?>" class="btn btn-danger">Cancel</a>&nbsp;
                                   <button type="submit" class="btn btn-primary" onclick="validateNow();return false;"><i class="fa fa-fw fa-check"></i> Submit</button>
                              </div>
                         </div>
                    </form>
               </div>
          </div>
     </div>
</div>
<script type="text/javascript" src="//crlcu.github.io/multiselect/dist/js/multiselect.min.js"></script>
<script type="text/javascript">
     function changeTermLine() {
          var ctrlLine = $("#controlLine").val();
          var postiveLine = $("#positiveVerificationLine").val();
          var longTermLine = $("#longTermVerificationLine").val();
          if (ctrlLine != '' && postiveLine != '' && longTermLine != '') {
               if (ctrlLine == 'absent' && postiveLine == 'absent' && longTermLine == 'absent') {
                    $("#outcome").html('Invalid – Please Verify').css({
                         "color": "<?php echo $lineOutComeColor; ?>"
                    });
                    $(".outcome").css({
                         "display": "block"
                    });
               } else if (ctrlLine == 'absent' && postiveLine == 'absent' && longTermLine == 'present') {
                    $("#outcome").html('Invalid – Please Verify').css({
                         "color": "<?php echo $lineOutComeColor; ?>"
                    });
                    $(".outcome").css({
                         "display": "block"
                    });
               } else if (ctrlLine == 'absent' && postiveLine == 'present' && longTermLine == 'absent') {
                    $("#outcome").html('Invalid – Please Verify').css({
                         "color": "<?php echo $lineOutComeColor; ?>"
                    });
                    $(".outcome").css({
                         "display": "block"
                    });
               } else if (ctrlLine == 'absent' && postiveLine == 'present' && longTermLine == 'present') {
                    $("#outcome").html('Invalid – Please Verify').css({
                         "color": "<?php echo $lineOutComeColor; ?>"
                    });
                    $(".outcome").css({
                         "display": "block"
                    });
               } else if (ctrlLine == 'present' && postiveLine == 'absent' && longTermLine == 'absent') {
                    $("#outcome").html('Assay HIV Negative').css({
                         "color": "<?php echo $lineOutComeColor; ?>"
                    });
                    $(".outcome").css({
                         "display": "block"
                    });
               } else if (ctrlLine == 'present' && postiveLine == 'absent' && longTermLine == 'present') {
                    $("#outcome").html('Invalid – Please Verify').css({
                         "color": "<?php echo $lineOutComeColor; ?>"
                    });
                    $(".outcome").css({
                         "display": "block"
                    });
               } else if (ctrlLine == 'present' && postiveLine == 'present' && longTermLine == 'absent') {
                    $("#outcome").html('Assay Recent').css({
                         "color": "<?php echo $lineOutComeColor2; ?>"
                    });
                    $(".outcome").css({
                         "display": "block"
                    });
               } else if (ctrlLine == 'present' && postiveLine == 'present' && longTermLine == 'present') {
                    $("#outcome").html('Long Term').css({
                         "color": "<?php echo $lineOutComeColor2; ?>"
                    });
                    $(".outcome").css({
                         "display": "block"
                    });
               }
          } else {
               $("#outcome").html('').hide();
               $(".outcome").css({
                    "display": "none"
               });
          }
     }

     duplicateName = true;
     var rowCount = 1;

     function validateNow() {

          flag = deforayValidator.init({
               formId: 'qcEditInformation'
          });
          document.getElementById("outcomeData").value = document.getElementById("outcome").innerHTML;
          document.getElementById("outcomeData").value = document.getElementById("outcome").innerHTML;
          if (document.getElementById("outcome").innerHTML == 'Assay Recent - Please ensure you add Viral Load Result') {
               document.getElementById("outcomeData").value = 'Assay Recent';
          }
          if (document.getElementById("outcome").innerHTML == 'Invalid – Please Verify') {
               document.getElementById("outcomeData").value = 'Invalid';
          }

          refResult = $("#referenceResult").val();
          outcData = $("#outcomeData").val();
          if (refResult == 'long_term_sample') {
               if (outcData == 'Long Term') {
                    $("#finalResult").val('pass');
               } else {
                    $("#finalResult").val('fail');
               }
          }
          if (refResult == 'preliminary_recent_sample') {
               if (outcData == 'Assay Recent') {
                    $("#finalResult").val('pass');
               } else {
                    $("#finalResult").val('fail');
               }
          }
          if (refResult == 'hiv_negative_sample') {
               if (outcData == 'Assay HIV Negative') {
                    $("#finalResult").val('pass');
               } else {
                    $("#finalResult").val('fail');
               }
          }
          if (flag) {
               if (duplicateName) {
                    $.blockUI();
                    alert(formId);
                    document.getElementById('qcEditInformation').submit();
               }
          }
     }

     // function otherRecencyTestNotPerfomedCheck(obj){
     //      if( obj.value == 'other' ){
     //           $("#otherRecencyTestNotPerformedReason").css('display','block');
     //           $("#otherRecencyTestNotPerformedReasonLabel").css('display','block');
     //           $(".removeClassReq").addClass("isRequired");
     //
     //      }else{
     //           $("#otherRecencyTestNotPerformedReason").css('display','none').val("").removeClass("isRequired");
     //           $("#otherRecencyTestNotPerformedReasonLabel").css('display','none');
     //      }
     // }

     // $('#recencyTestPerformedYes').change(function() {
     //      if(this.checked == true){
     //           $('#recencyTestNotPerformedReasonLabel').show();
     //           $('#recencyTestNotPerformedReason').show();
     //           $("#outcome").html('').hide();
     //           $(".outcome").hide();
     //           $(".disbaledResult").attr("disabled",true).removeClass("isRequired").val("");
     //           $(".removeClassReq").addClass("isRequired");
     //
     //      }else{
     //           $(".disbaledResult").addClass("isRequired");
     //           $(".disbaledResult").attr("disabled",false);
     //           $(".removeClassReq").removeClass("isRequired").val("");
     //           $('#recencyTestNotPerformedReason').hide();
     //           $('#recencyTestNotPerformedReasonLabel').hide();
     //           $('#otherRecencyTestNotPerformedReason').hide();
     //           $('#otherRecencyTestNotPerformedReasonLabel').hide();
     //      }
     // });


     jQuery(document).ready(function($) {
          // if($('input[id=recencyTestPerformedYes]').prop('checked')==true)
          // {
          //      $('#recencyTestNotPerformedReasonLabel').show();
          //      $('#recencyTestNotPerformedReason').show();
          //      $(".disbaledResult").attr("disabled",true).removeClass("isRequired").val("");
          //      $("#recencyTestNotPerformedReason").addClass("isRequired");
          // }else{
          //      $('#recencyTestNotPerformedReasonLabel').hide();
          //      $('#recencyTestNotPerformedReason').hide();
          //      $(".removeClassReq").removeClass("isRequired").val("");
          //      $("#recencyTestNotPerformedReason").removeClass("isRequired");
          // }
          // if($('#recencyTestNotPerformedReason').val() == "other"){
          //      $('#otherRecencyTestNotPerformedReasonLabel').show();
          //      $('#otherRecencyTestNotPerformedReason').show();
          //      $("#otherRecencyTestNotPerformedReason").addClass("isRequired");
          // }
          changeTermLine();
     });

     function testKitLotNoChange(obj){
          if (obj.value != "") {
               $.post('/recency/get-kit-lot-info', {
                         kitNo: obj.value
                    },
                    function(data) {
                         if (data != "") {
                              var objects = JSON.parse(data)
                              objects.forEach(function(key, index) {
                                   $('#testKitExpDate').val(key.kit_expiry_date);
                              });
                         }
                    });
          } else {
               $('#testKitExpDate').val('');
          }
     }

     $(document).ready(function() {
          $("#testingFacilityId").select2({
               placeholder: "Choose Testing Site",
               width: "280px",
               allowClear: true,
          });
          $("#testKitLotNo").select2({
               placeholder: "Choose Test Kit Lot No",
               width: "280px",
               allowClear: true,
          });
     });
</script>