<?php
$format = $result['format'];
if (isset($result['result']) && count($result['result']) > 0) {
    $n=count($result['result']);
    if($n>4){
        $max='4';
    }else{
        $max=$n-1;
    }
?>
    <script>
        Highcharts.chart('qualitySampleLotChart', {
            credits: {
                enabled: false
            },
            exporting: {
                filename: 'Quality Sample Lot Chart',
                buttons: {
                    contextButton: {
                        menuItems: [
                            'printChart',
                            'separator',
                            'downloadPNG',
                            'downloadJPEG',
                            'downloadPDF',
                            'downloadSVG',
                            'separator',
                            'downloadCSV',
                            'downloadXLS',
                            'viewData'
                        ]
                    }
                }
            },
            
            title: {
                text: ''
            },

            xAxis: {
                categories: [
                    <?php foreach ($result['result'] as $key=>$res) { ?> '<?php echo $key; ?>',
                    <?php } ?>
                ],
                crosshair: true,
                min: 0,
                max: '<?php echo $max; ?>',
                scrollbar: {
                    enabled: true
                },
                title: {
                    enabled: true,
                    text: 'QC Samples <br>(N=<?php echo $result['total']; ?>)',
                    style: {
                        fontSize: '12px',
                    }
                }

            },
            yAxis: {
                min: 0,
                <?php if ($format == 'percentage') { ?>
                    max: 100,
                <?php } ?>
                title: {
                    <?php if ($format == 'percentage') { ?>
                        text: 'Percentage %'
                    <?php } else { ?>
                        text: 'Number of count'
                    <?php } ?>
                }
            },
            legend: {
                reversed: true
            },
            tooltip: {
                headerFormat: '<span style="font-size:10px;color:{series.color}">{point.key}</span><table>',
                <?php if ($format == 'percentage') { ?>
                    pointFormat: '<tr><td style="color:{series.color};padding:0">: </td><td style="padding:0"><b>{point.y}%</b></td></tr></table>'
                <?php } else { ?>
                    pointFormat: '<tr><td style="color:{series.color};padding:0">: </td><td style="padding:0"><b>{point.y}</b></td></tr></table>'
                <?php } ?>
            },

            plotOptions: {
                series: {
                    stacking: 'normal',
                    borderWidth: 0,
                    dataLabels: {
                        enabled: true,
                        formatter: function() {
                            <?php if ($format == 'percentage') { ?>
                                return this.y > 0 ? this.y + '%' : 0;
                            <?php } else { ?>
                                return this.y;
                            <?php } ?>
                        }
                    }
                }
            },
            series: [{
                type: 'column',
                colorByPoint: true,
                data: [
                    <?php foreach ($result['result'] as $val) { ?> 
                        <?php echo $val; ?>,
                    <?php } ?>
                ],
                showInLegend: false
            }]

        });
    </script>
<?php } else {
    echo "<br><br><br><br><br><br><br><h2 style='text-align:center;color:#aaa'>No data available</h2>";
} ?>