<?php

use Zend\Session\Container;
$sessionLogin = new Container('credo');
$roleCode = $sessionLogin->roleCode;

    $editAction = '{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center",bSortable:false}';
?>
<div class="bg-body-light">
     <div class="content content-full">
          <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
               <h1 class="flex-sm-fill font-size-h2 font-w400 mt-2 mb-0 mb-sm-2">Quality Check Testing</h1>
               <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                    <ol class="breadcrumb">
                         <li class="breadcrumb-item">
                              <a href="<?php echo $this->url('quality-check',array('action' => 'add'));?>" class="btn btn-primary pull-right" style="margin-top:-5px;"><i class="fa fa-plus"></i>&nbsp;Add QC Testing</a>
                                <?php if($roleCode=='admin'){ ?>
                                   <a href="javascript:void(0)" class="btn btn-primary pull-right" style="margin-top:-5px;" onclick="exportQCData();"><i class="fa fa-download"></i>&nbsp;Export Excel</a>
                                <?php } ?>
                         </li>
                    </ol>
               </nav>
          </div>
     </div>
</div>
     <div class="content">
          <div class="block block-rounded block-bordered">
               <div class="block-header block-header-default">
               </div>
               <div class="block-content block-content-full">
                    <table id="qcDataTable" class="table-responsive table table-bordered table-striped table-vcenter table-responsive">
                         <thead>
                              <tr>
                                    <th>QC Sample Id</th>
                                    <th>QC Date</th>
                                    <th>Reference Result</th>
                                    <th>Kit Lot No.</th>
                                    <th>Kit Expiry Date</th>
                                    <th>HIV Recency Date</th>
                                    <th>Control Line</th>
                                    <th>Positive Verification</th>
                                    <th>Long Term Verification</th>
                                    <th>Term Outcome</th>
                                    <th>Tester Name</th>
                                    <th>Action</th>
                              </tr>
                         </thead>
                         <tbody>
                              <tr>
                                <?php if($roleCode == "user"){
                                   echo "<td colspan='7' class='dataTables_empty'>Loading data from server</td>";
                                }else{
                                    echo "<td colspan='6' class='dataTables_empty'>Loading data from server</td>";
                                }?>
                              </tr>
                              <tr>
                              </tbody>
                         </table>
                    </div>
               </div>
          </div>

          <script type="text/javascript">
          /* Table initialisation */
          oTable = null;
          $(document).ready(function() {
            oTable = $('#qcDataTable').dataTable( {
                "bAutoWidth": false,
                "bProcessing": true,
                "bServerSide": true,
                "aoColumns": [
                        <?php echo $editAction;?>
                ],
                "sAjaxSource": "<?php echo $this->url('quality-check',array('action' => 'index')); ?>",
                "fnServerData": function ( sSource, aoData, fnCallback ) {
                    $.ajax({
                        "dataType": 'json',
                        "type": "POST",
                        "url": sSource,
                        "data": aoData,
                        "success": fnCallback
                    });
                }
            } );

          } );

        function exportQCData()
        {
            $.blockUI();
            $.post("<?php echo $this->url('quality-check',array('action'=>'export-qc-data')); ?>",
                function(data){
                if(data == "" || data == null || data == undefined){
                $.unblockUI();
                alert('Unable to generate download');
                }else{
                $.unblockUI();
                document.location.href = '/temporary/'+data;
                }
            });
        }
     </script>
