<?php

use Laminas\Session\Container;

$sessionLogin = new Container('credo');
$roleCode = $sessionLogin->roleCode;
$acl=$this->layout()->acl;
if (isset($acl) && $acl->isAllowed($roleCode, 'Application\Controller\QualityCheck', 'edit')) {
    $editAction = '{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center",bSortable:false}';
}else{
    $editAction = '{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"}';
}
?>
<link rel="stylesheet" href="<?php echo $this->basePath() . '/assets/plugins/datepicker/daterangepicker.css' ?>" rel="stylesheet">
<div class="bg-body-light">
    <div class="content content-full">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
            <h1 class="flex-sm-fill font-size-h2 font-w400 mt-2 mb-0 mb-sm-2">Quality Check Testing</h1>
            <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <?php if ($roleCode != "manager" && isset($acl) && $acl->isAllowed($roleCode, 'Application\Controller\QualityCheck', 'edit')) { ?>
                            <a href="<?php echo $this->url('quality-check', array('action' => 'add')); ?>" class="btn btn-primary pull-right" style="margin-top:-5px;"><i class="fa fa-plus"></i>&nbsp;Add QC Testing</a>
                        <?php }
                        if (($roleCode == 'admin' || $roleCode == 'manager') && isset($acl) && $acl->isAllowed($roleCode, 'Application\Controller\QualityCheck', 'export-qc-data')) { ?>
                            <a href="javascript:void(0)" class="btn btn-primary pull-right" style="margin-top:-5px;" onclick="exportQCData();"><i class="fa fa-download"></i>&nbsp;Export Excel</a>
                        <?php } ?>
                    </li>
                </ol>
            </nav>
        </div>
    </div>
</div>
<div class="content">
    <div class="block block-rounded block-bordered">
        <div class="block-header block-header-default">
        </div>
        <div class="block-content block-content-full">

            <table id="advanceFilter" class="table" cellpadding="1" cellspacing="3" style="margin-left:1%;margin-top:20px;width: 98%;margin-bottom: 0px;">
                <tr>
                    <td><b>Assay Outcome :</b></td>
                    <td>
                        <select class="form-control" id="termOut" name="termOut" title="Please select assay outcome" style="width:100%;">
                            <option value=""> -- Select -- </option>
                            <option value="Assay Negative">Assay Negative</option>
                            <option value="Assay Recent">Assay Recent</option>
                            <option value="Long Term">Long Term</option>
                            <option value="Invalid">Invalid</option>
                        </select>
                    </td>
                    <td><b>Testing Site :</b></td>
                    <td>
                        <select class="form-control" id="testingFacility" name="testingFacility" title="Please select testing facility name" style="width:100%;">
                            <option value=""> -- Select -- </option>
                            <?php
                            foreach ($facilityResult['facilityTest'] as $facilityRow) {
                                // if(2 != (int)$facilityRow['facility_type_id']) continue;
                            ?>
                                <option value="<?php echo $facilityRow['facility_id']; ?>"><?php echo ucwords($facilityRow['facility_name']); ?></option>
                            <?php
                            }
                            ?>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td><b>QC Test Dates:</b></td>
                    <td>
                        <input type="text" class="form-control" id="qcTestDate" placeholder="Hiv Recency Test Date" name="qcTestDate" title="Please select HIV Recency Test Dates" style="width:100%;" readonly>
                    </td>
                    <td colspan="4" style="text-align: end;"><input type="button" onclick="searchVlRequestData();" value="Search" class="btn btn-info btn-sm">
                        &nbsp;<button class="btn btn-danger btn-sm" onclick="document.location.href = document.location"><span>Reset</span></button>
                        &nbsp;<button class="btn btn-primary btn-sm pull-right" style="margin-right:5px;" onclick="$('#showhide').fadeToggle();return false;"><span>Manage Columns</span></button>
                    </td>
                </tr>

            </table>
            <span style="display: none;position:absolute;z-index: 9999 !important;color:#000;padding:5px;width:70%;" id="showhide">

                <div class="row" style="background:#eee;padding: 15px;border-radius:20px;font-size:13px;">
                    <div class="col-sm-12 " style=""><a href="javascript:void(0);" style="float:right;font-size:20px;color:red;font-weight:bold" onclick="closeDiv()" title="Close">X</a>
                    </div>

                    <?php $i = 0; ?>
                    <div class="col-sm-3">
                        <input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="<?php echo $i; ?>" id="iCol<?php echo $i; ?>" data-showhide="qc_sample_id" class="showhideCheckBox" /> <label for="iCol<?php echo $i; ?>">QC Sample ID</label>
                    </div>
                    <div class="col-sm-3">
                        <input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="<?php echo $i = $i + 1; ?>" id="iCol<?php echo $i; ?>" data-showhide="qc_test_date" class="showhideCheckBox" /> <label for="iCol<?php echo $i; ?>">QC Date</label> <br>
                    </div>
                    <div class="col-sm-3">
                        <input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="<?php echo $i = $i + 1; ?>" id="iCol<?php echo $i; ?>" data-showhide="reference_result" class="showhideCheckBox" /> <label for="iCol<?php echo $i; ?>">Reference Result</label>
                    </div>
                    <div class="col-sm-3">
                        <input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="<?php echo $i = $i + 1; ?>" id="iCol<?php echo $i; ?>" data-showhide="kit_lot_no" class="showhideCheckBox" /> <label for="iCol<?php echo $i; ?>">Kit Lot No.</label> <br>
                    </div>
                    <div class="col-sm-3">
                        <input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="<?php echo $i = $i + 1; ?>" id="iCol<?php echo $i; ?>" data-showhide="kit_expiry_date" class="showhideCheckBox" /> <label for="iCol<?php echo $i; ?>">Kit Expiry Date</label>
                    </div>
                    <div class="col-sm-3">
                        <input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="<?php echo $i = $i + 1; ?>" id="iCol<?php echo $i; ?>" data-showhide="control_line" class="showhideCheckBox" /> <label for="iCol<?php echo $i; ?>">Control Line</label>
                    </div>
                    <div class="col-sm-3">
                        <input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="<?php echo $i = $i + 1; ?>" id="iCol<?php echo $i; ?>" data-showhide="positive_verification_line" class="showhideCheckBox" /> <label for="iCol<?php echo $i; ?>">Verification Line</label>
                    </div>
                    <div class="col-sm-3">
                        <input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="<?php echo $i = $i + 1; ?>" id="iCol<?php echo $i; ?>" data-showhide="long_term_verification_line" class="showhideCheckBox" /> <label for="iCol<?php echo $i; ?>">Long Term Line</label>
                    </div>
                    <div class="col-sm-3">
                        <input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="<?php echo $i = $i + 1; ?>" id="iCol<?php echo $i; ?>" data-showhide="term_outcome" class="showhideCheckBox" /> <label for="iCol<?php echo $i; ?>">Assay Outcome</label>
                    </div>
                    <div class="col-sm-3">
                        <input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="<?php echo $i = $i + 1; ?>" id="iCol<?php echo $i; ?>" data-showhide="tester_name" class="showhideCheckBox" /> <label for="iCol<?php echo $i; ?>">Tester Name</label>
                    </div>
                </div>
            </span>


            <table id="qcDataTable" class="table-responsive table table-bordered table-striped table-vcenter table-responsive">

                <thead>
                    <tr>
                        <th>QC Sample ID</th>
                        <th>QC Test Date</th>
                        <th>Reference Result</th>
                        <th>Kit Lot No.</th>
                        <th>Kit Expiry Date</th>
                        <th>Control Line</th>
                        <th>Verification Line</th>
                        <th>Long Term Line</th>
                        <th>Assay Outcome</th>
                        <th>Tester Name</th>
                        <?php if ($roleCode != 'manager' && isset($acl) && $acl->isAllowed($roleCode, 'Application\Controller\QualityCheck', 'edit')) { ?>
                        <th>Action</th>
                        <?php } ?>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <?php if ($roleCode == "user") {
                            echo "<td colspan='11' class='dataTables_empty'>Loading data from server</td>";
                        } else {
                            echo "<td colspan='10' class='dataTables_empty'>Loading data from server</td>";
                        } ?>
                    </tr>
                </tbody>
                <tfoot>
                    <tr>
                        <th>QC Sample ID</th>
                        <th>QC Date</th>
                        <th>Reference Result</th>
                        <th>Kit Lot No.</th>
                        <th>Kit Expiry Date</th>
                        <th>Control Line</th>
                        <th>Verification Line</th>
                        <th>Long Term Line </th>
                        <th>Assay Outcome</th>
                        <th>Tester Name</th>
                        <?php if (isset($acl) && $acl->isAllowed($roleCode, 'Application\Controller\QualityCheck', 'edit')) { ?>
                        <th>Action</th>
                        <?php } ?>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>

<script type="text/javascript">
    let searchExecuted = false;
    /* Table initialisation */
    oTable = null;
    $(document).ready(function() {
        $("#testingFacility").select2({
            placeholder: "Choose Testing Site..",
            width: "290px",
            allowClear: true,
        });
        oTable = $('#qcDataTable').dataTable({
            "bAutoWidth": false,
            "bProcessing": true,
            "bServerSide": true,
            "aoColumns": [
                <?php echo $editAction; ?>
            ],
            "sAjaxSource": "<?php echo $this->url('quality-check', array('action' => 'index')); ?>",
            "fnServerData": function(sSource, aoData, fnCallback) {
                aoData.push({
                    "name": "tOutcome",
                    "value": $("#termOut").val()
                });
                aoData.push({
                    "name": "testingFacility",
                    "value": $("#testingFacility").val()
                });
                aoData.push({
                    "name": "qcTestDate",
                    "value": $("#qcTestDate").val()
                });
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
                });
            }
        });

        $(".showhideCheckBox").change(function() {
            if ($(this).attr('checked')) {
                idpart = $(this).attr('data-showhide');
                $("#" + idpart + "-sort").show();
            } else {
                idpart = $(this).attr('data-showhide');
                $("#" + idpart + "-sort").hide();
            }
        });

        var i = '<?php echo $i; ?>';
        for (colNo = 0; colNo <= i; colNo++) {
            $("#iCol" + colNo).attr("checked", oTable.fnSettings().aoColumns[parseInt(colNo)].bVisible);

            if (oTable.fnSettings().aoColumns[colNo].bVisible) {
                $("#iCol" + colNo + "-sort").show();
            } else {
                $("#iCol" + colNo + "-sort").hide();
            }
        }

        $('#qcTestDate').daterangepicker({
                format: 'DD-MMM-YYYY',
                autoUpdateInput: false,
                separator: ' to ',
                startDate: moment().subtract('days', 29),
                endDate: moment(),
                maxDate: moment(),
                ranges: {
                    'Today': [moment(), moment()],
                    'Yesterday': [moment().subtract('days', 1), moment().subtract('days', 1)],
                    'Last 7 Days': [moment().subtract('days', 6), moment()],
                    'Last 30 Days': [moment().subtract('days', 29), moment()],
                    'Last 60 Days': [moment().subtract('days', 59), moment()],
                    'Last 180 Days': [moment().subtract('days', 179), moment()],
                    'This Month': [moment().startOf('month'), moment().endOf('month')],
                    'Last Month': [moment().subtract('month', 1).startOf('month'), moment().subtract('month', 1).endOf('month')]
                }
            },
            function(start, end) {
                startDate = start.format('YYYY-MM-DD');
                endDate = end.format('YYYY-MM-DD');
                $('input[name="qcTestDate"]').on('apply.daterangepicker', function(ev, picker) {
                    $(this).val(picker.startDate.format('DD-MMM-YYYY') + ' to ' + picker.endDate.format('DD-MMM-YYYY'));
                });

            });

        $("#advanceFilter input, #advanceFilter select").on("change", function() {
            searchExecuted = false;
        });
    });

    function searchVlRequestData() {
        searchExecuted = true;
        $.blockUI();
        oTable.fnDraw();
        $.unblockUI();
    }

    function closeDiv() {
        $("#showhide").fadeOut('slow');
    }

    function fnShowHide(iCol) {
        var bVis = oTable.fnSettings().aoColumns[iCol].bVisible;
        oTable.fnSetColumnVis(iCol, bVis ? false : true);
    }

    function searchVlRequestData() {
        $.blockUI();
        oTable.fnDraw();
        $.unblockUI();
    }

    function exportQCData() {
        if (searchExecuted === false) {
            searchVlRequestData();
        }
        $.blockUI();
        $.post("<?php echo $this->url('quality-check', array('action' => 'export-qc-data')); ?>",
            function(data) {
                if (data == "" || data == null || data == undefined) {
                    $.unblockUI();
                    alert('Unable to generate download');
                } else {
                    $.unblockUI();
                    document.location.href = '/temporary/' + data;
                }
            });
    }
</script>