<?php
use Zend\Session\Container;
$sessionLogin = new Container('credo');
// \Zend\Debug\Debug::dump($roleResult);die;
?>
<div class="bg-body-light">
     <div class="content content-full">
          <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
               <h1 class="flex-sm-fill font-size-h2 font-w400 mt-2 mb-0 mb-sm-2">Users</h1>
               <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                    <ol class="breadcrumb">
                         <a href="<?php echo $this->url('user', array('action' => 'index')); ?>"><li class="breadcrumb-item">Users Details</li></a>
                         <li class="breadcrumb-item active" aria-current="page">&nbsp;/ Add</li>
                    </ol>
               </nav>
          </div>
     </div>
</div>


<div class="content">
     <div class="block block-rounded block-bordered">
          <div class="block-header block-header-default">
               <h3 class="block-title">Add Users Details</h3>
          </div>
          <div class="block-content">
               <div class="col-md-12 table-responsive" id="hide">
                    <form name="userInformation" id="userInformation"  class="mb-5" action="<?php echo $this->url('user', array('action' => 'add')); ?>" method="post">
                        <div class="form-group row">
                            <label class="col-sm-2 col-form-label" for="keyword">User Name<span class="mandatory">*</span></label>
                            <div class="col-sm-4">
                                <input type="text" class="form-control isRequired" id="userName" name="userName" placeholder="Enter the user name" title="Please enter the user name" onblur="checkNameValidation('user', 'user_name', this,'NULL', 'The user name that you entered already exists . Please try another name..');">
                            </div>

                            <label class="col-sm-2 col-form-label" for="keyword">Role<span class="mandatory">*</span></label>
                            <div class="col-sm-4">
                                <select class="form-control isRequired" id="roleName" name="roleName" title="Please select the role name">
                                    <option value="">--Select--</option>
                                    <?php foreach($roleResult as $role){?>
                                        <option value="<?php echo base64_encode($role['role_id']); ?>"><?php echo $role['role_name']; ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-sm-2 col-form-label" for="keyword">Email<span class="mandatory">*</span></label>
                            <div class="col-sm-4">
                                <input type="email" class="form-control isRequired" id="email" name="email" placeholder="Enter the email" title="Please enter the email">
                            </div>

                            <label class="col-sm-2 col-form-label" for="keyword">Alternate Email</label>
                            <div class="col-sm-4">
                                <input type="email" class="form-control" id="altEmail" name="altEmail" placeholder="Enter the alternate email" title="Please enter the alternate email">
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-sm-2 col-form-label" for="keyword">Password<span class="mandatory">*</span></label>
                            <div class="col-sm-4">
                                <input type="password" class="form-control isRequired" id="servPass" name="servPass" placeholder="Enter the Password" title="Please enter the password">
                            </div>

                            <label class="col-sm-2 col-form-label" for="keyword">Mobile<span class="mandatory">*</span></label>
                            <div class="col-sm-4">
                                <input type="number" class="form-control isRequired" id="mobile" name="mobile" placeholder="Enter the mobile" title="Please enter the mobile">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-sm-2 col-form-label" for="keyword">Alternate Mobile</label>
                            <div class="col-sm-4">
                                <input type="number" class="form-control" id="altMobile" name="altMobile" placeholder="Enter the alternate mobile" title="Please enter the alternate mobile">
                            </div>
                            
                            <label class="col-sm-2 col-form-label" for="keyword">Job Responsibility<span class="mandatory">*</span></label>
                            <div class="col-sm-4">
                                <input type="text" class="form-control isRequired" id="JobResponse" name="JobResponse" placeholder="Enter the job responsibility" title="Please enter the job responsibility">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-sm-2 col-form-label" for="keyword">Comments</label>
                            <div class="col-sm-4">
                                <textarea rows="4" cols="50" class="form-control" id="comments" name="comments" placeholder="Enter the comments" title="Please enter the comments"></textarea>
                            </div>

                            <label class="col-sm-2 col-form-label" for="keywordType">Status<span class="mandatory">*</span></label>
                            <div class="col-sm-4">
                                <select class="form-control isRequired" id="userStatus" name="userStatus" title="Please select the user status">
                                    <option value="active">Active</option>
                                    <option value="inactive">Inactive</option>
                                </select>
                            </div>
                        </div>
                        <div class="row items-push">
                            <div class="col-lg-7 offset-lg-4">
                                <a href="<?php echo $this->url('user', array('action' => 'index')); ?>" class="btn btn-danger">Cancel</a>&nbsp;
                                <button type="submit" class="btn btn-primary" onclick="validateNow();return false;"><i class="fa fa-fw fa-check"></i> Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    duplicateName = true;
    function validateNow() {
        flag = deforayValidator.init({
            formId: 'userInformation'
        });
        if (flag) {
            if (duplicateName) {
                $.blockUI();
                getmatterid();
                document.getElementById('userInformation').submit();
            }
        }
    }
    function checkNameValidation(tableName, fieldName, obj, fnct, msg){
        checkValue = document.getElementById(obj.id).value;
        if($.trim(checkValue)!= ''){
            $.post("<?php echo $this->url('common', array('action' => 'index')); ?>", { tableName: tableName, fieldName: fieldName, value: checkValue, companyId: companyId, existingCompanyId: existingCompanyId, fnct: fnct, srcfrom: 'SuperAdmin'},
            function(data) {
                if (data > 0)
                {
                        alert(msg);
                        duplicateName = false;
                        document.getElementById(obj.id).value = "";
                }
                else {
                        duplicateName = true;
                }
            });
        }
    }
    $(document).ready(function(){

        
    });

</script>
