<?php
use Laminas\Session\Container;
$sessionLogin = new Container('credo');
$facilityId = array();
?>
<div class="bg-body-light">
     <div class="content content-full">
          <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
               <h1 class="flex-sm-fill font-size-h2 font-w400 mt-2 mb-0 mb-sm-2">Edit Profile</h1>
               <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                    <ol class="breadcrumb">
                         <a href="/"><li class="breadcrumb-item">Home</li></a>
                         <li class="breadcrumb-item active" aria-current="page">&nbsp;/ Edit Profile</li>
                    </ol>
               </nav>
          </div>
     </div>
</div>


<div class="content">
    <div class="block block-rounded block-bordered">
        <div class="block-header block-header-default">
            <h3 class="block-title">Edit Profile Details</h3>
        </div>
        <div class="block-content">
            <div class="col-md-12 table-responsive" id="hide">
                <form name="userInformation" id="userInformation"  class="mb-5" action="<?php echo $this->url('user', array('action' => 'edit-profile')); ?>" method="post">
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" for="">User Name<span class="mandatory">*</span></label>
                        <div class="col-sm-4">
                            <input type="text" value="<?php echo $result['user_name']; ?>" class="form-control isRequired" id="userName" name="userName" placeholder="Enter the user name" title="Please enter the user name" >
                        </div>
                        <label class="col-sm-2 col-form-label" for="">Login Email<span class="mandatory">*</span></label>
                        <div class="col-sm-4">
                            <input type="email" style="background-color:#fff;" readonly value="<?php echo $result['email']; ?>" class="form-control isRequired" id="email" name="email" placeholder="Enter the email" title="Please enter the email" onblur="checkNameValidation('users', 'email', this,'<?php echo "user_id##".$result['user_id'];?>', 'The email that you entered already exists . Please try another name..');">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" for="">Alternate Email</label>
                        <div class="col-sm-4">
                            <input type="email" value="<?php echo $result['alt_email']; ?>" class="form-control" id="altEmail" name="altEmail" placeholder="Enter the alternate email" title="Please enter the alternate email">
                        </div>
                        <label class="col-sm-2 col-form-label" for="">Password</label>
                        <div class="col-sm-4">
                            <input type="password"class="form-control " id="servPass" name="servPass" placeholder="Enter the Password" title="Please enter the password">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" for="">Mobile<span class="mandatory">*</span></label>
                        <div class="col-sm-4">
                            <input type="number" value="<?php echo $result['mobile']; ?>" class="form-control isRequired" id="mobile" name="mobile" placeholder="Enter the mobile" title="Please enter the mobile">
                        </div>
                        <label class="col-sm-2 col-form-label" for="">Alternate Mobile</label>
                        <div class="col-sm-4">
                            <input type="number" value="<?php echo $result['alt_mobile']; ?>" class="form-control" id="altMobile" name="altMobile" placeholder="Enter the alternate mobile" title="Please enter the alternate mobile">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" for="">Job Responsibility<span class="mandatory">*</span></label>
                        <div class="col-sm-4">
                            <input type="text" value="<?php echo $result['job_responsibility']; ?>" class="form-control isRequired" id="JobResponse" name="JobResponse" placeholder="Enter the job responsibility" title="Please enter the job responsibility">
                        </div>
                        <label class="col-sm-2 col-form-label" for="">Comments</label>
                        <div class="col-sm-4">
                            <textarea rows="4" cols="50" class="form-control" id="comments" name="comments" placeholder="Enter the comments" title="Please enter the comments"><?php echo $result['comments']; ?></textarea>
                        </div>
                    </div>
                    <div class="row items-push">
                        <div class="col-lg-7 offset-lg-4">
                        <input type="hidden" name="userId" value="<?php echo base64_encode($result['user_id']); ?>"/>
                            <a href="/" class="btn btn-danger">Cancel</a>&nbsp;
                            <button type="submit" class="btn btn-primary" onclick="validateNow();return false;"><i class="fa fa-fw fa-check"></i> Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    duplicateName = true;
    function validateNow() {
        flag = deforayValidator.init({
            formId: 'userInformation'
        });
        if (flag) {
            if (duplicateName) {
                $.blockUI();
                
                document.getElementById('userInformation').submit();
            }
        }
    }
    function checkNameValidation(tableName, fieldName, obj, fnct, msg){
        checkValue = document.getElementById(obj.id).value;
        if($.trim(checkValue)!= ''){
            $.post("<?php echo $this->url('common', array('action' => 'index')); ?>", { tableName: tableName, fieldName: fieldName, value: checkValue, fnct: fnct},
            function(data) {
                if (data > 0)
                {
                        alert(msg);
                        duplicateName = false;
                        document.getElementById(obj.id).value = "";
                }
                else {
                        duplicateName = true;
                }
            });
        }
    }
    $(document).ready(function($){
    });
</script>
