<link rel="stylesheet" href="https://unpkg.com/leaflet@1.4.0/dist/leaflet.css" integrity="sha512-puBpdR0798OZvTTbP4A8Ix/l+A4dHDD0DGqYW6RQ+9jxkRFclaxxQb/SJAWZfWAkuyeQUytO7+7N4QKrDh+drA==" crossorigin="" />

<?php

use Zend\Session\Container;

$sessionLogin = new Container('credo');
$roleCode = $sessionLogin->roleCode;
//\Zend\Debug\Debug::dump($globalConfigResult);die;

$editAction = ' {"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"}';
$startDate = date('d-M-Y', strtotime('today - 365 days'));
$currentDate = date('d-M-Y');
?>
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/highcharts-more.js"></script>
<script src="https://code.highcharts.com/modules/solid-gauge.js"></script>
<style>
	.highcharts-container{
		height: 160px !important;
		overflow: initial !important;
	}
	.display-4 {
		color: #fb885f !important;
		font-weight: 400px  !important;
		padding: 45px 0px;
		font-stretch: expanded;
	}
</style>
<link rel="stylesheet" href="<?php echo $this->basePath() . '/assets/plugins/datepicker/daterangepicker.css' ?>" rel="stylesheet">
<div class="bg-body-light">
	<div class="content content-full">
		<div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
			<h1 class="flex-sm-fill font-size-h2 font-w400 mt-2 mb-0 mb-sm-2">Analysis Dashboard</h1>
		</div>
	</div>
</div>
<div class="content">
	<div class="row sticky-div" style=" position: sticky; top: 70px; z-index: 3;background: #f0f8ffbf;margin-bottom: 20px; ">
		<div class="form-group row" style="border: 1px solid #80808069;margin: 0px !important;padding: 15px 0px;">
			<div class="col-sm-4" style=" margin-top:10px;">
				<input type="text" id="sampleTestedDates" name="sampleTestedDates" class="form-control" placeholder="Select Date Range" readonly style="background:#fff;" value="" />
			</div>
			<?php
			foreach ($globalConfigResult as $config) { ?>
				<?php if ($config['global_name'] == 'location_one' || $config['global_name'] == 'location_two' || $config['global_name'] == 'location_three') { ?>
					<div class="col-sm-2" style=" margin-top: 10px; ">
						<select class="form-control" id="<?php echo $config['global_name']; ?>" name="<?php echo $config['global_name']; ?>" title="Please enter the <?php echo lcfirst($config['global_value']); ?>" onchange="getLocationDeatils('<?php echo $config["global_name"]; ?>');">
							<option value="">-- Select --</option>
						</select>
					</div>
			<?php }
			} ?>
			<div class="col-sm-2" style=" margin-top: 10px; ">
				<select class="form-control" id="facilityId" name="facilityId" title="Please choose facility">
					<option value="">-- Select --</option>
				</select>
			</div>

			<div class="col-sm-2" style=" margin-top: 10px; ">
				<select class="form-control" id="testingFacility" name="testingFacility" title="Please select testing facility name" style="width:100%;">
					<option value=""> -- Select-- </option>
					<?php foreach ($facilityResult['facilityTest'] as $facilityRow) { ?>
						<option value="<?php echo $facilityRow['facility_id']; ?>"><?php echo ucwords($facilityRow['facility_name']); ?></option>
					<?php } ?>
				</select>
			</div>
			<div class="items-push col-lg-2" style=" margin-top: 10px; ">
				<a href="javascript:void(0);" class="btn btn-hero-primary" onclick="getFinalOutcomeChart();getInfectionByDistrictChart();getInfectionByAgeChart();getRecentInfectionByMonthSexChart();"><i class="fa fa-fw fa-search"></i> Search</a>
			</div>
			<div class="col-lg-8 hide-div" style=" margin-top: 10px;display:none; ">
				<a class="float-right" href="javascript:void(0);" onclick="onhide('sticky-div');" style="padding: 5px; color: #5f9ea0c2;">
					<i class="fa fa-arrow-up"></i> Hide
				</a>
			</div>
		</div>
	</div>
	<div class="row" style=" border: 1px solid #8080806b; background: aliceblue;margin-bottom: 20px; ">
		<div class="col-md-6">
			<h2 class="content-heading">
				<i class="fa fa-angle-right text-muted mr-1"></i> Recent Infection by Gender &nbsp;&nbsp;&nbsp;&nbsp;
				<small class="custom-control custom-switch custom-control-inline">
					<input type="checkbox" class="custom-control-input" id="recent-infection-by-gender-percentage" name="recent-infection-by-gender-percentage" checked onchange="getFinalOutcomeChart();">
					<label class="custom-control-label" for="recent-infection-by-gender-percentage">Percentage</label>
				</small>
			</h2>
			<div class="block block-rounded block-bordered">
				<div class="block-content block-content-full">
					<div id="container" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
				</div>
			</div>
		</div>
		<div class="col-md-6">
			<h2 class="content-heading">
				<i class="fa fa-angle-right text-muted mr-1"></i> Recent Infection by District
				&nbsp;&nbsp;&nbsp;&nbsp;
				<small class="custom-control custom-switch custom-control-inline">
					<input type="checkbox" class="custom-control-input" id="recent-infection-by-district-percentage" name="recent-infection-by-district-percentage" checked onchange="getInfectionByDistrictChart();">
					<label class="custom-control-label" for="recent-infection-by-district-percentage">Percentage</label>
				</small>
			</h2>
			<div class="block block-rounded block-bordered">
				<div class="block-content block-content-full">
					<div id="infectionByDistrict" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
				</div>
			</div>
		</div>
	</div>
	<div class="row" style=" border: 1px solid #8080806b; background: aliceblue;margin-bottom: 20px; ">
		<div class="col-md-6">
			<h2 class="content-heading">
				<i class="fa fa-angle-right text-muted mr-1"></i> Recent Infection by Age
				&nbsp;&nbsp;&nbsp;&nbsp;
				<small class="custom-control custom-switch custom-control-inline">
					<input type="checkbox" class="custom-control-input" id="recent-infection-by-age-percentage" name="recent-infection-by-age-percentage" checked onchange="getInfectionByAgeChart();">
					<label class="custom-control-label" for="recent-infection-by-age-percentage">Percentage</label>
				</small>
			</h2>
			<div class="block block-rounded block-bordered">
				<div class="block-content block-content-full">
					<div id="infectionByAge" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
				</div>
			</div>
		</div>
		<div class="col-md-6">
			<h2 class="content-heading">
				<i class="fa fa-angle-right text-muted mr-1"></i> Recent Infection by Month and Sex
				&nbsp;&nbsp;&nbsp;&nbsp;
				<small class="custom-control custom-switch custom-control-inline">
					<input type="checkbox" class="custom-control-input" id="recent-infection-by-month-sex" name="recent-infection-by-month-sex" checked onchange="getRecentInfectionByMonthSexChart();">
					<label class="custom-control-label" for="recent-infection-by-month-sex">Percentage</label>
				</small>
			</h2>
			<div class="block block-rounded block-bordered">
				<div class="block-content block-content-full">
					<div id="infectionByMonthSex" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
				</div>
			</div>
		</div>
	</div>
	<div class="row" style=" border: 1px solid #8080806b; background: aliceblue;margin-bottom: 20px; ">
		<div class="col-md-12">
			<h2 class="content-heading">
				<i class="fa fa-angle-right text-muted mr-1"></i> Map (feature is under development)
			</h2>
			<div class="block block-rounded block-bordered">
				<div class="block-content block-content-full">
					<div id="mapid" style="height: 480px;z-index: 1;"></div>
				</div>
			</div>
		</div>
	</div>
	<div class="row" style=" border: 1px solid #8080806b; background: aliceblue;margin-bottom: 20px; ">
		<div class="col-md-12">
			<h2 class="content-heading">
				<i class="fa fa-angle-right text-muted mr-1"></i> # of Recent (feature is under development)
			</h2>
			<div class="block block-rounded block-bordered">
				<div class="block-content block-content-full">
					<div id="circleMap" style="height: 600px;z-index:1;"></div>
				</div>
			</div>
		</div>
	</div>
</div>

<script src="https://code.highcharts.com/stock/highstock.js"></script>
<script src="<?php echo $this->basePath() . '/assets/js/exporting.js'; ?>"></script>
<script src="<?php echo $this->basePath() . '/assets/js/export-data.js'; ?>"></script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB2D8wrWMY3XZnuHO6C31uq90JiuaFzGws"></script>
<script src="<?php echo $this->basePath() . '/assets/_es6/pages/be_comp_maps_google.js'; ?>"></script>
<script src="<?php echo $this->basePath() . '/assets/js/plugins/gmaps/gmaps.min.js'; ?>"></script>
<script src="<?php echo $this->basePath() . '/assets/js/pages/be_comp_maps_google.min.js'; ?>"></script>
<script src="https://unpkg.com/leaflet@1.4.0/dist/leaflet.js" integrity="sha512-QVftwZFqvtRNi0ZyCtsznlKSWOStnDORoefr1enyq5mVL4tmKB3S/EnC3rRJcxCPavG10IcrVGSmPh6Qw5lwrg==" crossorigin=""></script>
<script type="text/javascript">
	var flag = true; 
	var mymap = L.map('mapid').setView([-1.9565912, 30.0595336], 14);
	var citymap = {
        Butare: {
          center: {lat: -2.608007, lng: 29.735934},
          population: 27800
        },
        Kibungo: {
          center: {lat: -2.161069, lng: 30.544063},
          population: 57800
        },
        Ruhengeri: {
          center: {lat: -1.503175, lng: 29.631295},
          population: 07800
        },
        Gitarama: {
          center: {lat: -2.082385, lng: 29.717131},
          population: 47800
        },
        Kigarama: {
          center: {lat: -1.980945, lng: 30.071184},
          population: 25800
        },
        Musasa: {
          center: {lat: -1.819176, lng: 29.850755},
          population: 37800
        }
	};
	function initMapMarkers() {
		var map = new google.maps.Map(document.getElementById('circleMap'), {
          zoom: 8,
          center: {lat: -1.986817, lng: 29.952009},
          mapTypeId: 'roadmap'
        });

        for (var city in citymap) {
          var cityCircle = new google.maps.Circle({
            strokeColor: '#FF0000',
            strokeOpacity: 0.8,
            strokeWeight: 2,
            fillColor: '#FF0000',
            fillOpacity: 0.35,
            map: map,
            center: citymap[city].center,
            radius: Math.sqrt(citymap[city].population) * 100
          });
        }
        /* if (jQuery('#circleMap').length) {
            new GMaps({
                div: '#circleMap',
                lat: 48.8566,
                lng: 2.3522,
                zoom: 11,
                scrollwheel: false
            }).addMarkers([
                {lat: 48.79, lng: 2.31, title: 'Map Marker #1', animation: google.maps.Animation.DROP, infoWindow: {content: 'Map Marker #1'}},
                {lat: 48.88, lng: 2.42, title: 'Map Marker #2', animation: google.maps.Animation.DROP, infoWindow: {content: 'Map Marker #2'}},
                {lat: 48.90, lng: 2.36, title: 'Map Marker #3', animation: google.maps.Animation.DROP, infoWindow: {content: 'Map Marker #3'}},
                {lat: 48.79, lng: 2.39, title: 'Map Marker #4', animation: google.maps.Animation.DROP, infoWindow: {content: 'Map Marker #4'}},
                {lat: 48.77, lng: 2.44, title: 'Map Marker #5', animation: google.maps.Animation.DROP, infoWindow: {content: 'Map Marker #5'}}
            ]);
		} */
	}
	
	L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw', {
		maxZoom: 18,
		attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, ' +
			'<a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, ' +
			'Imagery &copy; <a href="https://www.mapbox.com/">Mapbox</a>',
		id: 'mapbox.streets'
	}).addTo(mymap);

	L.marker([-1.9565912, 30.0595336]).addTo(mymap);

	/* Table initialisation */
	oTable = null;
	$(document).ready(function() {
		$('#page-container').removeClass('sidebar-o');
		initMapMarkers();
		$("#location_one").select2({
			placeholder: "Choose Province",
			allowClear: true,
		});
		$("#location_two").select2({
			placeholder: "Choose District",
			allowClear: true,
		});
		$("#location_three").select2({
			placeholder: "Choose City",
			allowClear: true,
		});
		$("#facilityId").select2({
			placeholder: "Choose Facility",
			allowClear: true,
		});
		$("#testingFacility").select2({
			placeholder: "Choose Testing Site",
			allowClear: true,
		});
		getFinalOutcomeChart();
		getInfectionByDistrictChart();
		getInfectionByAgeChart();
		getRecentInfectionByMonthSexChart();
		
		//getHivViralLoadChart();
		<?php foreach ($globalConfigResult as $config) {
			?>
			getLocationDeatils('<?php echo $config["global_name"]; ?>');
			<?php
			break;
		} ?>

		$('#sampleTestedDates').daterangepicker({
				format: 'DD-MMM-YYYY',
				autoUpdateInput: false,
				separator: ' to ',
				startDate: moment().subtract('days', 29),
				endDate: moment(),
				maxDate: moment(),
				ranges: {
					'Today': [moment(), moment()],
					'Yesterday': [moment().subtract('days', 1), moment().subtract('days', 1)],
					'Last 7 Days': [moment().subtract('days', 6), moment()],
					'Last 30 Days': [moment().subtract('days', 29), moment()],
					'Last 60 Days': [moment().subtract('days', 59), moment()],
					'Last 180 Days': [moment().subtract('days', 179), moment()],
					'This Month': [moment().startOf('month'), moment().endOf('month')],
					'Last Month': [moment().subtract('month', 1).startOf('month'), moment().subtract('month', 1).endOf('month')]
				}
			},
			function(start, end) {
				startDate = start.format('YYYY-MM-DD');
				endDate = end.format('YYYY-MM-DD');
				$('input[name="sampleTestedDates"]').on('apply.daterangepicker', function(ev, picker) {
					$(this).val(picker.startDate.format('DD-MMM-YYYY') + ' to ' + picker.endDate.format('DD-MMM-YYYY'));
				});

			});

			
	});



	function getLocationDeatils(globalName, nxtGlobalName) {
		var selectValue = document.getElementById(globalName).value;
		var innerId = '';
		var path = '';
		if (globalName == 'location_one' && selectValue == '') {
			path = 'get-province';
			innerId = 'location_one';
		} else if (globalName == 'location_one' && selectValue != '') {
			path = 'get-district';
			innerId = 'location_two';
			$("#location_three").html("<option value=''>-- Select --</option>");
		} else if (globalName == 'location_two' && selectValue != '') {
			path = 'get-city';
			innerId = 'location_three';
		} else if (globalName == 'location_three' || globalName == 'location_two') {
			getFacilityListByLocation(globalName);
		}
		if (path != '') {
			$.blockUI();
			$.post("/common/" + path, {
					selectValue: selectValue
				},
				function(data) {
					$("#" + innerId).html(data);
					getFacilityListByLocation(globalName);
					$.unblockUI();
				});
		}
	}

	function getFacilityListByLocation(globalName) {
		$.post("<?php echo $this->url('facilities', array('action' => 'get-facility-by-location')); ?>", {
				locationOne: $("#location_one").val(),
				locationTwo: $("#location_two").val(),
				locationThree: $("#location_three").val(),
				globalName: globalName
			},
			function(data) {
				$("#facilityId").html('<option value="">-- Select --</option>' + data);
			});
	}

	function getFinalOutcomeChart() {
		var format = null;
		if ($('#recent-infection-by-gender-percentage').prop('checked')) {
			format = 'percentage';
		} else {
			format = 'number';
		}
		$.post("<?php echo $this->url('recency', array('action' => 'recent-infection-by-gender-chart')); ?>", {
				format: format,
				sampleTestedDates: $("#sampleTestedDates").val(),
				locationOne: $("#location_one").val(),
				locationTwo: $("#location_two").val(),
				locationThree: $("#location_three").val(),
				fName: $("#facilityId").val(),
				testingFacility: $("#testingFacility").val()
			},
			function(data) {
				$("#container").html(data);
			});
	}

	function getInfectionByDistrictChart() {
		var format = null;
		if ($('#recent-infection-by-district-percentage').prop('checked')) {
			format = 'percentage';
		} else {
			format = 'number';
		}
		$.post("<?php echo $this->url('recency', array('action' => 'recent-infection-by-district-chart')); ?>", {
				format: format,
				sampleTestedDates: $("#sampleTestedDates").val(),
				locationOne: $("#location_one").val(),
				locationTwo: $("#location_two").val(),
				locationThree: $("#location_three").val(),
				fName: $("#facilityId").val(),
				testingFacility: $("#testingFacility").val()
			},
			function(data) {
				$("#infectionByDistrict").html(data);
			});
	}

	function getInfectionByAgeChart() {
		var format = null;
		if ($('#recent-infection-by-age-percentage').prop('checked')) {
			format = 'percentage';
		} else {
			format = 'number';
		}
		$.post("<?php echo $this->url('recency', array('action' => 'recent-infection-by-age-chart')); ?>", {
				format: format,
				sampleTestedDates: $("#sampleTestedDates").val()
			},
			function(data) {
				$("#infectionByAge").html(data);
			});
	}
	// function getHivViralLoadChart() {		
	// 	$.post("< ?php echo $this->url('recency', array('action' => 'recent-hiv-viral-load-chart')); ?>",{sampleTestedDates:$("#sampleTestedDates").val()},
	// 	function(data){
	// 		$("#hivViralLoad").html(data);
	// 	});
	// }
	

	function getRecentInfectionByMonthSexChart() {
		var format = null;
		if ($('#recent-infection-by-month-sex').prop('checked')) {
			format = 'percentage';
		} else {
			format = 'number';
		}
		$.post("<?php echo $this->url('recency', array('action' => 'recent-infection-by-month-sex-chart')); ?>", {
				format: format,
				sampleTestedDates: $("#sampleTestedDates").val()
			},
			function(data) {
				$("#infectionByMonthSex").html(data);
			});
	}

	function onhide(_class){
		$('.'+_class).css('position','inherit');
		$('.hide-div').hide(500);
		flag = false;
	}

	$(document).scroll(function() {
		if(flag){
			if($(window).scrollTop() > 159){
				$('.hide-div').show(500);
			}else{
				$('.hide-div').hide(500);
			}
		}
	});
</script>