	<?php

	use Zend\Session\Container;
	$sessionLogin = new Container('credo');
	$roleCode = $sessionLogin->roleCode;
	//\Zend\Debug\Debug::dump($globalConfigResult);die;

	$editAction = ' {"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"}';
	$startDate=date('d-M-Y', strtotime('today - 29 days'));
	$currentDate=date('d-M-Y');
	?>
	<style>
	</style>
	<link rel="stylesheet" href="<?php echo $this->basePath() . '/assets/plugins/datepicker/daterangepicker.css'?>" rel="stylesheet">
	<div class="bg-body-light">
		<div class="content content-full">
			<div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
				<h1 class="flex-sm-fill font-size-h2 font-w400 mt-2 mb-0 mb-sm-2">Analysis Dashboard</h1>
			</div>
		</div>
	</div>
	<div class="content">
			<div class="block block-rounded block-bordered">
			<div class="block-content block-content-full">
			<div class="form-group row">
				<label style=" margin-bottom: 2.5%; " class="col-sm-2 col-form-label" for="">Sample Collection Date</label>
							<div class="col-sm-4">
							<input type="text" id="sampleTestedDates" name="sampleTestedDates" class="form-control" placeholder="Select Date Range" readonly style="background:#fff;" value="<?php echo $startDate." to ".$currentDate;?>"/>
								</div>
							<?php
							foreach($globalConfigResult as $config){ ?>
								<?php if($config['global_name'] == 'location_one' || $config['global_name'] == 'location_two' || $config['global_name'] == 'location_three'){ ?>
									<label style=" margin-bottom: 2.5%; " class="col-sm-2 col-form-label" for=""><?php echo ucfirst($config['global_value']); ?></label>
									<div class="col-sm-4">
										<select class="form-control" id="<?php echo $config['global_name']; ?>" name="<?php echo $config['global_name']; ?>" title="Please enter the <?php echo lcfirst($config['global_value']); ?>" onchange="getLocationDeatils('<?php echo $config["global_name"];?>');">
											<option value="">-- Select --</option>
										</select>
									</div>
								<?php }
							}?>
							<label style=" margin-bottom: 2.5%; " class="col-sm-2 col-form-label" for="">Facility</label>
							<div class="col-sm-4">
								<select class="form-control" id="facilityId" name="facilityId" title="Please choose facility">
									<option value="">-- Select --</option>
								</select>
							</div>

							<label style=" margin-bottom: 2.5%; " class="col-sm-2 col-form-label" for="">Testing Site</label>
							<div class="col-sm-4">
									<select class="form-control" id="testingFacility" name="testingFacility"  title="Please select testing facility name" style="width:100%;">
									<option value=""> -- Select -- </option>
										<?php
										foreach($facilityResult['facilityTest'] as $facilityRow){
											if(2 != (int)$facilityRow['facility_type_id']) continue;
										?>
										<option value="<?php echo $facilityRow['facility_id'];?>"><?php echo ucwords($facilityRow['facility_name']);?></option>
										<?php
										}
										?>
									</select>
								</div>
								
								
						<div class="row items-push">
							<div class="col-lg-7 ">
								<a href="javascript:void(0);" class="btn btn-primary" onclick="searchData(); getRecencyAllDataCount();getFinalOutcomeChart();"><i class="fa fa-fw fa-check"></i> Search</a>
								
							</div>
						</div>
						</div>
						</div>
						</div>
					
						


						
						<h2 class="content-heading">
							<i class="fa fa-angle-right text-muted mr-1"></i> FInal Outcome Chart
						</h2>
						<div class="block block-rounded block-bordered">
						<div class="block-content block-content-full">

						<div id="container" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
						</div>
						</div>                
							
					
					
	</div>
	<script src="<?php echo $this->basePath() . '/assets/js/highcharts.js'; ?>"></script>
	<script src="<?php echo $this->basePath() . '/assets/js/exporting.js.js'; ?>"></script>
	<script src="<?php echo $this->basePath() . '/assets/js/export-data.js'; ?>"></script>

	<script type="text/javascript">
			/* Table initialisation */
			oTable = null;
			$(document).ready(function() {

				getRecencyAllDataCount();
				getFinalOutcomeChart();

				

				<?php foreach($globalConfigResult as $config){
				?>
				getLocationDeatils('<?php echo $config["global_name"];?>');
				<?php
				break;
			} ?>

		$('#sampleTestedDates').daterangepicker({
			format: 'DD-MMM-YYYY',
			autoUpdateInput: false,
				separator: ' to ',
				startDate: moment().subtract('days', 29),
				endDate: moment(),
				maxDate: moment(),
				ranges: {
					'Today': [moment(), moment()],
					'Yesterday': [moment().subtract('days', 1), moment().subtract('days', 1)],
					'Last 7 Days': [moment().subtract('days', 6), moment()],
					'Last 30 Days': [moment().subtract('days', 29), moment()],
					'This Month': [moment().startOf('month'), moment().endOf('month')],
					'Last Month': [moment().subtract('month', 1).startOf('month'), moment().subtract('month', 1).endOf('month')]
					}
	},
	function(start, end) {
		startDate = start.format('YYYY-MM-DD');
		endDate = end.format('YYYY-MM-DD');
		$('input[name="sampleTestedDates"]').on('apply.daterangepicker', function(ev, picker) {
		$(this).val(picker.startDate.format('DD-MMM-YYYY') + ' to ' + picker.endDate.format('DD-MMM-YYYY'));
	});

	});
				});

			function searchData(){
				$.blockUI();
				oTable.fnDraw();
				$.unblockUI();
			}



			function getLocationDeatils(globalName,nxtGlobalName)
		{
			var selectValue = document.getElementById(globalName).value;
			var innerId = '';
			var path = '';
				if(globalName=='location_one' && selectValue==''){
					path = 'get-province';
					innerId = 'location_one';
				}else if(globalName=='location_one' && selectValue!=''){
					path = 'get-district';
					innerId = 'location_two';
					$("#location_three").html("<option value=''>-- Select --</option>");
				}else if(globalName=='location_two' && selectValue!=''){
					path = 'get-city';
					innerId = 'location_three';
				}else if(globalName=='location_three' || globalName=='location_two'){
					getFacilityListByLocation(globalName);
				}
				if(path!=''){
					$.blockUI();
					$.post("/common/"+path, {selectValue:selectValue},
					function(data) {
						$("#"+innerId).html(data);
						getFacilityListByLocation(globalName);
						$.unblockUI();
					});
				}
		}
		function getFacilityListByLocation(globalName)
		{
			$.post("<?php echo $this->url('facilities', array('action' => 'get-facility-by-location')); ?>", {locationOne:$("#location_one").val(),locationTwo:$("#location_two").val(),locationThree:$("#location_three").val(),globalName:globalName},
			function(data) {
				$("#facilityId").html('<option value="">-- Select --</option>'+data);
			});
		}

		function exportRecencyInfo()
		{
			$.blockUI();
			$.post("<?php echo $this->url('home',array('action'=>'export-recency-data')); ?>",
				function(data){
				if(data == "" || data == null || data == undefined){
				$.unblockUI();
				alert('Unable to generate download');
				}else{
				$.unblockUI();
				document.location.href = '/temporary/'+data;
				}
			});
		}

	function getRecencyAllDataCount() {
		
			$.post("<?php echo $this->url('recency',array('action'=>'get-recency-all-data-count')); ?>",{sampleTestedDates:$("#sampleTestedDates").val(),locationOne:$("#location_one").val(),locationTwo:$("#location_two").val(),locationThree:$("#location_three").val(),fName:$("#facilityId").val(),testingFacility:$("#testingFacility").val(),tOutcome:$("#termOut").val(),finalOutcome:$("#finalOutcome").val()},
				function(data){
					var obj = JSON.parse(data);
					$("#totalSamples").html(obj.totalSamples);
					$("#samplesTestedRecency").html(obj.samplesTestedRecency);
					$("#samplesTestedViralLoad").html(obj.samplesTestedViralLoad);
					$("#samplesFinalOutcome").html(obj.samplesFinalOutcome);
			});
	}

		function getFinalOutcomeChart() {
		
			$.post("<?php echo $this->url('recency',array('action'=>'get-final-outcome-chart')); ?>",{sampleTestedDates:$("#sampleTestedDates").val(),locationOne:$("#location_one").val(),locationTwo:$("#location_two").val(),locationThree:$("#location_three").val(),fName:$("#facilityId").val(),testingFacility:$("#testingFacility").val(),tOutcome:$("#termOut").val(),finalOutcome:$("#finalOutcome").val()},
				function(data){
					$("#container").html(data);
			});
	}


	</script>