<?php
use Zend\Session\Container;
     $sessionLogin = new Container('credo');
     $role = $sessionLogin->roleCode;
     $editAction = ' {"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center",bSortable:false}';
?>
<div class="bg-body-light">
     <div class="content content-full">
          <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
               <h1 class="flex-sm-fill font-size-h2 font-w400 mt-2 mb-0 mb-sm-2">
                    <a href="<?php echo $this->url('home'); ?>">Home</h1> </a>
                    <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                         <ol class="breadcrumb">
                              <li class="breadcrumb-item">
                              </li>
                         </ol>
                    </nav>
               </div>
          </div>
     </div>
     <div class="content">
          <div class="block block-rounded block-bordered">
               <div class="block-header block-header-default">
                    <h3 class="block-title">Client Matters </h3>
               </div>
               <div class="block-content block-content-full">
                    <table id="clientDataTable" class="table table-bordered table-striped table-vcenter ">
                         <thead>
                              <tr>
                                   <!-- <th>Agreed Fee</th> -->
                                   <th>File Ref No</th>
                                   <th>File Open Date</th>
                                   <th>Matter Type</th>
                                   <th>Client Name</th>
                                   <th>Fee Earner </th>
                                   <th>Status</th>
                                   <th>Created On</th>
                                   <th>Action</th>
                              </tr>
                         </thead>
                         <tbody>
                              <tr>
                                   <td colspan="8" class="dataTables_empty">Loading data from server</td>
                              </tr>
                              <tr>
                              </tbody>
                         </table>
                    </div>
               </div>
          </div>

          <script type="text/javascript">
          /* Table initialisation */
          oTable = null;
          $(document).ready(function() {
               $('#clientDataTable').dataTable( {
                    "bAutoWidth": false,
                    "bProcessing": true,
                    "bServerSide": true,
                    "aoColumns": [
                         <?php echo $editAction;?>
                    ],
                    "sAjaxSource": "<?php echo $this->url('clients',array('action' => 'client-matter')); ?>",
                    "fnServerData": function ( sSource, aoData, fnCallback ) {
                         $.ajax({
                              "dataType": 'json',
                              "type": "POST",
                              "url": sSource,
                              "data": aoData,
                              "success": fnCallback
                         });
                    }
               } );

          } );

     </script>
