<link rel="stylesheet" href="https://unpkg.com/leaflet@1.4.0/dist/leaflet.css" integrity="sha512-puBpdR0798OZvTTbP4A8Ix/l+A4dHDD0DGqYW6RQ+9jxkRFclaxxQb/SJAWZfWAkuyeQUytO7+7N4QKrDh+drA==" crossorigin="" />

<?php

use Zend\Session\Container;

$sessionLogin = new Container('credo');
$roleCode = $sessionLogin->roleCode;
//\Zend\Debug\Debug::dump($globalConfigResult);die;

$editAction = ' {"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"}';
$startDate = date('d-M-Y', strtotime('today - 365 days'));
$currentDate = date('d-M-Y');
?>
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/highcharts-more.js"></script>
<script src="https://code.highcharts.com/modules/solid-gauge.js"></script>
<style>
	.highcharts-container{
		height: 160px !important;
		overflow: initial !important;
	}
	.display-4 {
		color: #fb885f !important;
		font-weight: 400px  !important;
		padding: 45px 0px;
		font-stretch: expanded;
	}
</style>
<link rel="stylesheet" href="<?php echo $this->basePath() . '/assets/plugins/datepicker/daterangepicker.css' ?>" rel="stylesheet">
<div class="bg-body-light">
	<div class="content content-full">
		<div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
			<h1 class="flex-sm-fill font-size-h2 font-w400 mt-2 mb-0 mb-sm-2">Quality Control Dashboard</h1>
		</div>
	</div>
</div>
<div class="content">
	<div class="row sticky-div" style=" position: sticky; top: 70px; z-index: 1;background: #f0f8ffbf;margin-bottom: 20px; ">
		<div class="form-group row" style="border: 1px solid #80808069;margin: 0px !important;padding: 15px 0px;">
			<div class="col-sm-4" style=" margin-top:10px;">
				<input type="text" id="sampleTestedDates" name="sampleTestedDates" class="form-control" placeholder="Select Date Range" readonly style="background:#fff;" value="" />
			</div>
			<?php
			foreach ($globalConfigResult as $config) { ?>
				<?php if ($config['global_name'] == 'location_one' || $config['global_name'] == 'location_two' || $config['global_name'] == 'location_three') { ?>
					<div class="col-sm-2" style=" margin-top: 10px;width:100%; ">
						<select class="form-control" id="<?php echo $config['global_name']; ?>" name="<?php echo $config['global_name']; ?>" title="Please enter the <?php echo lcfirst($config['global_value']); ?>" onchange="getLocationDeatils('<?php echo $config["global_name"]; ?>');">
							<option value="">-- Select --</option>
						</select>
					</div>
			<?php }
			} ?>
			<div class="col-sm-2" style=" margin-top: 10px; ">
				<select class="form-control" id="facilityId" name="facilityId" title="Please choose facility" style="width:100%;">
					<option value="">-- Select --</option>
				</select>
			</div>

			<div class="col-sm-2" style=" margin-top: 10px; ">
				<select class="form-control" id="testingFacility" name="testingFacility" title="Please select testing facility name" style="width:100%;">
					<option value=""> -- Select-- </option>
					<?php foreach ($facilityResult['facilityTest'] as $facilityRow) {?>
						<option value="<?php echo $facilityRow['facility_id']; ?>"><?php echo ucwords($facilityRow['facility_name']); ?></option>
					<?php } ?>
				</select>
			</div>
			<div class="items-push col-lg-2" style=" margin-top: 10px;text-align:center;">
				<a href="javascript:void(0);" class="btn btn-hero-primary" onclick="getQualityResultsChart();getQualitySampleLotChart();getQualityResultsLitLotNumberChart();getTestingQualityChart();getQualityControlByMonth();"><i class="fa fa-fw fa-search"></i> Search</a>
			</div>
			<div class="col-lg-8 hide-div" style=" margin-top: 10px;display:none; ">
				<a class="float-right" href="javascript:void(0);" onclick="onhide();" style="padding: 5px; color: #5f9ea0c2;">
					<i class="fa fa-arrow-up"></i> Hide
				</a>
			</div>
		</div>
	</div>
	<h2 class="content-heading">
		<i class="fa fa-angle-right text-muted mr-1"></i> Testing Quality
		&nbsp;&nbsp;&nbsp;&nbsp;
		<small class="custom-control custom-switch custom-control-inline">
			<input type="checkbox" class="custom-control-input" id="testing-quality-percentage" name="testing-quality-percentage" checked onchange="getTestingQualityChart();">
			<label class="custom-control-label" for="testing-quality-percentage">Percentage</label>
		</small>
		<br>
		<small style="font-size:0.7em;">&nbsp; &nbsp; To assess the quality of Recency Testing</small>
	</h2>
	<div class="row">
		<div class="col-md-6">
			<div class="block block-rounded block-bordered">
				<div class="block-content block-content-full">
					<div id="testingQualityChartNegative" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
				</div>
			</div>
		</div>
		<div class="col-md-6">
			<div class="block block-rounded block-bordered">
				<div class="block-content block-content-full">
					<div id="testingQualityChartInvalid" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
				</div>
			</div>
		</div>
	</div>

	<h2 class="content-heading">
		<i class="fa fa-angle-right text-muted mr-1"></i> % Assay Negative or Invalid by District

		<br>
		<small style="font-size:0.7em;">&nbsp; &nbsp; To assess the quality of Recency Testing</small>
	</h2>
	<div class="row">
		<div class="col-md-12">
			<div class="block block-rounded block-bordered">
				<div class="block-content block-content-full">
					<div id="testingQualityTable" style="min-width: 310px;">

					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="row" style=" border: 1px solid #8080806b; background: aliceblue;margin-bottom: 20px; ">
		<div class="col-md-6">
			<h2 class="content-heading">
				<i class="fa fa-angle-right text-muted mr-1"></i> Quality Control Results By Specimen Type
				&nbsp;&nbsp;&nbsp;&nbsp;
				<small class="custom-control custom-switch custom-control-inline">
					<input type="checkbox" class="custom-control-input" id="quality-result-by-speciman-percentage" name="quality-result-by-speciman-percentage" checked onchange="getQualityResultsChart();">
					<label class="custom-control-label" for="quality-result-by-speciman-percentage">Percentage</label>
				</small>
			</h2>
			<div class="block block-rounded block-bordered">
				<div class="block-content block-content-full">
					<div id="qualityResultTermOutcomeChart" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
				</div>
			</div>
		</div>
		<div class="col-md-6">
			<h2 class="content-heading">
				<i class="fa fa-angle-right text-muted mr-1"></i> Quality Control Results By QC Panel Lot
				&nbsp;&nbsp;&nbsp;&nbsp;
				<small class="custom-control custom-switch custom-control-inline">
					<input type="checkbox" class="custom-control-input" id="quality-sample-lot-percentage" name="quality-sample-lot-percentage" checked onchange="getQualitySampleLotChart();">
					<label class="custom-control-label" for="quality-sample-lot-percentage">Percentage</label>
				</small>
			</h2>
			<div class="block block-rounded block-bordered">
				<div class="block-content block-content-full">
					<div id="qualitySampleLotChart" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
				</div>
			</div>
		</div>
	</div>
	<div class="row" style=" border: 1px solid #8080806b; background: aliceblue;margin-bottom: 20px; ">
		<div class="col-md-6">
			<h2 class="content-heading">
				<i class="fa fa-angle-right text-muted mr-1"></i> Quality Control Results By Kit Lot
				&nbsp;&nbsp;&nbsp;&nbsp;
				<small class="custom-control custom-switch custom-control-inline">
					<input type="checkbox" class="custom-control-input" id="quality-result-by-kit-lot-number-percentage" name="quality-result-by-kit-lot-number-percentage" checked onchange="getQualityResultsLitLotNumberChart();">
					<label class="custom-control-label" for="quality-result-by-kit-lot-number-percentage">Percentage</label>
				</small>
			</h2>
			<div class="block block-rounded block-bordered" style="height: 674px;">
				<div class="block-content block-content-full">
					<div id="qualityResultKitLotNumberChart" style="margin-top:100px; min-width: 310px; height: 400px; margin: 0 auto"></div>
				</div>
			</div>
		</div>
		<div class="col-md-6">
			<h2 class="content-heading ">
				<i class="fa fa-angle-right text-muted mr-1"></i> Quality Control Pass Rate by Facility
		
			</h2>
			<div class="block block-rounded block-bordered">
				<div class="block-content block-content-full">
					<table id="passRateFacilityWiseDataTable" class="table table-bordered table-striped table-vcenter">
						<thead>
							<tr>
								<th>Facility</th>
								<th>Kit</th>
								<th>District Name</th>
								<th>% Passed</th>
		
							</tr>
						</thead>
						<tbody>
							<tr>
								<td colspan="5" class="dataTables_empty">Loading data from server</td>
							</tr>
							<tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
	<h2 class="content-heading">
		<i class="fa fa-angle-right text-muted mr-1"></i> Quality Control Pass Rate by Month
		&nbsp;&nbsp;&nbsp;&nbsp;
		<small class="custom-control custom-switch custom-control-inline">
			<input type="checkbox" class="custom-control-input" id="quality-control-by-month" name="quality-control-by-month" checked onchange="getQualityControlByMonth();">
			<label class="custom-control-label" for="quality-control-by-month">Percentage</label>
		</small>
	</h2>
	<div class="block block-rounded block-bordered">
		<div class="block-content block-content-full">
			<div id="qualityControlByMonthwise" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
		</div>
	</div>



</div>
<script src="https://code.highcharts.com/stock/highstock.js"></script>
<script src="<?php echo $this->basePath() . '/assets/js/exporting.js'; ?>"></script>
<script src="<?php echo $this->basePath() . '/assets/js/export-data.js'; ?>"></script>

<script src="https://unpkg.com/leaflet@1.4.0/dist/leaflet.js" integrity="sha512-QVftwZFqvtRNi0ZyCtsznlKSWOStnDORoefr1enyq5mVL4tmKB3S/EnC3rRJcxCPavG10IcrVGSmPh6Qw5lwrg==" crossorigin=""></script>

<script type="text/javascript">
	var hidebtn = true; 
	/* Table initialisation */
	oTable = null;
	$(document).ready(function() {
		$('#page-container').removeClass('sidebar-o');
		$("#location_one").select2({
			placeholder: "Choose Province",
			allowClear: true,
		});
		$("#location_two").select2({
			placeholder: "Choose District",
			allowClear: true,
		});
		$("#location_three").select2({
			placeholder: "Choose City",
			allowClear: true,
		});
		$("#facilityId").select2({
			placeholder: "Choose Facility",
			allowClear: true,
		});
		$("#testingFacility").select2({
			placeholder: "Choose Testing Site",
			allowClear: true,
		});
		getQualityResultsChart();
		getQualitySampleLotChart();
		getQualityResultsLitLotNumberChart();
		getTestingQualityChart();
		getQualityControlByMonth();
		<?php foreach ($globalConfigResult as $config) {
			?>
			getLocationDeatils('<?php echo $config["global_name"]; ?>');
			<?php
			break;
		} ?>

		$('#sampleTestedDates').daterangepicker({
				format: 'DD-MMM-YYYY',
				autoUpdateInput: false,
				separator: ' to ',
				startDate: moment().subtract('days', 29),
				endDate: moment(),
				maxDate: moment(),
				ranges: {
					'Today': [moment(), moment()],
					'Yesterday': [moment().subtract('days', 1), moment().subtract('days', 1)],
					'Last 7 Days': [moment().subtract('days', 6), moment()],
					'Last 30 Days': [moment().subtract('days', 29), moment()],
					'Last 60 Days': [moment().subtract('days', 59), moment()],
					'Last 180 Days': [moment().subtract('days', 179), moment()],
					'This Month': [moment().startOf('month'), moment().endOf('month')],
					'Last Month': [moment().subtract('month', 1).startOf('month'), moment().subtract('month', 1).endOf('month')]
				}
			},
			function(start, end) {
				startDate = start.format('YYYY-MM-DD');
				endDate = end.format('YYYY-MM-DD');
				$('input[name="sampleTestedDates"]').on('apply.daterangepicker', function(ev, picker) {
					$(this).val(picker.startDate.format('DD-MMM-YYYY') + ' to ' + picker.endDate.format('DD-MMM-YYYY'));
				});

			});

		oTable = $('#passRateFacilityWiseDataTable').dataTable({
			"bAutoWidth": false,
			"bProcessing": true,
			"bServerSide": true,
			"aoColumns": [{
					"sClass": "center"
				},
				{
					"sClass": "center"
				},
				{
					"sClass": "center"
				},

				{
					"sClass": "center",
					"bSortable": false
				}
			],
			"sAjaxSource": "<?php echo $this->url('quality-check', array('action' => 'get-pass-rate-by-facility')); ?>",
			"fnServerData": function(sSource, aoData, fnCallback) {

				$.ajax({
					"dataType": 'json',
					"type": "POST",
					"url": sSource,
					"data": aoData,
					"success": fnCallback
				});
			}
		});
	});



	function getLocationDeatils(globalName, nxtGlobalName) {
		var selectValue = document.getElementById(globalName).value;
		var innerId = '';
		var path = '';
		if (globalName == 'location_one' && selectValue == '') {
			path = 'get-province';
			innerId = 'location_one';
		} else if (globalName == 'location_one' && selectValue != '') {
			path = 'get-district';
			innerId = 'location_two';
			$("#location_three").html("<option value=''>-- Select --</option>");
		} else if (globalName == 'location_two' && selectValue != '') {
			path = 'get-city';
			innerId = 'location_three';
		} else if (globalName == 'location_three' || globalName == 'location_two') {
			getFacilityListByLocation(globalName);
		}
		if (path != '') {
			$.blockUI();
			$.post("/common/" + path, {
					selectValue: selectValue
				},
				function(data) {
					$("#" + innerId).html(data);
					getFacilityListByLocation(globalName);
					$.unblockUI();
				});
		}
	}

	function getFacilityListByLocation(globalName) {
		$.post("<?php echo $this->url('facilities', array('action' => 'get-facility-by-location')); ?>", {
				locationOne: $("#location_one").val(),
				locationTwo: $("#location_two").val(),
				locationThree: $("#location_three").val(),
				globalName: globalName
			},
			function(data) {
				$("#facilityId").html('<option value="">-- Select --</option>' + data);
			});
	}


	function getQualityResultsChart() {
		var format = null;
		if ($('#quality-result-by-speciman-percentage').prop('checked')) {
			format = 'percentage';
		} else {
			format = 'number';
		}
		$.post("<?php echo $this->url('quality-check', array('action' => 'get-quality-result-wise-term-outcome-chart')); ?>", {
				format: format,
				sampleTestedDates: $("#sampleTestedDates").val()
			},
			function(data) {
				$("#qualityResultTermOutcomeChart").html(data);
			});
	}

	function getQualitySampleLotChart() {
		var format = null;
		if ($('#quality-sample-lot-percentage').prop('checked')) {
			format = 'percentage';
		} else {
			format = 'number';
		}
		$.post("<?php echo $this->url('quality-check', array('action' => 'get-sample-lot-chart')); ?>", {
				format: format,
				sampleTestedDates: $("#sampleTestedDates").val()
			},
			function(data) {
				$("#qualitySampleLotChart").html(data);
			});
	}

	function getQualityResultsLitLotNumberChart() {
		var format = null;
		if ($('#quality-result-by-kit-lot-number-percentage').prop('checked')) {
			format = 'percentage';
		} else {
			format = 'number';
		}
		$.post("<?php echo $this->url('quality-check', array('action' => 'get-kit-lot-number-chart')); ?>", {
				format: format,
				sampleTestedDates: $("#sampleTestedDates").val()
			},
			function(data) {
				$("#qualityResultKitLotNumberChart").html(data);
			});
	}

	function getTestingQualityChart() {
		var format = null;
		if ($('#testing-quality-percentage').prop('checked')) {
			format = 'percentage';
		} else {
			format = 'number';
		}
		$.post("<?php echo $this->url('quality-check', array('action' => 'get-testing-quality-negative-chart')); ?>", {
				format: format,
				sampleTestedDates: $("#sampleTestedDates").val()
			},
			function(data) {
				$("#testingQualityChartNegative").html(data);
			});

		$.post("<?php echo $this->url('quality-check', array('action' => 'get-testing-quality-invalid-chart')); ?>", {
				format: format,
				sampleTestedDates: $("#sampleTestedDates").val()
			},
			function(data) {
				$("#testingQualityChartInvalid").html(data);
			});

		$.post("<?php echo $this->url('quality-check', array('action' => 'get-district-wise-quality-check-invalid')); ?>", {
				format: format,
				sampleTestedDates: $("#sampleTestedDates").val(),
				locationThree: $("#location_three").val(),
				testingFacility: $("#testingFacility").val()
			},
			function(data) {
				$("#testingQualityTable").html(data);
			});
	}



	function getQualityControlByMonth() {
		var format = null;
		if ($('#quality-control-by-month').prop('checked')) {
			format = 'percentage';
		} else {
			format = 'number';
		}
		$.post("<?php echo $this->url('quality-check', array('action' => 'get-month-wise-quality-control')); ?>", {
			format: format,
			format: format,
			sampleTestedDates: $("#sampleTestedDates").val(),
			locationOne: $("#location_one").val(),
			locationTwo: $("#location_two").val(),
			locationThree: $("#location_three").val(),
			fName: $("#facilityId").val(),
			testingFacility: $("#testingFacility").val()
		},
		function(data) {
			$("#qualityControlByMonthwise").html(data);
		});
	}
	function onhide(){
		$('.sticky-div').css('position','inherit');
		$('.hide-div').hide(500);
		hidebtn = false;
	}

	$(document).scroll(function() {
		if ($(window).width() < 768) {
				$('.sticky-div').css('position', 'inherit');
				$('.hide-div').hide(500);
				hidebtn = false;
		}else{
			if(hidebtn){
				if($(window).scrollTop() > 159){
					$('.hide-div').show(500);
					$('.sticky-div').css('position', 'sticky');
				}else{
					$('.hide-div').hide(500);
				}
			}
		}
	});
</script>