<?php
$per = (($result['minimum'] * 100) / $result['total']);
?>
<script>
    var gaugeOptions = {
        chart: {
            type: 'solidgauge'
        },

        title: null,

        pane: {
            center: ['50%', '35%'],
            size: '70%',
            startAngle: -90,
            endAngle: 90,
            background: {
                backgroundColor: Highcharts.defaultOptions.legend.backgroundColor || '#EEE',
                innerRadius: '60%',
                outerRadius: '100%',
                shape: 'arc',
            }
        },

        tooltip: {
            enabled: false
        },

        plotOptions: {
            solidgauge: {
                dataLabels: {
                    borderWidth: 0,
                }
            },
        }
    };

    // The speed gauge
    var chartSpeed = Highcharts.chart('<?php echo $result['bind'];?>', Highcharts.merge(gaugeOptions, {
        yAxis: {
            min: 0,
            max: 100,
            tickInterval: 0,
            labels: {
                enabled: false
            },
        },

        credits: {
            enabled: false
        },

        navigation: {
            buttonOptions: {
                enabled: false
            }
        },

        series: [{
            data: [<?php echo (isset($per) && $per > 0)?round(number_format($per,2)):0;?>],
            dataLabels: {
                format: '<div style="text-align:center">' +
                    '<span style="font-weight: 400px !important;font-size:2.5rem;color: #fb885f !important;transform: scale(1, 1.5); -webkit-transform: scale(1, 1.2); -moz-transform: scale(1, 1.5); -ms-transform: scale(1, 1.5); -o-transform: scale(1, 1.5);">{y} %</span><br/>' +
                    '</div>',
            }
        }],
    }));
</script>