<?php

use Laminas\Session\Container;

$sessionLogin = new Container('credo');
$roleCode = $sessionLogin->roleCode;
$acl=$this->layout()->acl;
//$editAction = '{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center","bSortable":false}';
?>
<style>
    .thCenter {
        text-align: center;
        vertical-align: middle;
    }
</style>
<link rel="stylesheet" href="<?php echo $this->basePath() . '/assets/plugins/datepicker/daterangepicker.css' ?>" rel="stylesheet">
<div class="bg-body-light">
    <div class="content content-full">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
            <h1 class="flex-sm-fill font-size-h2 font-w400 mt-2 mb-0 mb-sm-2">Weekly Report</h1>
        </div>
    </div>
</div>
<div class="content">
    <div class="block block-rounded block-bordered">
        <div class="block-header block-header-default"></div>

        <div class="block-content block-content-full">
            <div class="form-group row">
                <label style=" margin-bottom: 2.5%; " class="col-sm-2 col-form-label" for="">Sample Collection Date</label>
                <div class="col-sm-4">
                    <input type="text" id="samplesCollectionDate" name="samplesCollectionDate" class="form-control" placeholder="Select Date Range" readonly style="background:#fff;" />
                </div>

                <label style=" margin-bottom: 2.5%; " class="col-sm-2 col-form-label" for="">Testing Site</label>
                <div class="col-sm-4">
                    <select class="form-control" id="testingFacility" name="testingFacility" title="Please select testing facility name" style="width:100%;">
                        <option value=""> -- Select -- </option>
                        <?php
                        foreach ($facilityResult['facilityTest'] as $facilityRow) {
                            //if(2 != (int)$facilityRow['facility_type_id']) continue;
                        ?>
                            <option value="<?php echo $facilityRow['facility_id']; ?>"><?php echo ucwords($facilityRow['facility_name']); ?></option>
                        <?php
                        }
                        ?>
                    </select>
                </div>
                <label style=" margin-bottom: 2.5%; " class="col-sm-2 col-form-label" for="Province">Province</label>
            <div class="col-sm-4">
            <select class="form-control <?php echo $locationOne; ?>" id="<?php echo $globalConfigResult[0]['global_name']; ?>" name="<?php echo $globalConfigResult[0]['global_name']; ?>" placeholder="Enter the <?php echo lcfirst($globalConfigResult[0]['global_value']); ?>" title="Please enter the <?php echo lcfirst($globalConfigResult[0]['global_value']); ?>" onchange="getLocationDeatils('<?php echo $globalConfigResult[0]['global_name']; ?>');">
                                         <option value="">-- Select --</option>
                        </select>
            </div>
            <label style=" margin-bottom: 2.5%; " class="col-sm-2 col-form-label" for="District">District:</label>
            <div class="col-sm-4">
            <select class="form-control <?php echo $locationTwo; ?>" id="<?php echo $globalConfigResult[1]['global_name']; ?>" name="<?php echo $globalConfigResult[1]['global_name']; ?>" placeholder="Enter the <?php echo lcfirst($globalConfigResult[1]['global_value']); ?>" title="Please enter the <?php echo lcfirst($globalConfigResult[1]['global_value']); ?>" onchange="getLocationDeatils('<?php echo $globalConfigResult[1]['global_name']; ?>');">
                        <option value="">-- Select --</option>
                </select>
            </div>
                <label style=" margin-bottom: 2.5%; " class="col-sm-2 col-form-label" for="">Facility Name</label>
                <div class="col-sm-4">
                    <select class="form-control" id="facilityName" name="facilityName" title="Please select facility name" style="width:100%;">
                        <option value=""> -- Select -- </option>
                        <?php
                        foreach ($facilityResult['facility'] as $facilityRow) {
                            // if(2 == (int)$facilityRow['facility_type_id']) continue;
                        ?>
                            <option value="<?php echo base64_encode($facilityRow['facility_id']); ?>"><?php echo ($facilityRow['facility_name']); ?></option>
                        <?php
                        }
                        ?>
                    </select>
                </div>
                <label style=" margin-bottom: 2.5%; " class="col-sm-2 col-form-label" for="hivRecencyTest">HIV Recency Test Dates:</label>
                <div class="col-sm-4">
                    <input type="text" class="form-control" id="hivRecencyTest" placeholder="Hiv Recency Test Date" name="hivRecencyTest" title="Please select HIV Recency Test Dates" style="width:100%;" readonly>
                </div>
            </div>
            <div class="row items-push">
                <div class="col-lg-7 ">
                    <a href="javascript:void(0);" class="btn btn-primary" onclick="searchData();"><i class="fa fa-fw fa-check"></i> Search</a>
                    <?php if (isset($acl) && $acl->isAllowed($roleCode, 'Application\Controller\ReportsController', 'export-weekly-report')) { ?>
                        <a href="javascript:void(0);" class="btn btn-success" onclick="exportWeeklyData();"><i class="fa fa-download"></i>&nbsp;Export Excel</a>
                    <?php } ?>
                </div>
            </div>
            <table id="tatTable" class="table table-bordered table-striped table-vcenter">
                <thead>
                    <tr>
                        <th rowspan="2" class="thCenter">Samples Received</th>
                        <th rowspan="2" class="thCenter">Samples Pending to be Tested</th>
                        <th rowspan="2" class="thCenter">Samples Tested</th>
                        <th colspan="3" class="thCenter" style="background-color:#9cc2e5;">Recency Testing Results(Asante)</th>
                        <th colspan="2" class="thCenter" style="background-color:#ebed89;">Assay Recent VL Results </th>
                        <th colspan="3" class="thCenter" style="background-color:#11aa06;">Final Results</th>
                    </tr>
                    <tr>
                        <th class="thCenter testingResult">Assay Recent</th>
                        <th class="thCenter testingResult">Long Term</th>
                        <th class="thCenter testingResult">Assay Negative</th>
                        <th class="thCenter vlResult">Done</th>
                        <th class="thCenter vlResult">Pending</th>
                        <th class="thCenter finalResult">RITA Recent</th>
                        <th class="thCenter finalResult">Long Term</th>
                        <th class="thCenter finalResult">Inconclusive</th>
                    </tr>
                </thead>
                <tbody id="weeklyData">
                    <tr>
                        <td colspan='6' class='dataTables_empty'>Loading data from server</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

<script type="text/javascript">
    let searchExecuted = false;
    /* Table initialisation */
    oTable = null;
    $(document).ready(function() {
        $('#page-container').removeClass('sidebar-o');
        $("#facilityName").select2({
            placeholder: "Choose Facility",
            width: "290px",
            allowClear: true,
        });
        $("#testingFacility").select2({
            placeholder: "Choose Testing Site",
            width: "290px",
            allowClear: true,
        });

        $('#samplesCollectionDate').daterangepicker({
                format: 'DD-MMM-YYYY',
                separator: ' to ',
                startDate: moment().subtract('days', 30),
                endDate: moment(),
                maxDate: moment(),
                ranges: {
                    'Today': [moment(), moment()],
                    'Yesterday': [moment().subtract('days', 1), moment().subtract('days', 1)],
                    'Last 7 Days': [moment().subtract('days', 6), moment()],
                    'Last 30 Days': [moment().subtract('days', 29), moment()],
                    'Last 60 Days': [moment().subtract('days', 59), moment()],
                    'Last 180 Days': [moment().subtract('days', 179), moment()],
                    'This Month': [moment().startOf('month'), moment().endOf('month')],
                    'Last Month': [moment().subtract('month', 1).startOf('month'), moment().subtract('month', 1).endOf('month')]
                }
            },
            function(start, end) {
                startDate = start.format('YYYY-MM-DD');
                endDate = end.format('YYYY-MM-DD');
            });

        $('#hivRecencyTest').daterangepicker({
                format: 'DD-MMM-YYYY',
                autoUpdateInput: false,
                separator: ' to ',
                startDate: moment().subtract('days', 29),
                endDate: moment(),
                maxDate: moment(),
                ranges: {
                    'Today': [moment(), moment()],
                    'Yesterday': [moment().subtract('days', 1), moment().subtract('days', 1)],
                    'Last 7 Days': [moment().subtract('days', 6), moment()],
                    'Last 30 Days': [moment().subtract('days', 29), moment()],
                    'Last 60 Days': [moment().subtract('days', 59), moment()],
                    'Last 180 Days': [moment().subtract('days', 179), moment()],
                    'This Month': [moment().startOf('month'), moment().endOf('month')],
                    'Last Month': [moment().subtract('month', 1).startOf('month'), moment().subtract('month', 1).endOf('month')]
                }
            },
            function(start, end) {
                startDate = start.format('YYYY-MM-DD');
                endDate = end.format('YYYY-MM-DD');
                $('input[name="hivRecencyTest"]').on('apply.daterangepicker', function(ev, picker) {
                    $(this).val(picker.startDate.format('DD-MMM-YYYY') + ' to ' + picker.endDate.format('DD-MMM-YYYY'));
                });

            });

        $("#advanceFilter input, #advanceFilter select").on("change", function() {
            searchExecuted = false;
        });

        getWeeklyData();

        <?php foreach ($globalConfigResult as $config) { ?>
            getLocationDeatils('<?php echo $config["global_name"]; ?>');
        <?php break;
        } ?>
    });

    function searchData() {
        searchExecuted = true;
        $.blockUI();
        getWeeklyData();
        $.unblockUI();
    }

    function getWeeklyData() {
        var samplesCollectionDate = $("#samplesCollectionDate").val();
        $.blockUI();
        $.post("<?php echo $this->url('reports', array('action' => 'get-weekly-report')); ?>", {
                samplesCollectionDate: samplesCollectionDate,
                testingFacility: $("#testingFacility").val(),
                province: $("#location_one").val(),
                district: $("#location_two").val(),
                facilityName: $("#facilityName").val(),
                hivRecencyTest: $("#hivRecencyTest").val()
            },
            function(data) {
                $("#weeklyData").html(data);
                $.unblockUI();
            });
    }

    function exportWeeklyData() {
        if (searchExecuted === false) {
            getWeeklyData();
        }
        $.blockUI();
        $.post("<?php echo $this->url('reports', array('action' => 'export-weekly-report')); ?>",
            function(data) {
                if (data == "" || data == null || data == undefined) {
                    $.unblockUI();
                    alert('Unable to generate download');
                } else {
                    $.unblockUI();
                    document.location.href = '/temporary/' + data;
                }
            });
    }

    function getLocationDeatils(globalName) {
        var selectValue = document.getElementById(globalName).value;
        var innerId = '';
        var path = '';

        if (globalName == 'location_one' && selectValue == '') {
            path = 'get-province';
            innerId = 'location_one';
        } else if (globalName == 'location_one' && selectValue != '') {
            path = 'get-district';
            innerId = 'location_two';
            $("#location_three").html("<option value=''>-- Select --</option>");

        } else if (globalName == 'location_two' && selectValue != '') {
            path = 'get-city';
            innerId = 'location_three';
            if (selectValue == 'other') {
                $("#otherDistrictName").show();
                $("#otherDistrictName").addClass('isRequired');
            } else {
                $("#otherDistrictName").hide();
                $("#otherDistrictName").removeClass('isRequired');
            }
        } else if (globalName == 'location_three' && selectValue != '') {
            path = 'get-facility';
            if (selectValue == 'other') {
                $("#otherCityName").show();
                $("#otherCityName").addClass('isRequired');
            } else {
                $("#otherCityName").hide();
                $("#otherCityName").removeClass('isRequired');
            }
        }
        if (path != '') {
            $.blockUI();
            $.post("/common/" + path, {
                    selectValue: selectValue
                },
                function(data) {
                    if (globalName == 'location_one' && selectValue != '') {
                        var splitOption = data.split("##");
                        $("#" + innerId).html(splitOption[0]);
                        $("#facilityName").html(splitOption[1]);
                    } else if (globalName == 'location_two' && selectValue != '') {
                        var splitOption = data.split("##");
                        $("#" + innerId).html(splitOption[0]);
                        $("#facilityName").html(splitOption[1]);
                    } else if (globalName == 'location_three' && selectValue != '') {
                        $("#facilityName").html(data);
                    } else {
                        $("#" + innerId).html(data);
                    }
                    $.unblockUI();
                });
        }
    }
</script>